import * as _302 from "./abci/types";
import * as _303 from "./crypto/keys";
import * as _304 from "./crypto/proof";
import * as _305 from "./libs/bits/types";
import * as _306 from "./p2p/types";
import * as _307 from "./types/block";
import * as _308 from "./types/evidence";
import * as _309 from "./types/params";
import * as _310 from "./types/types";
import * as _311 from "./types/validator";
import * as _312 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _302.CheckTxType;
        checkTxTypeToJSON(object: _302.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _302.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _302.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _302.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _302.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _302.EvidenceType;
        evidenceTypeToJSON(object: _302.EvidenceType): string;
        CheckTxType: typeof _302.CheckTxType;
        CheckTxTypeSDKType: typeof _302.CheckTxType;
        CheckTxTypeAmino: typeof _302.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _302.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _302.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _302.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _302.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _302.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _302.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _302.EvidenceType;
        EvidenceTypeSDKType: typeof _302.EvidenceType;
        EvidenceTypeAmino: typeof _302.EvidenceType;
        Request: {
            encode(message: _302.Request, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Request;
            fromJSON(object: any): _302.Request;
            toJSON(message: _302.Request): unknown;
            fromPartial(object: Partial<_302.Request>): _302.Request;
            fromAmino(object: _302.RequestAmino): _302.Request;
            toAmino(message: _302.Request): _302.RequestAmino;
            fromAminoMsg(object: _302.RequestAminoMsg): _302.Request;
            fromProtoMsg(message: _302.RequestProtoMsg): _302.Request;
            toProto(message: _302.Request): Uint8Array;
            toProtoMsg(message: _302.Request): _302.RequestProtoMsg;
        };
        RequestEcho: {
            encode(message: _302.RequestEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestEcho;
            fromJSON(object: any): _302.RequestEcho;
            toJSON(message: _302.RequestEcho): unknown;
            fromPartial(object: Partial<_302.RequestEcho>): _302.RequestEcho;
            fromAmino(object: _302.RequestEchoAmino): _302.RequestEcho;
            toAmino(message: _302.RequestEcho): _302.RequestEchoAmino;
            fromAminoMsg(object: _302.RequestEchoAminoMsg): _302.RequestEcho;
            fromProtoMsg(message: _302.RequestEchoProtoMsg): _302.RequestEcho;
            toProto(message: _302.RequestEcho): Uint8Array;
            toProtoMsg(message: _302.RequestEcho): _302.RequestEchoProtoMsg;
        };
        RequestFlush: {
            encode(_: _302.RequestFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestFlush;
            fromJSON(_: any): _302.RequestFlush;
            toJSON(_: _302.RequestFlush): unknown;
            fromPartial(_: Partial<_302.RequestFlush>): _302.RequestFlush;
            fromAmino(_: _302.RequestFlushAmino): _302.RequestFlush;
            toAmino(_: _302.RequestFlush): _302.RequestFlushAmino;
            fromAminoMsg(object: _302.RequestFlushAminoMsg): _302.RequestFlush;
            fromProtoMsg(message: _302.RequestFlushProtoMsg): _302.RequestFlush;
            toProto(message: _302.RequestFlush): Uint8Array;
            toProtoMsg(message: _302.RequestFlush): _302.RequestFlushProtoMsg;
        };
        RequestInfo: {
            encode(message: _302.RequestInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestInfo;
            fromJSON(object: any): _302.RequestInfo;
            toJSON(message: _302.RequestInfo): unknown;
            fromPartial(object: Partial<_302.RequestInfo>): _302.RequestInfo;
            fromAmino(object: _302.RequestInfoAmino): _302.RequestInfo;
            toAmino(message: _302.RequestInfo): _302.RequestInfoAmino;
            fromAminoMsg(object: _302.RequestInfoAminoMsg): _302.RequestInfo;
            fromProtoMsg(message: _302.RequestInfoProtoMsg): _302.RequestInfo;
            toProto(message: _302.RequestInfo): Uint8Array;
            toProtoMsg(message: _302.RequestInfo): _302.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            encode(message: _302.RequestSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestSetOption;
            fromJSON(object: any): _302.RequestSetOption;
            toJSON(message: _302.RequestSetOption): unknown;
            fromPartial(object: Partial<_302.RequestSetOption>): _302.RequestSetOption;
            fromAmino(object: _302.RequestSetOptionAmino): _302.RequestSetOption;
            toAmino(message: _302.RequestSetOption): _302.RequestSetOptionAmino;
            fromAminoMsg(object: _302.RequestSetOptionAminoMsg): _302.RequestSetOption;
            fromProtoMsg(message: _302.RequestSetOptionProtoMsg): _302.RequestSetOption;
            toProto(message: _302.RequestSetOption): Uint8Array;
            toProtoMsg(message: _302.RequestSetOption): _302.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            encode(message: _302.RequestInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestInitChain;
            fromJSON(object: any): _302.RequestInitChain;
            toJSON(message: _302.RequestInitChain): unknown;
            fromPartial(object: Partial<_302.RequestInitChain>): _302.RequestInitChain;
            fromAmino(object: _302.RequestInitChainAmino): _302.RequestInitChain;
            toAmino(message: _302.RequestInitChain): _302.RequestInitChainAmino;
            fromAminoMsg(object: _302.RequestInitChainAminoMsg): _302.RequestInitChain;
            fromProtoMsg(message: _302.RequestInitChainProtoMsg): _302.RequestInitChain;
            toProto(message: _302.RequestInitChain): Uint8Array;
            toProtoMsg(message: _302.RequestInitChain): _302.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            encode(message: _302.RequestQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestQuery;
            fromJSON(object: any): _302.RequestQuery;
            toJSON(message: _302.RequestQuery): unknown;
            fromPartial(object: Partial<_302.RequestQuery>): _302.RequestQuery;
            fromAmino(object: _302.RequestQueryAmino): _302.RequestQuery;
            toAmino(message: _302.RequestQuery): _302.RequestQueryAmino;
            fromAminoMsg(object: _302.RequestQueryAminoMsg): _302.RequestQuery;
            fromProtoMsg(message: _302.RequestQueryProtoMsg): _302.RequestQuery;
            toProto(message: _302.RequestQuery): Uint8Array;
            toProtoMsg(message: _302.RequestQuery): _302.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            encode(message: _302.RequestBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestBeginBlock;
            fromJSON(object: any): _302.RequestBeginBlock;
            toJSON(message: _302.RequestBeginBlock): unknown;
            fromPartial(object: Partial<_302.RequestBeginBlock>): _302.RequestBeginBlock;
            fromAmino(object: _302.RequestBeginBlockAmino): _302.RequestBeginBlock;
            toAmino(message: _302.RequestBeginBlock): _302.RequestBeginBlockAmino;
            fromAminoMsg(object: _302.RequestBeginBlockAminoMsg): _302.RequestBeginBlock;
            fromProtoMsg(message: _302.RequestBeginBlockProtoMsg): _302.RequestBeginBlock;
            toProto(message: _302.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _302.RequestBeginBlock): _302.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            encode(message: _302.RequestCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestCheckTx;
            fromJSON(object: any): _302.RequestCheckTx;
            toJSON(message: _302.RequestCheckTx): unknown;
            fromPartial(object: Partial<_302.RequestCheckTx>): _302.RequestCheckTx;
            fromAmino(object: _302.RequestCheckTxAmino): _302.RequestCheckTx;
            toAmino(message: _302.RequestCheckTx): _302.RequestCheckTxAmino;
            fromAminoMsg(object: _302.RequestCheckTxAminoMsg): _302.RequestCheckTx;
            fromProtoMsg(message: _302.RequestCheckTxProtoMsg): _302.RequestCheckTx;
            toProto(message: _302.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _302.RequestCheckTx): _302.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            encode(message: _302.RequestDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestDeliverTx;
            fromJSON(object: any): _302.RequestDeliverTx;
            toJSON(message: _302.RequestDeliverTx): unknown;
            fromPartial(object: Partial<_302.RequestDeliverTx>): _302.RequestDeliverTx;
            fromAmino(object: _302.RequestDeliverTxAmino): _302.RequestDeliverTx;
            toAmino(message: _302.RequestDeliverTx): _302.RequestDeliverTxAmino;
            fromAminoMsg(object: _302.RequestDeliverTxAminoMsg): _302.RequestDeliverTx;
            fromProtoMsg(message: _302.RequestDeliverTxProtoMsg): _302.RequestDeliverTx;
            toProto(message: _302.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _302.RequestDeliverTx): _302.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            encode(message: _302.RequestEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestEndBlock;
            fromJSON(object: any): _302.RequestEndBlock;
            toJSON(message: _302.RequestEndBlock): unknown;
            fromPartial(object: Partial<_302.RequestEndBlock>): _302.RequestEndBlock;
            fromAmino(object: _302.RequestEndBlockAmino): _302.RequestEndBlock;
            toAmino(message: _302.RequestEndBlock): _302.RequestEndBlockAmino;
            fromAminoMsg(object: _302.RequestEndBlockAminoMsg): _302.RequestEndBlock;
            fromProtoMsg(message: _302.RequestEndBlockProtoMsg): _302.RequestEndBlock;
            toProto(message: _302.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _302.RequestEndBlock): _302.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            encode(_: _302.RequestCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestCommit;
            fromJSON(_: any): _302.RequestCommit;
            toJSON(_: _302.RequestCommit): unknown;
            fromPartial(_: Partial<_302.RequestCommit>): _302.RequestCommit;
            fromAmino(_: _302.RequestCommitAmino): _302.RequestCommit;
            toAmino(_: _302.RequestCommit): _302.RequestCommitAmino;
            fromAminoMsg(object: _302.RequestCommitAminoMsg): _302.RequestCommit;
            fromProtoMsg(message: _302.RequestCommitProtoMsg): _302.RequestCommit;
            toProto(message: _302.RequestCommit): Uint8Array;
            toProtoMsg(message: _302.RequestCommit): _302.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            encode(_: _302.RequestListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestListSnapshots;
            fromJSON(_: any): _302.RequestListSnapshots;
            toJSON(_: _302.RequestListSnapshots): unknown;
            fromPartial(_: Partial<_302.RequestListSnapshots>): _302.RequestListSnapshots;
            fromAmino(_: _302.RequestListSnapshotsAmino): _302.RequestListSnapshots;
            toAmino(_: _302.RequestListSnapshots): _302.RequestListSnapshotsAmino;
            fromAminoMsg(object: _302.RequestListSnapshotsAminoMsg): _302.RequestListSnapshots;
            fromProtoMsg(message: _302.RequestListSnapshotsProtoMsg): _302.RequestListSnapshots;
            toProto(message: _302.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _302.RequestListSnapshots): _302.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            encode(message: _302.RequestOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestOfferSnapshot;
            fromJSON(object: any): _302.RequestOfferSnapshot;
            toJSON(message: _302.RequestOfferSnapshot): unknown;
            fromPartial(object: Partial<_302.RequestOfferSnapshot>): _302.RequestOfferSnapshot;
            fromAmino(object: _302.RequestOfferSnapshotAmino): _302.RequestOfferSnapshot;
            toAmino(message: _302.RequestOfferSnapshot): _302.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _302.RequestOfferSnapshotAminoMsg): _302.RequestOfferSnapshot;
            fromProtoMsg(message: _302.RequestOfferSnapshotProtoMsg): _302.RequestOfferSnapshot;
            toProto(message: _302.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _302.RequestOfferSnapshot): _302.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            encode(message: _302.RequestLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestLoadSnapshotChunk;
            fromJSON(object: any): _302.RequestLoadSnapshotChunk;
            toJSON(message: _302.RequestLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_302.RequestLoadSnapshotChunk>): _302.RequestLoadSnapshotChunk;
            fromAmino(object: _302.RequestLoadSnapshotChunkAmino): _302.RequestLoadSnapshotChunk;
            toAmino(message: _302.RequestLoadSnapshotChunk): _302.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _302.RequestLoadSnapshotChunkAminoMsg): _302.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _302.RequestLoadSnapshotChunkProtoMsg): _302.RequestLoadSnapshotChunk;
            toProto(message: _302.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _302.RequestLoadSnapshotChunk): _302.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            encode(message: _302.RequestApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.RequestApplySnapshotChunk;
            fromJSON(object: any): _302.RequestApplySnapshotChunk;
            toJSON(message: _302.RequestApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_302.RequestApplySnapshotChunk>): _302.RequestApplySnapshotChunk;
            fromAmino(object: _302.RequestApplySnapshotChunkAmino): _302.RequestApplySnapshotChunk;
            toAmino(message: _302.RequestApplySnapshotChunk): _302.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _302.RequestApplySnapshotChunkAminoMsg): _302.RequestApplySnapshotChunk;
            fromProtoMsg(message: _302.RequestApplySnapshotChunkProtoMsg): _302.RequestApplySnapshotChunk;
            toProto(message: _302.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _302.RequestApplySnapshotChunk): _302.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            encode(message: _302.Response, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Response;
            fromJSON(object: any): _302.Response;
            toJSON(message: _302.Response): unknown;
            fromPartial(object: Partial<_302.Response>): _302.Response;
            fromAmino(object: _302.ResponseAmino): _302.Response;
            toAmino(message: _302.Response): _302.ResponseAmino;
            fromAminoMsg(object: _302.ResponseAminoMsg): _302.Response;
            fromProtoMsg(message: _302.ResponseProtoMsg): _302.Response;
            toProto(message: _302.Response): Uint8Array;
            toProtoMsg(message: _302.Response): _302.ResponseProtoMsg;
        };
        ResponseException: {
            encode(message: _302.ResponseException, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseException;
            fromJSON(object: any): _302.ResponseException;
            toJSON(message: _302.ResponseException): unknown;
            fromPartial(object: Partial<_302.ResponseException>): _302.ResponseException;
            fromAmino(object: _302.ResponseExceptionAmino): _302.ResponseException;
            toAmino(message: _302.ResponseException): _302.ResponseExceptionAmino;
            fromAminoMsg(object: _302.ResponseExceptionAminoMsg): _302.ResponseException;
            fromProtoMsg(message: _302.ResponseExceptionProtoMsg): _302.ResponseException;
            toProto(message: _302.ResponseException): Uint8Array;
            toProtoMsg(message: _302.ResponseException): _302.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            encode(message: _302.ResponseEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseEcho;
            fromJSON(object: any): _302.ResponseEcho;
            toJSON(message: _302.ResponseEcho): unknown;
            fromPartial(object: Partial<_302.ResponseEcho>): _302.ResponseEcho;
            fromAmino(object: _302.ResponseEchoAmino): _302.ResponseEcho;
            toAmino(message: _302.ResponseEcho): _302.ResponseEchoAmino;
            fromAminoMsg(object: _302.ResponseEchoAminoMsg): _302.ResponseEcho;
            fromProtoMsg(message: _302.ResponseEchoProtoMsg): _302.ResponseEcho;
            toProto(message: _302.ResponseEcho): Uint8Array;
            toProtoMsg(message: _302.ResponseEcho): _302.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            encode(_: _302.ResponseFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseFlush;
            fromJSON(_: any): _302.ResponseFlush;
            toJSON(_: _302.ResponseFlush): unknown;
            fromPartial(_: Partial<_302.ResponseFlush>): _302.ResponseFlush;
            fromAmino(_: _302.ResponseFlushAmino): _302.ResponseFlush;
            toAmino(_: _302.ResponseFlush): _302.ResponseFlushAmino;
            fromAminoMsg(object: _302.ResponseFlushAminoMsg): _302.ResponseFlush;
            fromProtoMsg(message: _302.ResponseFlushProtoMsg): _302.ResponseFlush;
            toProto(message: _302.ResponseFlush): Uint8Array;
            toProtoMsg(message: _302.ResponseFlush): _302.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            encode(message: _302.ResponseInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseInfo;
            fromJSON(object: any): _302.ResponseInfo;
            toJSON(message: _302.ResponseInfo): unknown;
            fromPartial(object: Partial<_302.ResponseInfo>): _302.ResponseInfo;
            fromAmino(object: _302.ResponseInfoAmino): _302.ResponseInfo;
            toAmino(message: _302.ResponseInfo): _302.ResponseInfoAmino;
            fromAminoMsg(object: _302.ResponseInfoAminoMsg): _302.ResponseInfo;
            fromProtoMsg(message: _302.ResponseInfoProtoMsg): _302.ResponseInfo;
            toProto(message: _302.ResponseInfo): Uint8Array;
            toProtoMsg(message: _302.ResponseInfo): _302.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            encode(message: _302.ResponseSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseSetOption;
            fromJSON(object: any): _302.ResponseSetOption;
            toJSON(message: _302.ResponseSetOption): unknown;
            fromPartial(object: Partial<_302.ResponseSetOption>): _302.ResponseSetOption;
            fromAmino(object: _302.ResponseSetOptionAmino): _302.ResponseSetOption;
            toAmino(message: _302.ResponseSetOption): _302.ResponseSetOptionAmino;
            fromAminoMsg(object: _302.ResponseSetOptionAminoMsg): _302.ResponseSetOption;
            fromProtoMsg(message: _302.ResponseSetOptionProtoMsg): _302.ResponseSetOption;
            toProto(message: _302.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _302.ResponseSetOption): _302.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            encode(message: _302.ResponseInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseInitChain;
            fromJSON(object: any): _302.ResponseInitChain;
            toJSON(message: _302.ResponseInitChain): unknown;
            fromPartial(object: Partial<_302.ResponseInitChain>): _302.ResponseInitChain;
            fromAmino(object: _302.ResponseInitChainAmino): _302.ResponseInitChain;
            toAmino(message: _302.ResponseInitChain): _302.ResponseInitChainAmino;
            fromAminoMsg(object: _302.ResponseInitChainAminoMsg): _302.ResponseInitChain;
            fromProtoMsg(message: _302.ResponseInitChainProtoMsg): _302.ResponseInitChain;
            toProto(message: _302.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _302.ResponseInitChain): _302.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            encode(message: _302.ResponseQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseQuery;
            fromJSON(object: any): _302.ResponseQuery;
            toJSON(message: _302.ResponseQuery): unknown;
            fromPartial(object: Partial<_302.ResponseQuery>): _302.ResponseQuery;
            fromAmino(object: _302.ResponseQueryAmino): _302.ResponseQuery;
            toAmino(message: _302.ResponseQuery): _302.ResponseQueryAmino;
            fromAminoMsg(object: _302.ResponseQueryAminoMsg): _302.ResponseQuery;
            fromProtoMsg(message: _302.ResponseQueryProtoMsg): _302.ResponseQuery;
            toProto(message: _302.ResponseQuery): Uint8Array;
            toProtoMsg(message: _302.ResponseQuery): _302.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            encode(message: _302.ResponseBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseBeginBlock;
            fromJSON(object: any): _302.ResponseBeginBlock;
            toJSON(message: _302.ResponseBeginBlock): unknown;
            fromPartial(object: Partial<_302.ResponseBeginBlock>): _302.ResponseBeginBlock;
            fromAmino(object: _302.ResponseBeginBlockAmino): _302.ResponseBeginBlock;
            toAmino(message: _302.ResponseBeginBlock): _302.ResponseBeginBlockAmino;
            fromAminoMsg(object: _302.ResponseBeginBlockAminoMsg): _302.ResponseBeginBlock;
            fromProtoMsg(message: _302.ResponseBeginBlockProtoMsg): _302.ResponseBeginBlock;
            toProto(message: _302.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _302.ResponseBeginBlock): _302.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            encode(message: _302.ResponseCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseCheckTx;
            fromJSON(object: any): _302.ResponseCheckTx;
            toJSON(message: _302.ResponseCheckTx): unknown;
            fromPartial(object: Partial<_302.ResponseCheckTx>): _302.ResponseCheckTx;
            fromAmino(object: _302.ResponseCheckTxAmino): _302.ResponseCheckTx;
            toAmino(message: _302.ResponseCheckTx): _302.ResponseCheckTxAmino;
            fromAminoMsg(object: _302.ResponseCheckTxAminoMsg): _302.ResponseCheckTx;
            fromProtoMsg(message: _302.ResponseCheckTxProtoMsg): _302.ResponseCheckTx;
            toProto(message: _302.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _302.ResponseCheckTx): _302.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            encode(message: _302.ResponseDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseDeliverTx;
            fromJSON(object: any): _302.ResponseDeliverTx;
            toJSON(message: _302.ResponseDeliverTx): unknown;
            fromPartial(object: Partial<_302.ResponseDeliverTx>): _302.ResponseDeliverTx;
            fromAmino(object: _302.ResponseDeliverTxAmino): _302.ResponseDeliverTx;
            toAmino(message: _302.ResponseDeliverTx): _302.ResponseDeliverTxAmino;
            fromAminoMsg(object: _302.ResponseDeliverTxAminoMsg): _302.ResponseDeliverTx;
            fromProtoMsg(message: _302.ResponseDeliverTxProtoMsg): _302.ResponseDeliverTx;
            toProto(message: _302.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _302.ResponseDeliverTx): _302.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            encode(message: _302.ResponseEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseEndBlock;
            fromJSON(object: any): _302.ResponseEndBlock;
            toJSON(message: _302.ResponseEndBlock): unknown;
            fromPartial(object: Partial<_302.ResponseEndBlock>): _302.ResponseEndBlock;
            fromAmino(object: _302.ResponseEndBlockAmino): _302.ResponseEndBlock;
            toAmino(message: _302.ResponseEndBlock): _302.ResponseEndBlockAmino;
            fromAminoMsg(object: _302.ResponseEndBlockAminoMsg): _302.ResponseEndBlock;
            fromProtoMsg(message: _302.ResponseEndBlockProtoMsg): _302.ResponseEndBlock;
            toProto(message: _302.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _302.ResponseEndBlock): _302.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            encode(message: _302.ResponseCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseCommit;
            fromJSON(object: any): _302.ResponseCommit;
            toJSON(message: _302.ResponseCommit): unknown;
            fromPartial(object: Partial<_302.ResponseCommit>): _302.ResponseCommit;
            fromAmino(object: _302.ResponseCommitAmino): _302.ResponseCommit;
            toAmino(message: _302.ResponseCommit): _302.ResponseCommitAmino;
            fromAminoMsg(object: _302.ResponseCommitAminoMsg): _302.ResponseCommit;
            fromProtoMsg(message: _302.ResponseCommitProtoMsg): _302.ResponseCommit;
            toProto(message: _302.ResponseCommit): Uint8Array;
            toProtoMsg(message: _302.ResponseCommit): _302.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            encode(message: _302.ResponseListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseListSnapshots;
            fromJSON(object: any): _302.ResponseListSnapshots;
            toJSON(message: _302.ResponseListSnapshots): unknown;
            fromPartial(object: Partial<_302.ResponseListSnapshots>): _302.ResponseListSnapshots;
            fromAmino(object: _302.ResponseListSnapshotsAmino): _302.ResponseListSnapshots;
            toAmino(message: _302.ResponseListSnapshots): _302.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _302.ResponseListSnapshotsAminoMsg): _302.ResponseListSnapshots;
            fromProtoMsg(message: _302.ResponseListSnapshotsProtoMsg): _302.ResponseListSnapshots;
            toProto(message: _302.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _302.ResponseListSnapshots): _302.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            encode(message: _302.ResponseOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseOfferSnapshot;
            fromJSON(object: any): _302.ResponseOfferSnapshot;
            toJSON(message: _302.ResponseOfferSnapshot): unknown;
            fromPartial(object: Partial<_302.ResponseOfferSnapshot>): _302.ResponseOfferSnapshot;
            fromAmino(object: _302.ResponseOfferSnapshotAmino): _302.ResponseOfferSnapshot;
            toAmino(message: _302.ResponseOfferSnapshot): _302.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _302.ResponseOfferSnapshotAminoMsg): _302.ResponseOfferSnapshot;
            fromProtoMsg(message: _302.ResponseOfferSnapshotProtoMsg): _302.ResponseOfferSnapshot;
            toProto(message: _302.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _302.ResponseOfferSnapshot): _302.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            encode(message: _302.ResponseLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseLoadSnapshotChunk;
            fromJSON(object: any): _302.ResponseLoadSnapshotChunk;
            toJSON(message: _302.ResponseLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_302.ResponseLoadSnapshotChunk>): _302.ResponseLoadSnapshotChunk;
            fromAmino(object: _302.ResponseLoadSnapshotChunkAmino): _302.ResponseLoadSnapshotChunk;
            toAmino(message: _302.ResponseLoadSnapshotChunk): _302.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _302.ResponseLoadSnapshotChunkAminoMsg): _302.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _302.ResponseLoadSnapshotChunkProtoMsg): _302.ResponseLoadSnapshotChunk;
            toProto(message: _302.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _302.ResponseLoadSnapshotChunk): _302.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            encode(message: _302.ResponseApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ResponseApplySnapshotChunk;
            fromJSON(object: any): _302.ResponseApplySnapshotChunk;
            toJSON(message: _302.ResponseApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_302.ResponseApplySnapshotChunk>): _302.ResponseApplySnapshotChunk;
            fromAmino(object: _302.ResponseApplySnapshotChunkAmino): _302.ResponseApplySnapshotChunk;
            toAmino(message: _302.ResponseApplySnapshotChunk): _302.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _302.ResponseApplySnapshotChunkAminoMsg): _302.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _302.ResponseApplySnapshotChunkProtoMsg): _302.ResponseApplySnapshotChunk;
            toProto(message: _302.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _302.ResponseApplySnapshotChunk): _302.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            encode(message: _302.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ConsensusParams;
            fromJSON(object: any): _302.ConsensusParams;
            toJSON(message: _302.ConsensusParams): unknown;
            fromPartial(object: Partial<_302.ConsensusParams>): _302.ConsensusParams;
            fromAmino(object: _302.ConsensusParamsAmino): _302.ConsensusParams;
            toAmino(message: _302.ConsensusParams): _302.ConsensusParamsAmino;
            fromAminoMsg(object: _302.ConsensusParamsAminoMsg): _302.ConsensusParams;
            fromProtoMsg(message: _302.ConsensusParamsProtoMsg): _302.ConsensusParams;
            toProto(message: _302.ConsensusParams): Uint8Array;
            toProtoMsg(message: _302.ConsensusParams): _302.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _302.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.BlockParams;
            fromJSON(object: any): _302.BlockParams;
            toJSON(message: _302.BlockParams): unknown;
            fromPartial(object: Partial<_302.BlockParams>): _302.BlockParams;
            fromAmino(object: _302.BlockParamsAmino): _302.BlockParams;
            toAmino(message: _302.BlockParams): _302.BlockParamsAmino;
            fromAminoMsg(object: _302.BlockParamsAminoMsg): _302.BlockParams;
            fromProtoMsg(message: _302.BlockParamsProtoMsg): _302.BlockParams;
            toProto(message: _302.BlockParams): Uint8Array;
            toProtoMsg(message: _302.BlockParams): _302.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            encode(message: _302.LastCommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.LastCommitInfo;
            fromJSON(object: any): _302.LastCommitInfo;
            toJSON(message: _302.LastCommitInfo): unknown;
            fromPartial(object: Partial<_302.LastCommitInfo>): _302.LastCommitInfo;
            fromAmino(object: _302.LastCommitInfoAmino): _302.LastCommitInfo;
            toAmino(message: _302.LastCommitInfo): _302.LastCommitInfoAmino;
            fromAminoMsg(object: _302.LastCommitInfoAminoMsg): _302.LastCommitInfo;
            fromProtoMsg(message: _302.LastCommitInfoProtoMsg): _302.LastCommitInfo;
            toProto(message: _302.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _302.LastCommitInfo): _302.LastCommitInfoProtoMsg;
        };
        Event: {
            encode(message: _302.Event, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Event;
            fromJSON(object: any): _302.Event;
            toJSON(message: _302.Event): unknown;
            fromPartial(object: Partial<_302.Event>): _302.Event;
            fromAmino(object: _302.EventAmino): _302.Event;
            toAmino(message: _302.Event): _302.EventAmino;
            fromAminoMsg(object: _302.EventAminoMsg): _302.Event;
            fromProtoMsg(message: _302.EventProtoMsg): _302.Event;
            toProto(message: _302.Event): Uint8Array;
            toProtoMsg(message: _302.Event): _302.EventProtoMsg;
        };
        EventAttribute: {
            encode(message: _302.EventAttribute, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.EventAttribute;
            fromJSON(object: any): _302.EventAttribute;
            toJSON(message: _302.EventAttribute): unknown;
            fromPartial(object: Partial<_302.EventAttribute>): _302.EventAttribute;
            fromAmino(object: _302.EventAttributeAmino): _302.EventAttribute;
            toAmino(message: _302.EventAttribute): _302.EventAttributeAmino;
            fromAminoMsg(object: _302.EventAttributeAminoMsg): _302.EventAttribute;
            fromProtoMsg(message: _302.EventAttributeProtoMsg): _302.EventAttribute;
            toProto(message: _302.EventAttribute): Uint8Array;
            toProtoMsg(message: _302.EventAttribute): _302.EventAttributeProtoMsg;
        };
        TxResult: {
            encode(message: _302.TxResult, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.TxResult;
            fromJSON(object: any): _302.TxResult;
            toJSON(message: _302.TxResult): unknown;
            fromPartial(object: Partial<_302.TxResult>): _302.TxResult;
            fromAmino(object: _302.TxResultAmino): _302.TxResult;
            toAmino(message: _302.TxResult): _302.TxResultAmino;
            fromAminoMsg(object: _302.TxResultAminoMsg): _302.TxResult;
            fromProtoMsg(message: _302.TxResultProtoMsg): _302.TxResult;
            toProto(message: _302.TxResult): Uint8Array;
            toProtoMsg(message: _302.TxResult): _302.TxResultProtoMsg;
        };
        Validator: {
            encode(message: _302.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Validator;
            fromJSON(object: any): _302.Validator;
            toJSON(message: _302.Validator): unknown;
            fromPartial(object: Partial<_302.Validator>): _302.Validator;
            fromAmino(object: _302.ValidatorAmino): _302.Validator;
            toAmino(message: _302.Validator): _302.ValidatorAmino;
            fromAminoMsg(object: _302.ValidatorAminoMsg): _302.Validator;
            fromProtoMsg(message: _302.ValidatorProtoMsg): _302.Validator;
            toProto(message: _302.Validator): Uint8Array;
            toProtoMsg(message: _302.Validator): _302.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            encode(message: _302.ValidatorUpdate, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.ValidatorUpdate;
            fromJSON(object: any): _302.ValidatorUpdate;
            toJSON(message: _302.ValidatorUpdate): unknown;
            fromPartial(object: Partial<_302.ValidatorUpdate>): _302.ValidatorUpdate;
            fromAmino(object: _302.ValidatorUpdateAmino): _302.ValidatorUpdate;
            toAmino(message: _302.ValidatorUpdate): _302.ValidatorUpdateAmino;
            fromAminoMsg(object: _302.ValidatorUpdateAminoMsg): _302.ValidatorUpdate;
            fromProtoMsg(message: _302.ValidatorUpdateProtoMsg): _302.ValidatorUpdate;
            toProto(message: _302.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _302.ValidatorUpdate): _302.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            encode(message: _302.VoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.VoteInfo;
            fromJSON(object: any): _302.VoteInfo;
            toJSON(message: _302.VoteInfo): unknown;
            fromPartial(object: Partial<_302.VoteInfo>): _302.VoteInfo;
            fromAmino(object: _302.VoteInfoAmino): _302.VoteInfo;
            toAmino(message: _302.VoteInfo): _302.VoteInfoAmino;
            fromAminoMsg(object: _302.VoteInfoAminoMsg): _302.VoteInfo;
            fromProtoMsg(message: _302.VoteInfoProtoMsg): _302.VoteInfo;
            toProto(message: _302.VoteInfo): Uint8Array;
            toProtoMsg(message: _302.VoteInfo): _302.VoteInfoProtoMsg;
        };
        Evidence: {
            encode(message: _302.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Evidence;
            fromJSON(object: any): _302.Evidence;
            toJSON(message: _302.Evidence): unknown;
            fromPartial(object: Partial<_302.Evidence>): _302.Evidence;
            fromAmino(object: _302.EvidenceAmino): _302.Evidence;
            toAmino(message: _302.Evidence): _302.EvidenceAmino;
            fromAminoMsg(object: _302.EvidenceAminoMsg): _302.Evidence;
            fromProtoMsg(message: _302.EvidenceProtoMsg): _302.Evidence;
            toProto(message: _302.Evidence): Uint8Array;
            toProtoMsg(message: _302.Evidence): _302.EvidenceProtoMsg;
        };
        Snapshot: {
            encode(message: _302.Snapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Snapshot;
            fromJSON(object: any): _302.Snapshot;
            toJSON(message: _302.Snapshot): unknown;
            fromPartial(object: Partial<_302.Snapshot>): _302.Snapshot;
            fromAmino(object: _302.SnapshotAmino): _302.Snapshot;
            toAmino(message: _302.Snapshot): _302.SnapshotAmino;
            fromAminoMsg(object: _302.SnapshotAminoMsg): _302.Snapshot;
            fromProtoMsg(message: _302.SnapshotProtoMsg): _302.Snapshot;
            toProto(message: _302.Snapshot): Uint8Array;
            toProtoMsg(message: _302.Snapshot): _302.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            encode(message: _304.Proof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _304.Proof;
            fromJSON(object: any): _304.Proof;
            toJSON(message: _304.Proof): unknown;
            fromPartial(object: Partial<_304.Proof>): _304.Proof;
            fromAmino(object: _304.ProofAmino): _304.Proof;
            toAmino(message: _304.Proof): _304.ProofAmino;
            fromAminoMsg(object: _304.ProofAminoMsg): _304.Proof;
            fromProtoMsg(message: _304.ProofProtoMsg): _304.Proof;
            toProto(message: _304.Proof): Uint8Array;
            toProtoMsg(message: _304.Proof): _304.ProofProtoMsg;
        };
        ValueOp: {
            encode(message: _304.ValueOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _304.ValueOp;
            fromJSON(object: any): _304.ValueOp;
            toJSON(message: _304.ValueOp): unknown;
            fromPartial(object: Partial<_304.ValueOp>): _304.ValueOp;
            fromAmino(object: _304.ValueOpAmino): _304.ValueOp;
            toAmino(message: _304.ValueOp): _304.ValueOpAmino;
            fromAminoMsg(object: _304.ValueOpAminoMsg): _304.ValueOp;
            fromProtoMsg(message: _304.ValueOpProtoMsg): _304.ValueOp;
            toProto(message: _304.ValueOp): Uint8Array;
            toProtoMsg(message: _304.ValueOp): _304.ValueOpProtoMsg;
        };
        DominoOp: {
            encode(message: _304.DominoOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _304.DominoOp;
            fromJSON(object: any): _304.DominoOp;
            toJSON(message: _304.DominoOp): unknown;
            fromPartial(object: Partial<_304.DominoOp>): _304.DominoOp;
            fromAmino(object: _304.DominoOpAmino): _304.DominoOp;
            toAmino(message: _304.DominoOp): _304.DominoOpAmino;
            fromAminoMsg(object: _304.DominoOpAminoMsg): _304.DominoOp;
            fromProtoMsg(message: _304.DominoOpProtoMsg): _304.DominoOp;
            toProto(message: _304.DominoOp): Uint8Array;
            toProtoMsg(message: _304.DominoOp): _304.DominoOpProtoMsg;
        };
        ProofOp: {
            encode(message: _304.ProofOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _304.ProofOp;
            fromJSON(object: any): _304.ProofOp;
            toJSON(message: _304.ProofOp): unknown;
            fromPartial(object: Partial<_304.ProofOp>): _304.ProofOp;
            fromAmino(object: _304.ProofOpAmino): _304.ProofOp;
            toAmino(message: _304.ProofOp): _304.ProofOpAmino;
            fromAminoMsg(object: _304.ProofOpAminoMsg): _304.ProofOp;
            fromProtoMsg(message: _304.ProofOpProtoMsg): _304.ProofOp;
            toProto(message: _304.ProofOp): Uint8Array;
            toProtoMsg(message: _304.ProofOp): _304.ProofOpProtoMsg;
        };
        ProofOps: {
            encode(message: _304.ProofOps, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _304.ProofOps;
            fromJSON(object: any): _304.ProofOps;
            toJSON(message: _304.ProofOps): unknown;
            fromPartial(object: Partial<_304.ProofOps>): _304.ProofOps;
            fromAmino(object: _304.ProofOpsAmino): _304.ProofOps;
            toAmino(message: _304.ProofOps): _304.ProofOpsAmino;
            fromAminoMsg(object: _304.ProofOpsAminoMsg): _304.ProofOps;
            fromProtoMsg(message: _304.ProofOpsProtoMsg): _304.ProofOps;
            toProto(message: _304.ProofOps): Uint8Array;
            toProtoMsg(message: _304.ProofOps): _304.ProofOpsProtoMsg;
        };
        PublicKey: {
            encode(message: _303.PublicKey, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _303.PublicKey;
            fromJSON(object: any): _303.PublicKey;
            toJSON(message: _303.PublicKey): unknown;
            fromPartial(object: Partial<_303.PublicKey>): _303.PublicKey;
            fromAmino(object: _303.PublicKeyAmino): _303.PublicKey;
            toAmino(message: _303.PublicKey): _303.PublicKeyAmino;
            fromAminoMsg(object: _303.PublicKeyAminoMsg): _303.PublicKey;
            fromProtoMsg(message: _303.PublicKeyProtoMsg): _303.PublicKey;
            toProto(message: _303.PublicKey): Uint8Array;
            toProtoMsg(message: _303.PublicKey): _303.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                encode(message: _305.BitArray, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
                decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _305.BitArray;
                fromJSON(object: any): _305.BitArray;
                toJSON(message: _305.BitArray): unknown;
                fromPartial(object: Partial<_305.BitArray>): _305.BitArray;
                fromAmino(object: _305.BitArrayAmino): _305.BitArray;
                toAmino(message: _305.BitArray): _305.BitArrayAmino;
                fromAminoMsg(object: _305.BitArrayAminoMsg): _305.BitArray;
                fromProtoMsg(message: _305.BitArrayProtoMsg): _305.BitArray;
                toProto(message: _305.BitArray): Uint8Array;
                toProtoMsg(message: _305.BitArray): _305.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        ProtocolVersion: {
            encode(message: _306.ProtocolVersion, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _306.ProtocolVersion;
            fromJSON(object: any): _306.ProtocolVersion;
            toJSON(message: _306.ProtocolVersion): unknown;
            fromPartial(object: Partial<_306.ProtocolVersion>): _306.ProtocolVersion;
            fromAmino(object: _306.ProtocolVersionAmino): _306.ProtocolVersion;
            toAmino(message: _306.ProtocolVersion): _306.ProtocolVersionAmino;
            fromAminoMsg(object: _306.ProtocolVersionAminoMsg): _306.ProtocolVersion;
            fromProtoMsg(message: _306.ProtocolVersionProtoMsg): _306.ProtocolVersion;
            toProto(message: _306.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _306.ProtocolVersion): _306.ProtocolVersionProtoMsg;
        };
        NodeInfo: {
            encode(message: _306.NodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _306.NodeInfo;
            fromJSON(object: any): _306.NodeInfo;
            toJSON(message: _306.NodeInfo): unknown;
            fromPartial(object: Partial<_306.NodeInfo>): _306.NodeInfo;
            fromAmino(object: _306.NodeInfoAmino): _306.NodeInfo;
            toAmino(message: _306.NodeInfo): _306.NodeInfoAmino;
            fromAminoMsg(object: _306.NodeInfoAminoMsg): _306.NodeInfo;
            fromProtoMsg(message: _306.NodeInfoProtoMsg): _306.NodeInfo;
            toProto(message: _306.NodeInfo): Uint8Array;
            toProtoMsg(message: _306.NodeInfo): _306.NodeInfoProtoMsg;
        };
        NodeInfoOther: {
            encode(message: _306.NodeInfoOther, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _306.NodeInfoOther;
            fromJSON(object: any): _306.NodeInfoOther;
            toJSON(message: _306.NodeInfoOther): unknown;
            fromPartial(object: Partial<_306.NodeInfoOther>): _306.NodeInfoOther;
            fromAmino(object: _306.NodeInfoOtherAmino): _306.NodeInfoOther;
            toAmino(message: _306.NodeInfoOther): _306.NodeInfoOtherAmino;
            fromAminoMsg(object: _306.NodeInfoOtherAminoMsg): _306.NodeInfoOther;
            fromProtoMsg(message: _306.NodeInfoOtherProtoMsg): _306.NodeInfoOther;
            toProto(message: _306.NodeInfoOther): Uint8Array;
            toProtoMsg(message: _306.NodeInfoOther): _306.NodeInfoOtherProtoMsg;
        };
        PeerInfo: {
            encode(message: _306.PeerInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _306.PeerInfo;
            fromJSON(object: any): _306.PeerInfo;
            toJSON(message: _306.PeerInfo): unknown;
            fromPartial(object: Partial<_306.PeerInfo>): _306.PeerInfo;
            fromAmino(object: _306.PeerInfoAmino): _306.PeerInfo;
            toAmino(message: _306.PeerInfo): _306.PeerInfoAmino;
            fromAminoMsg(object: _306.PeerInfoAminoMsg): _306.PeerInfo;
            fromProtoMsg(message: _306.PeerInfoProtoMsg): _306.PeerInfo;
            toProto(message: _306.PeerInfo): Uint8Array;
            toProtoMsg(message: _306.PeerInfo): _306.PeerInfoProtoMsg;
        };
        PeerAddressInfo: {
            encode(message: _306.PeerAddressInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _306.PeerAddressInfo;
            fromJSON(object: any): _306.PeerAddressInfo;
            toJSON(message: _306.PeerAddressInfo): unknown;
            fromPartial(object: Partial<_306.PeerAddressInfo>): _306.PeerAddressInfo;
            fromAmino(object: _306.PeerAddressInfoAmino): _306.PeerAddressInfo;
            toAmino(message: _306.PeerAddressInfo): _306.PeerAddressInfoAmino;
            fromAminoMsg(object: _306.PeerAddressInfoAminoMsg): _306.PeerAddressInfo;
            fromProtoMsg(message: _306.PeerAddressInfoProtoMsg): _306.PeerAddressInfo;
            toProto(message: _306.PeerAddressInfo): Uint8Array;
            toProtoMsg(message: _306.PeerAddressInfo): _306.PeerAddressInfoProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            encode(message: _311.ValidatorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _311.ValidatorSet;
            fromJSON(object: any): _311.ValidatorSet;
            toJSON(message: _311.ValidatorSet): unknown;
            fromPartial(object: Partial<_311.ValidatorSet>): _311.ValidatorSet;
            fromAmino(object: _311.ValidatorSetAmino): _311.ValidatorSet;
            toAmino(message: _311.ValidatorSet): _311.ValidatorSetAmino;
            fromAminoMsg(object: _311.ValidatorSetAminoMsg): _311.ValidatorSet;
            fromProtoMsg(message: _311.ValidatorSetProtoMsg): _311.ValidatorSet;
            toProto(message: _311.ValidatorSet): Uint8Array;
            toProtoMsg(message: _311.ValidatorSet): _311.ValidatorSetProtoMsg;
        };
        Validator: {
            encode(message: _311.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _311.Validator;
            fromJSON(object: any): _311.Validator;
            toJSON(message: _311.Validator): unknown;
            fromPartial(object: Partial<_311.Validator>): _311.Validator;
            fromAmino(object: _311.ValidatorAmino): _311.Validator;
            toAmino(message: _311.Validator): _311.ValidatorAmino;
            fromAminoMsg(object: _311.ValidatorAminoMsg): _311.Validator;
            fromProtoMsg(message: _311.ValidatorProtoMsg): _311.Validator;
            toProto(message: _311.Validator): Uint8Array;
            toProtoMsg(message: _311.Validator): _311.ValidatorProtoMsg;
        };
        SimpleValidator: {
            encode(message: _311.SimpleValidator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _311.SimpleValidator;
            fromJSON(object: any): _311.SimpleValidator;
            toJSON(message: _311.SimpleValidator): unknown;
            fromPartial(object: Partial<_311.SimpleValidator>): _311.SimpleValidator;
            fromAmino(object: _311.SimpleValidatorAmino): _311.SimpleValidator;
            toAmino(message: _311.SimpleValidator): _311.SimpleValidatorAmino;
            fromAminoMsg(object: _311.SimpleValidatorAminoMsg): _311.SimpleValidator;
            fromProtoMsg(message: _311.SimpleValidatorProtoMsg): _311.SimpleValidator;
            toProto(message: _311.SimpleValidator): Uint8Array;
            toProtoMsg(message: _311.SimpleValidator): _311.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _310.BlockIDFlag;
        blockIDFlagToJSON(object: _310.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _310.SignedMsgType;
        signedMsgTypeToJSON(object: _310.SignedMsgType): string;
        BlockIDFlag: typeof _310.BlockIDFlag;
        BlockIDFlagSDKType: typeof _310.BlockIDFlag;
        BlockIDFlagAmino: typeof _310.BlockIDFlag;
        SignedMsgType: typeof _310.SignedMsgType;
        SignedMsgTypeSDKType: typeof _310.SignedMsgType;
        SignedMsgTypeAmino: typeof _310.SignedMsgType;
        PartSetHeader: {
            encode(message: _310.PartSetHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.PartSetHeader;
            fromJSON(object: any): _310.PartSetHeader;
            toJSON(message: _310.PartSetHeader): unknown;
            fromPartial(object: Partial<_310.PartSetHeader>): _310.PartSetHeader;
            fromAmino(object: _310.PartSetHeaderAmino): _310.PartSetHeader;
            toAmino(message: _310.PartSetHeader): _310.PartSetHeaderAmino;
            fromAminoMsg(object: _310.PartSetHeaderAminoMsg): _310.PartSetHeader;
            fromProtoMsg(message: _310.PartSetHeaderProtoMsg): _310.PartSetHeader;
            toProto(message: _310.PartSetHeader): Uint8Array;
            toProtoMsg(message: _310.PartSetHeader): _310.PartSetHeaderProtoMsg;
        };
        Part: {
            encode(message: _310.Part, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.Part;
            fromJSON(object: any): _310.Part;
            toJSON(message: _310.Part): unknown;
            fromPartial(object: Partial<_310.Part>): _310.Part;
            fromAmino(object: _310.PartAmino): _310.Part;
            toAmino(message: _310.Part): _310.PartAmino;
            fromAminoMsg(object: _310.PartAminoMsg): _310.Part;
            fromProtoMsg(message: _310.PartProtoMsg): _310.Part;
            toProto(message: _310.Part): Uint8Array;
            toProtoMsg(message: _310.Part): _310.PartProtoMsg;
        };
        BlockID: {
            encode(message: _310.BlockID, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.BlockID;
            fromJSON(object: any): _310.BlockID;
            toJSON(message: _310.BlockID): unknown;
            fromPartial(object: Partial<_310.BlockID>): _310.BlockID;
            fromAmino(object: _310.BlockIDAmino): _310.BlockID;
            toAmino(message: _310.BlockID): _310.BlockIDAmino;
            fromAminoMsg(object: _310.BlockIDAminoMsg): _310.BlockID;
            fromProtoMsg(message: _310.BlockIDProtoMsg): _310.BlockID;
            toProto(message: _310.BlockID): Uint8Array;
            toProtoMsg(message: _310.BlockID): _310.BlockIDProtoMsg;
        };
        Header: {
            encode(message: _310.Header, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.Header;
            fromJSON(object: any): _310.Header;
            toJSON(message: _310.Header): unknown;
            fromPartial(object: Partial<_310.Header>): _310.Header;
            fromAmino(object: _310.HeaderAmino): _310.Header;
            toAmino(message: _310.Header): _310.HeaderAmino;
            fromAminoMsg(object: _310.HeaderAminoMsg): _310.Header;
            fromProtoMsg(message: _310.HeaderProtoMsg): _310.Header;
            toProto(message: _310.Header): Uint8Array;
            toProtoMsg(message: _310.Header): _310.HeaderProtoMsg;
        };
        Data: {
            encode(message: _310.Data, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.Data;
            fromJSON(object: any): _310.Data;
            toJSON(message: _310.Data): unknown;
            fromPartial(object: Partial<_310.Data>): _310.Data;
            fromAmino(object: _310.DataAmino): _310.Data;
            toAmino(message: _310.Data): _310.DataAmino;
            fromAminoMsg(object: _310.DataAminoMsg): _310.Data;
            fromProtoMsg(message: _310.DataProtoMsg): _310.Data;
            toProto(message: _310.Data): Uint8Array;
            toProtoMsg(message: _310.Data): _310.DataProtoMsg;
        };
        Vote: {
            encode(message: _310.Vote, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.Vote;
            fromJSON(object: any): _310.Vote;
            toJSON(message: _310.Vote): unknown;
            fromPartial(object: Partial<_310.Vote>): _310.Vote;
            fromAmino(object: _310.VoteAmino): _310.Vote;
            toAmino(message: _310.Vote): _310.VoteAmino;
            fromAminoMsg(object: _310.VoteAminoMsg): _310.Vote;
            fromProtoMsg(message: _310.VoteProtoMsg): _310.Vote;
            toProto(message: _310.Vote): Uint8Array;
            toProtoMsg(message: _310.Vote): _310.VoteProtoMsg;
        };
        Commit: {
            encode(message: _310.Commit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.Commit;
            fromJSON(object: any): _310.Commit;
            toJSON(message: _310.Commit): unknown;
            fromPartial(object: Partial<_310.Commit>): _310.Commit;
            fromAmino(object: _310.CommitAmino): _310.Commit;
            toAmino(message: _310.Commit): _310.CommitAmino;
            fromAminoMsg(object: _310.CommitAminoMsg): _310.Commit;
            fromProtoMsg(message: _310.CommitProtoMsg): _310.Commit;
            toProto(message: _310.Commit): Uint8Array;
            toProtoMsg(message: _310.Commit): _310.CommitProtoMsg;
        };
        CommitSig: {
            encode(message: _310.CommitSig, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.CommitSig;
            fromJSON(object: any): _310.CommitSig;
            toJSON(message: _310.CommitSig): unknown;
            fromPartial(object: Partial<_310.CommitSig>): _310.CommitSig;
            fromAmino(object: _310.CommitSigAmino): _310.CommitSig;
            toAmino(message: _310.CommitSig): _310.CommitSigAmino;
            fromAminoMsg(object: _310.CommitSigAminoMsg): _310.CommitSig;
            fromProtoMsg(message: _310.CommitSigProtoMsg): _310.CommitSig;
            toProto(message: _310.CommitSig): Uint8Array;
            toProtoMsg(message: _310.CommitSig): _310.CommitSigProtoMsg;
        };
        Proposal: {
            encode(message: _310.Proposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.Proposal;
            fromJSON(object: any): _310.Proposal;
            toJSON(message: _310.Proposal): unknown;
            fromPartial(object: Partial<_310.Proposal>): _310.Proposal;
            fromAmino(object: _310.ProposalAmino): _310.Proposal;
            toAmino(message: _310.Proposal): _310.ProposalAmino;
            fromAminoMsg(object: _310.ProposalAminoMsg): _310.Proposal;
            fromProtoMsg(message: _310.ProposalProtoMsg): _310.Proposal;
            toProto(message: _310.Proposal): Uint8Array;
            toProtoMsg(message: _310.Proposal): _310.ProposalProtoMsg;
        };
        SignedHeader: {
            encode(message: _310.SignedHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.SignedHeader;
            fromJSON(object: any): _310.SignedHeader;
            toJSON(message: _310.SignedHeader): unknown;
            fromPartial(object: Partial<_310.SignedHeader>): _310.SignedHeader;
            fromAmino(object: _310.SignedHeaderAmino): _310.SignedHeader;
            toAmino(message: _310.SignedHeader): _310.SignedHeaderAmino;
            fromAminoMsg(object: _310.SignedHeaderAminoMsg): _310.SignedHeader;
            fromProtoMsg(message: _310.SignedHeaderProtoMsg): _310.SignedHeader;
            toProto(message: _310.SignedHeader): Uint8Array;
            toProtoMsg(message: _310.SignedHeader): _310.SignedHeaderProtoMsg;
        };
        LightBlock: {
            encode(message: _310.LightBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.LightBlock;
            fromJSON(object: any): _310.LightBlock;
            toJSON(message: _310.LightBlock): unknown;
            fromPartial(object: Partial<_310.LightBlock>): _310.LightBlock;
            fromAmino(object: _310.LightBlockAmino): _310.LightBlock;
            toAmino(message: _310.LightBlock): _310.LightBlockAmino;
            fromAminoMsg(object: _310.LightBlockAminoMsg): _310.LightBlock;
            fromProtoMsg(message: _310.LightBlockProtoMsg): _310.LightBlock;
            toProto(message: _310.LightBlock): Uint8Array;
            toProtoMsg(message: _310.LightBlock): _310.LightBlockProtoMsg;
        };
        BlockMeta: {
            encode(message: _310.BlockMeta, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.BlockMeta;
            fromJSON(object: any): _310.BlockMeta;
            toJSON(message: _310.BlockMeta): unknown;
            fromPartial(object: Partial<_310.BlockMeta>): _310.BlockMeta;
            fromAmino(object: _310.BlockMetaAmino): _310.BlockMeta;
            toAmino(message: _310.BlockMeta): _310.BlockMetaAmino;
            fromAminoMsg(object: _310.BlockMetaAminoMsg): _310.BlockMeta;
            fromProtoMsg(message: _310.BlockMetaProtoMsg): _310.BlockMeta;
            toProto(message: _310.BlockMeta): Uint8Array;
            toProtoMsg(message: _310.BlockMeta): _310.BlockMetaProtoMsg;
        };
        TxProof: {
            encode(message: _310.TxProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _310.TxProof;
            fromJSON(object: any): _310.TxProof;
            toJSON(message: _310.TxProof): unknown;
            fromPartial(object: Partial<_310.TxProof>): _310.TxProof;
            fromAmino(object: _310.TxProofAmino): _310.TxProof;
            toAmino(message: _310.TxProof): _310.TxProofAmino;
            fromAminoMsg(object: _310.TxProofAminoMsg): _310.TxProof;
            fromProtoMsg(message: _310.TxProofProtoMsg): _310.TxProof;
            toProto(message: _310.TxProof): Uint8Array;
            toProtoMsg(message: _310.TxProof): _310.TxProofProtoMsg;
        };
        ConsensusParams: {
            encode(message: _309.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _309.ConsensusParams;
            fromJSON(object: any): _309.ConsensusParams;
            toJSON(message: _309.ConsensusParams): unknown;
            fromPartial(object: Partial<_309.ConsensusParams>): _309.ConsensusParams;
            fromAmino(object: _309.ConsensusParamsAmino): _309.ConsensusParams;
            toAmino(message: _309.ConsensusParams): _309.ConsensusParamsAmino;
            fromAminoMsg(object: _309.ConsensusParamsAminoMsg): _309.ConsensusParams;
            fromProtoMsg(message: _309.ConsensusParamsProtoMsg): _309.ConsensusParams;
            toProto(message: _309.ConsensusParams): Uint8Array;
            toProtoMsg(message: _309.ConsensusParams): _309.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _309.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _309.BlockParams;
            fromJSON(object: any): _309.BlockParams;
            toJSON(message: _309.BlockParams): unknown;
            fromPartial(object: Partial<_309.BlockParams>): _309.BlockParams;
            fromAmino(object: _309.BlockParamsAmino): _309.BlockParams;
            toAmino(message: _309.BlockParams): _309.BlockParamsAmino;
            fromAminoMsg(object: _309.BlockParamsAminoMsg): _309.BlockParams;
            fromProtoMsg(message: _309.BlockParamsProtoMsg): _309.BlockParams;
            toProto(message: _309.BlockParams): Uint8Array;
            toProtoMsg(message: _309.BlockParams): _309.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            encode(message: _309.EvidenceParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _309.EvidenceParams;
            fromJSON(object: any): _309.EvidenceParams;
            toJSON(message: _309.EvidenceParams): unknown;
            fromPartial(object: Partial<_309.EvidenceParams>): _309.EvidenceParams;
            fromAmino(object: _309.EvidenceParamsAmino): _309.EvidenceParams;
            toAmino(message: _309.EvidenceParams): _309.EvidenceParamsAmino;
            fromAminoMsg(object: _309.EvidenceParamsAminoMsg): _309.EvidenceParams;
            fromProtoMsg(message: _309.EvidenceParamsProtoMsg): _309.EvidenceParams;
            toProto(message: _309.EvidenceParams): Uint8Array;
            toProtoMsg(message: _309.EvidenceParams): _309.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            encode(message: _309.ValidatorParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _309.ValidatorParams;
            fromJSON(object: any): _309.ValidatorParams;
            toJSON(message: _309.ValidatorParams): unknown;
            fromPartial(object: Partial<_309.ValidatorParams>): _309.ValidatorParams;
            fromAmino(object: _309.ValidatorParamsAmino): _309.ValidatorParams;
            toAmino(message: _309.ValidatorParams): _309.ValidatorParamsAmino;
            fromAminoMsg(object: _309.ValidatorParamsAminoMsg): _309.ValidatorParams;
            fromProtoMsg(message: _309.ValidatorParamsProtoMsg): _309.ValidatorParams;
            toProto(message: _309.ValidatorParams): Uint8Array;
            toProtoMsg(message: _309.ValidatorParams): _309.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            encode(message: _309.VersionParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _309.VersionParams;
            fromJSON(object: any): _309.VersionParams;
            toJSON(message: _309.VersionParams): unknown;
            fromPartial(object: Partial<_309.VersionParams>): _309.VersionParams;
            fromAmino(object: _309.VersionParamsAmino): _309.VersionParams;
            toAmino(message: _309.VersionParams): _309.VersionParamsAmino;
            fromAminoMsg(object: _309.VersionParamsAminoMsg): _309.VersionParams;
            fromProtoMsg(message: _309.VersionParamsProtoMsg): _309.VersionParams;
            toProto(message: _309.VersionParams): Uint8Array;
            toProtoMsg(message: _309.VersionParams): _309.VersionParamsProtoMsg;
        };
        HashedParams: {
            encode(message: _309.HashedParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _309.HashedParams;
            fromJSON(object: any): _309.HashedParams;
            toJSON(message: _309.HashedParams): unknown;
            fromPartial(object: Partial<_309.HashedParams>): _309.HashedParams;
            fromAmino(object: _309.HashedParamsAmino): _309.HashedParams;
            toAmino(message: _309.HashedParams): _309.HashedParamsAmino;
            fromAminoMsg(object: _309.HashedParamsAminoMsg): _309.HashedParams;
            fromProtoMsg(message: _309.HashedParamsProtoMsg): _309.HashedParams;
            toProto(message: _309.HashedParams): Uint8Array;
            toProtoMsg(message: _309.HashedParams): _309.HashedParamsProtoMsg;
        };
        Evidence: {
            encode(message: _308.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _308.Evidence;
            fromJSON(object: any): _308.Evidence;
            toJSON(message: _308.Evidence): unknown;
            fromPartial(object: Partial<_308.Evidence>): _308.Evidence;
            fromAmino(object: _308.EvidenceAmino): _308.Evidence;
            toAmino(message: _308.Evidence): _308.EvidenceAmino;
            fromAminoMsg(object: _308.EvidenceAminoMsg): _308.Evidence;
            fromProtoMsg(message: _308.EvidenceProtoMsg): _308.Evidence;
            toProto(message: _308.Evidence): Uint8Array;
            toProtoMsg(message: _308.Evidence): _308.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            encode(message: _308.DuplicateVoteEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _308.DuplicateVoteEvidence;
            fromJSON(object: any): _308.DuplicateVoteEvidence;
            toJSON(message: _308.DuplicateVoteEvidence): unknown;
            fromPartial(object: Partial<_308.DuplicateVoteEvidence>): _308.DuplicateVoteEvidence;
            fromAmino(object: _308.DuplicateVoteEvidenceAmino): _308.DuplicateVoteEvidence;
            toAmino(message: _308.DuplicateVoteEvidence): _308.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _308.DuplicateVoteEvidenceAminoMsg): _308.DuplicateVoteEvidence;
            fromProtoMsg(message: _308.DuplicateVoteEvidenceProtoMsg): _308.DuplicateVoteEvidence;
            toProto(message: _308.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _308.DuplicateVoteEvidence): _308.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            encode(message: _308.LightClientAttackEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _308.LightClientAttackEvidence;
            fromJSON(object: any): _308.LightClientAttackEvidence;
            toJSON(message: _308.LightClientAttackEvidence): unknown;
            fromPartial(object: Partial<_308.LightClientAttackEvidence>): _308.LightClientAttackEvidence;
            fromAmino(object: _308.LightClientAttackEvidenceAmino): _308.LightClientAttackEvidence;
            toAmino(message: _308.LightClientAttackEvidence): _308.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _308.LightClientAttackEvidenceAminoMsg): _308.LightClientAttackEvidence;
            fromProtoMsg(message: _308.LightClientAttackEvidenceProtoMsg): _308.LightClientAttackEvidence;
            toProto(message: _308.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _308.LightClientAttackEvidence): _308.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            encode(message: _308.EvidenceList, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _308.EvidenceList;
            fromJSON(object: any): _308.EvidenceList;
            toJSON(message: _308.EvidenceList): unknown;
            fromPartial(object: Partial<_308.EvidenceList>): _308.EvidenceList;
            fromAmino(object: _308.EvidenceListAmino): _308.EvidenceList;
            toAmino(message: _308.EvidenceList): _308.EvidenceListAmino;
            fromAminoMsg(object: _308.EvidenceListAminoMsg): _308.EvidenceList;
            fromProtoMsg(message: _308.EvidenceListProtoMsg): _308.EvidenceList;
            toProto(message: _308.EvidenceList): Uint8Array;
            toProtoMsg(message: _308.EvidenceList): _308.EvidenceListProtoMsg;
        };
        Block: {
            encode(message: _307.Block, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _307.Block;
            fromJSON(object: any): _307.Block;
            toJSON(message: _307.Block): unknown;
            fromPartial(object: Partial<_307.Block>): _307.Block;
            fromAmino(object: _307.BlockAmino): _307.Block;
            toAmino(message: _307.Block): _307.BlockAmino;
            fromAminoMsg(object: _307.BlockAminoMsg): _307.Block;
            fromProtoMsg(message: _307.BlockProtoMsg): _307.Block;
            toProto(message: _307.Block): Uint8Array;
            toProtoMsg(message: _307.Block): _307.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            encode(message: _312.App, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _312.App;
            fromJSON(object: any): _312.App;
            toJSON(message: _312.App): unknown;
            fromPartial(object: Partial<_312.App>): _312.App;
            fromAmino(object: _312.AppAmino): _312.App;
            toAmino(message: _312.App): _312.AppAmino;
            fromAminoMsg(object: _312.AppAminoMsg): _312.App;
            fromProtoMsg(message: _312.AppProtoMsg): _312.App;
            toProto(message: _312.App): Uint8Array;
            toProtoMsg(message: _312.App): _312.AppProtoMsg;
        };
        Consensus: {
            encode(message: _312.Consensus, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _312.Consensus;
            fromJSON(object: any): _312.Consensus;
            toJSON(message: _312.Consensus): unknown;
            fromPartial(object: Partial<_312.Consensus>): _312.Consensus;
            fromAmino(object: _312.ConsensusAmino): _312.Consensus;
            toAmino(message: _312.Consensus): _312.ConsensusAmino;
            fromAminoMsg(object: _312.ConsensusAminoMsg): _312.Consensus;
            fromProtoMsg(message: _312.ConsensusProtoMsg): _312.Consensus;
            toProto(message: _312.Consensus): Uint8Array;
            toProtoMsg(message: _312.Consensus): _312.ConsensusProtoMsg;
        };
    };
}
