import * as _294 from "./abci/types";
import * as _295 from "./crypto/keys";
import * as _296 from "./crypto/proof";
import * as _297 from "./libs/bits/types";
import * as _298 from "./p2p/types";
import * as _299 from "./types/block";
import * as _300 from "./types/evidence";
import * as _301 from "./types/params";
import * as _302 from "./types/types";
import * as _303 from "./types/validator";
import * as _304 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _294.CheckTxType;
        checkTxTypeToJSON(object: _294.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _294.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _294.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _294.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _294.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _294.EvidenceType;
        evidenceTypeToJSON(object: _294.EvidenceType): string;
        CheckTxType: typeof _294.CheckTxType;
        CheckTxTypeSDKType: typeof _294.CheckTxType;
        CheckTxTypeAmino: typeof _294.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _294.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _294.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _294.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _294.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _294.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _294.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _294.EvidenceType;
        EvidenceTypeSDKType: typeof _294.EvidenceType;
        EvidenceTypeAmino: typeof _294.EvidenceType;
        Request: {
            encode(message: _294.Request, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.Request;
            fromJSON(object: any): _294.Request;
            toJSON(message: _294.Request): unknown;
            fromPartial(object: Partial<_294.Request>): _294.Request;
            fromAmino(object: _294.RequestAmino): _294.Request;
            toAmino(message: _294.Request): _294.RequestAmino;
            fromAminoMsg(object: _294.RequestAminoMsg): _294.Request;
            fromProtoMsg(message: _294.RequestProtoMsg): _294.Request;
            toProto(message: _294.Request): Uint8Array;
            toProtoMsg(message: _294.Request): _294.RequestProtoMsg;
        };
        RequestEcho: {
            encode(message: _294.RequestEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestEcho;
            fromJSON(object: any): _294.RequestEcho;
            toJSON(message: _294.RequestEcho): unknown;
            fromPartial(object: Partial<_294.RequestEcho>): _294.RequestEcho;
            fromAmino(object: _294.RequestEchoAmino): _294.RequestEcho;
            toAmino(message: _294.RequestEcho): _294.RequestEchoAmino;
            fromAminoMsg(object: _294.RequestEchoAminoMsg): _294.RequestEcho;
            fromProtoMsg(message: _294.RequestEchoProtoMsg): _294.RequestEcho;
            toProto(message: _294.RequestEcho): Uint8Array;
            toProtoMsg(message: _294.RequestEcho): _294.RequestEchoProtoMsg;
        };
        RequestFlush: {
            encode(_: _294.RequestFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestFlush;
            fromJSON(_: any): _294.RequestFlush;
            toJSON(_: _294.RequestFlush): unknown;
            fromPartial(_: Partial<_294.RequestFlush>): _294.RequestFlush;
            fromAmino(_: _294.RequestFlushAmino): _294.RequestFlush;
            toAmino(_: _294.RequestFlush): _294.RequestFlushAmino;
            fromAminoMsg(object: _294.RequestFlushAminoMsg): _294.RequestFlush;
            fromProtoMsg(message: _294.RequestFlushProtoMsg): _294.RequestFlush;
            toProto(message: _294.RequestFlush): Uint8Array;
            toProtoMsg(message: _294.RequestFlush): _294.RequestFlushProtoMsg;
        };
        RequestInfo: {
            encode(message: _294.RequestInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestInfo;
            fromJSON(object: any): _294.RequestInfo;
            toJSON(message: _294.RequestInfo): unknown;
            fromPartial(object: Partial<_294.RequestInfo>): _294.RequestInfo;
            fromAmino(object: _294.RequestInfoAmino): _294.RequestInfo;
            toAmino(message: _294.RequestInfo): _294.RequestInfoAmino;
            fromAminoMsg(object: _294.RequestInfoAminoMsg): _294.RequestInfo;
            fromProtoMsg(message: _294.RequestInfoProtoMsg): _294.RequestInfo;
            toProto(message: _294.RequestInfo): Uint8Array;
            toProtoMsg(message: _294.RequestInfo): _294.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            encode(message: _294.RequestSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestSetOption;
            fromJSON(object: any): _294.RequestSetOption;
            toJSON(message: _294.RequestSetOption): unknown;
            fromPartial(object: Partial<_294.RequestSetOption>): _294.RequestSetOption;
            fromAmino(object: _294.RequestSetOptionAmino): _294.RequestSetOption;
            toAmino(message: _294.RequestSetOption): _294.RequestSetOptionAmino;
            fromAminoMsg(object: _294.RequestSetOptionAminoMsg): _294.RequestSetOption;
            fromProtoMsg(message: _294.RequestSetOptionProtoMsg): _294.RequestSetOption;
            toProto(message: _294.RequestSetOption): Uint8Array;
            toProtoMsg(message: _294.RequestSetOption): _294.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            encode(message: _294.RequestInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestInitChain;
            fromJSON(object: any): _294.RequestInitChain;
            toJSON(message: _294.RequestInitChain): unknown;
            fromPartial(object: Partial<_294.RequestInitChain>): _294.RequestInitChain;
            fromAmino(object: _294.RequestInitChainAmino): _294.RequestInitChain;
            toAmino(message: _294.RequestInitChain): _294.RequestInitChainAmino;
            fromAminoMsg(object: _294.RequestInitChainAminoMsg): _294.RequestInitChain;
            fromProtoMsg(message: _294.RequestInitChainProtoMsg): _294.RequestInitChain;
            toProto(message: _294.RequestInitChain): Uint8Array;
            toProtoMsg(message: _294.RequestInitChain): _294.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            encode(message: _294.RequestQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestQuery;
            fromJSON(object: any): _294.RequestQuery;
            toJSON(message: _294.RequestQuery): unknown;
            fromPartial(object: Partial<_294.RequestQuery>): _294.RequestQuery;
            fromAmino(object: _294.RequestQueryAmino): _294.RequestQuery;
            toAmino(message: _294.RequestQuery): _294.RequestQueryAmino;
            fromAminoMsg(object: _294.RequestQueryAminoMsg): _294.RequestQuery;
            fromProtoMsg(message: _294.RequestQueryProtoMsg): _294.RequestQuery;
            toProto(message: _294.RequestQuery): Uint8Array;
            toProtoMsg(message: _294.RequestQuery): _294.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            encode(message: _294.RequestBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestBeginBlock;
            fromJSON(object: any): _294.RequestBeginBlock;
            toJSON(message: _294.RequestBeginBlock): unknown;
            fromPartial(object: Partial<_294.RequestBeginBlock>): _294.RequestBeginBlock;
            fromAmino(object: _294.RequestBeginBlockAmino): _294.RequestBeginBlock;
            toAmino(message: _294.RequestBeginBlock): _294.RequestBeginBlockAmino;
            fromAminoMsg(object: _294.RequestBeginBlockAminoMsg): _294.RequestBeginBlock;
            fromProtoMsg(message: _294.RequestBeginBlockProtoMsg): _294.RequestBeginBlock;
            toProto(message: _294.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _294.RequestBeginBlock): _294.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            encode(message: _294.RequestCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestCheckTx;
            fromJSON(object: any): _294.RequestCheckTx;
            toJSON(message: _294.RequestCheckTx): unknown;
            fromPartial(object: Partial<_294.RequestCheckTx>): _294.RequestCheckTx;
            fromAmino(object: _294.RequestCheckTxAmino): _294.RequestCheckTx;
            toAmino(message: _294.RequestCheckTx): _294.RequestCheckTxAmino;
            fromAminoMsg(object: _294.RequestCheckTxAminoMsg): _294.RequestCheckTx;
            fromProtoMsg(message: _294.RequestCheckTxProtoMsg): _294.RequestCheckTx;
            toProto(message: _294.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _294.RequestCheckTx): _294.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            encode(message: _294.RequestDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestDeliverTx;
            fromJSON(object: any): _294.RequestDeliverTx;
            toJSON(message: _294.RequestDeliverTx): unknown;
            fromPartial(object: Partial<_294.RequestDeliverTx>): _294.RequestDeliverTx;
            fromAmino(object: _294.RequestDeliverTxAmino): _294.RequestDeliverTx;
            toAmino(message: _294.RequestDeliverTx): _294.RequestDeliverTxAmino;
            fromAminoMsg(object: _294.RequestDeliverTxAminoMsg): _294.RequestDeliverTx;
            fromProtoMsg(message: _294.RequestDeliverTxProtoMsg): _294.RequestDeliverTx;
            toProto(message: _294.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _294.RequestDeliverTx): _294.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            encode(message: _294.RequestEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestEndBlock;
            fromJSON(object: any): _294.RequestEndBlock;
            toJSON(message: _294.RequestEndBlock): unknown;
            fromPartial(object: Partial<_294.RequestEndBlock>): _294.RequestEndBlock;
            fromAmino(object: _294.RequestEndBlockAmino): _294.RequestEndBlock;
            toAmino(message: _294.RequestEndBlock): _294.RequestEndBlockAmino;
            fromAminoMsg(object: _294.RequestEndBlockAminoMsg): _294.RequestEndBlock;
            fromProtoMsg(message: _294.RequestEndBlockProtoMsg): _294.RequestEndBlock;
            toProto(message: _294.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _294.RequestEndBlock): _294.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            encode(_: _294.RequestCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestCommit;
            fromJSON(_: any): _294.RequestCommit;
            toJSON(_: _294.RequestCommit): unknown;
            fromPartial(_: Partial<_294.RequestCommit>): _294.RequestCommit;
            fromAmino(_: _294.RequestCommitAmino): _294.RequestCommit;
            toAmino(_: _294.RequestCommit): _294.RequestCommitAmino;
            fromAminoMsg(object: _294.RequestCommitAminoMsg): _294.RequestCommit;
            fromProtoMsg(message: _294.RequestCommitProtoMsg): _294.RequestCommit;
            toProto(message: _294.RequestCommit): Uint8Array;
            toProtoMsg(message: _294.RequestCommit): _294.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            encode(_: _294.RequestListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestListSnapshots;
            fromJSON(_: any): _294.RequestListSnapshots;
            toJSON(_: _294.RequestListSnapshots): unknown;
            fromPartial(_: Partial<_294.RequestListSnapshots>): _294.RequestListSnapshots;
            fromAmino(_: _294.RequestListSnapshotsAmino): _294.RequestListSnapshots;
            toAmino(_: _294.RequestListSnapshots): _294.RequestListSnapshotsAmino;
            fromAminoMsg(object: _294.RequestListSnapshotsAminoMsg): _294.RequestListSnapshots;
            fromProtoMsg(message: _294.RequestListSnapshotsProtoMsg): _294.RequestListSnapshots;
            toProto(message: _294.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _294.RequestListSnapshots): _294.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            encode(message: _294.RequestOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestOfferSnapshot;
            fromJSON(object: any): _294.RequestOfferSnapshot;
            toJSON(message: _294.RequestOfferSnapshot): unknown;
            fromPartial(object: Partial<_294.RequestOfferSnapshot>): _294.RequestOfferSnapshot;
            fromAmino(object: _294.RequestOfferSnapshotAmino): _294.RequestOfferSnapshot;
            toAmino(message: _294.RequestOfferSnapshot): _294.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _294.RequestOfferSnapshotAminoMsg): _294.RequestOfferSnapshot;
            fromProtoMsg(message: _294.RequestOfferSnapshotProtoMsg): _294.RequestOfferSnapshot;
            toProto(message: _294.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _294.RequestOfferSnapshot): _294.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            encode(message: _294.RequestLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestLoadSnapshotChunk;
            fromJSON(object: any): _294.RequestLoadSnapshotChunk;
            toJSON(message: _294.RequestLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_294.RequestLoadSnapshotChunk>): _294.RequestLoadSnapshotChunk;
            fromAmino(object: _294.RequestLoadSnapshotChunkAmino): _294.RequestLoadSnapshotChunk;
            toAmino(message: _294.RequestLoadSnapshotChunk): _294.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _294.RequestLoadSnapshotChunkAminoMsg): _294.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _294.RequestLoadSnapshotChunkProtoMsg): _294.RequestLoadSnapshotChunk;
            toProto(message: _294.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _294.RequestLoadSnapshotChunk): _294.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            encode(message: _294.RequestApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.RequestApplySnapshotChunk;
            fromJSON(object: any): _294.RequestApplySnapshotChunk;
            toJSON(message: _294.RequestApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_294.RequestApplySnapshotChunk>): _294.RequestApplySnapshotChunk;
            fromAmino(object: _294.RequestApplySnapshotChunkAmino): _294.RequestApplySnapshotChunk;
            toAmino(message: _294.RequestApplySnapshotChunk): _294.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _294.RequestApplySnapshotChunkAminoMsg): _294.RequestApplySnapshotChunk;
            fromProtoMsg(message: _294.RequestApplySnapshotChunkProtoMsg): _294.RequestApplySnapshotChunk;
            toProto(message: _294.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _294.RequestApplySnapshotChunk): _294.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            encode(message: _294.Response, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.Response;
            fromJSON(object: any): _294.Response;
            toJSON(message: _294.Response): unknown;
            fromPartial(object: Partial<_294.Response>): _294.Response;
            fromAmino(object: _294.ResponseAmino): _294.Response;
            toAmino(message: _294.Response): _294.ResponseAmino;
            fromAminoMsg(object: _294.ResponseAminoMsg): _294.Response;
            fromProtoMsg(message: _294.ResponseProtoMsg): _294.Response;
            toProto(message: _294.Response): Uint8Array;
            toProtoMsg(message: _294.Response): _294.ResponseProtoMsg;
        };
        ResponseException: {
            encode(message: _294.ResponseException, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseException;
            fromJSON(object: any): _294.ResponseException;
            toJSON(message: _294.ResponseException): unknown;
            fromPartial(object: Partial<_294.ResponseException>): _294.ResponseException;
            fromAmino(object: _294.ResponseExceptionAmino): _294.ResponseException;
            toAmino(message: _294.ResponseException): _294.ResponseExceptionAmino;
            fromAminoMsg(object: _294.ResponseExceptionAminoMsg): _294.ResponseException;
            fromProtoMsg(message: _294.ResponseExceptionProtoMsg): _294.ResponseException;
            toProto(message: _294.ResponseException): Uint8Array;
            toProtoMsg(message: _294.ResponseException): _294.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            encode(message: _294.ResponseEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseEcho;
            fromJSON(object: any): _294.ResponseEcho;
            toJSON(message: _294.ResponseEcho): unknown;
            fromPartial(object: Partial<_294.ResponseEcho>): _294.ResponseEcho;
            fromAmino(object: _294.ResponseEchoAmino): _294.ResponseEcho;
            toAmino(message: _294.ResponseEcho): _294.ResponseEchoAmino;
            fromAminoMsg(object: _294.ResponseEchoAminoMsg): _294.ResponseEcho;
            fromProtoMsg(message: _294.ResponseEchoProtoMsg): _294.ResponseEcho;
            toProto(message: _294.ResponseEcho): Uint8Array;
            toProtoMsg(message: _294.ResponseEcho): _294.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            encode(_: _294.ResponseFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseFlush;
            fromJSON(_: any): _294.ResponseFlush;
            toJSON(_: _294.ResponseFlush): unknown;
            fromPartial(_: Partial<_294.ResponseFlush>): _294.ResponseFlush;
            fromAmino(_: _294.ResponseFlushAmino): _294.ResponseFlush;
            toAmino(_: _294.ResponseFlush): _294.ResponseFlushAmino;
            fromAminoMsg(object: _294.ResponseFlushAminoMsg): _294.ResponseFlush;
            fromProtoMsg(message: _294.ResponseFlushProtoMsg): _294.ResponseFlush;
            toProto(message: _294.ResponseFlush): Uint8Array;
            toProtoMsg(message: _294.ResponseFlush): _294.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            encode(message: _294.ResponseInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseInfo;
            fromJSON(object: any): _294.ResponseInfo;
            toJSON(message: _294.ResponseInfo): unknown;
            fromPartial(object: Partial<_294.ResponseInfo>): _294.ResponseInfo;
            fromAmino(object: _294.ResponseInfoAmino): _294.ResponseInfo;
            toAmino(message: _294.ResponseInfo): _294.ResponseInfoAmino;
            fromAminoMsg(object: _294.ResponseInfoAminoMsg): _294.ResponseInfo;
            fromProtoMsg(message: _294.ResponseInfoProtoMsg): _294.ResponseInfo;
            toProto(message: _294.ResponseInfo): Uint8Array;
            toProtoMsg(message: _294.ResponseInfo): _294.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            encode(message: _294.ResponseSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseSetOption;
            fromJSON(object: any): _294.ResponseSetOption;
            toJSON(message: _294.ResponseSetOption): unknown;
            fromPartial(object: Partial<_294.ResponseSetOption>): _294.ResponseSetOption;
            fromAmino(object: _294.ResponseSetOptionAmino): _294.ResponseSetOption;
            toAmino(message: _294.ResponseSetOption): _294.ResponseSetOptionAmino;
            fromAminoMsg(object: _294.ResponseSetOptionAminoMsg): _294.ResponseSetOption;
            fromProtoMsg(message: _294.ResponseSetOptionProtoMsg): _294.ResponseSetOption;
            toProto(message: _294.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _294.ResponseSetOption): _294.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            encode(message: _294.ResponseInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseInitChain;
            fromJSON(object: any): _294.ResponseInitChain;
            toJSON(message: _294.ResponseInitChain): unknown;
            fromPartial(object: Partial<_294.ResponseInitChain>): _294.ResponseInitChain;
            fromAmino(object: _294.ResponseInitChainAmino): _294.ResponseInitChain;
            toAmino(message: _294.ResponseInitChain): _294.ResponseInitChainAmino;
            fromAminoMsg(object: _294.ResponseInitChainAminoMsg): _294.ResponseInitChain;
            fromProtoMsg(message: _294.ResponseInitChainProtoMsg): _294.ResponseInitChain;
            toProto(message: _294.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _294.ResponseInitChain): _294.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            encode(message: _294.ResponseQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseQuery;
            fromJSON(object: any): _294.ResponseQuery;
            toJSON(message: _294.ResponseQuery): unknown;
            fromPartial(object: Partial<_294.ResponseQuery>): _294.ResponseQuery;
            fromAmino(object: _294.ResponseQueryAmino): _294.ResponseQuery;
            toAmino(message: _294.ResponseQuery): _294.ResponseQueryAmino;
            fromAminoMsg(object: _294.ResponseQueryAminoMsg): _294.ResponseQuery;
            fromProtoMsg(message: _294.ResponseQueryProtoMsg): _294.ResponseQuery;
            toProto(message: _294.ResponseQuery): Uint8Array;
            toProtoMsg(message: _294.ResponseQuery): _294.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            encode(message: _294.ResponseBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseBeginBlock;
            fromJSON(object: any): _294.ResponseBeginBlock;
            toJSON(message: _294.ResponseBeginBlock): unknown;
            fromPartial(object: Partial<_294.ResponseBeginBlock>): _294.ResponseBeginBlock;
            fromAmino(object: _294.ResponseBeginBlockAmino): _294.ResponseBeginBlock;
            toAmino(message: _294.ResponseBeginBlock): _294.ResponseBeginBlockAmino;
            fromAminoMsg(object: _294.ResponseBeginBlockAminoMsg): _294.ResponseBeginBlock;
            fromProtoMsg(message: _294.ResponseBeginBlockProtoMsg): _294.ResponseBeginBlock;
            toProto(message: _294.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _294.ResponseBeginBlock): _294.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            encode(message: _294.ResponseCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseCheckTx;
            fromJSON(object: any): _294.ResponseCheckTx;
            toJSON(message: _294.ResponseCheckTx): unknown;
            fromPartial(object: Partial<_294.ResponseCheckTx>): _294.ResponseCheckTx;
            fromAmino(object: _294.ResponseCheckTxAmino): _294.ResponseCheckTx;
            toAmino(message: _294.ResponseCheckTx): _294.ResponseCheckTxAmino;
            fromAminoMsg(object: _294.ResponseCheckTxAminoMsg): _294.ResponseCheckTx;
            fromProtoMsg(message: _294.ResponseCheckTxProtoMsg): _294.ResponseCheckTx;
            toProto(message: _294.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _294.ResponseCheckTx): _294.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            encode(message: _294.ResponseDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseDeliverTx;
            fromJSON(object: any): _294.ResponseDeliverTx;
            toJSON(message: _294.ResponseDeliverTx): unknown;
            fromPartial(object: Partial<_294.ResponseDeliverTx>): _294.ResponseDeliverTx;
            fromAmino(object: _294.ResponseDeliverTxAmino): _294.ResponseDeliverTx;
            toAmino(message: _294.ResponseDeliverTx): _294.ResponseDeliverTxAmino;
            fromAminoMsg(object: _294.ResponseDeliverTxAminoMsg): _294.ResponseDeliverTx;
            fromProtoMsg(message: _294.ResponseDeliverTxProtoMsg): _294.ResponseDeliverTx;
            toProto(message: _294.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _294.ResponseDeliverTx): _294.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            encode(message: _294.ResponseEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseEndBlock;
            fromJSON(object: any): _294.ResponseEndBlock;
            toJSON(message: _294.ResponseEndBlock): unknown;
            fromPartial(object: Partial<_294.ResponseEndBlock>): _294.ResponseEndBlock;
            fromAmino(object: _294.ResponseEndBlockAmino): _294.ResponseEndBlock;
            toAmino(message: _294.ResponseEndBlock): _294.ResponseEndBlockAmino;
            fromAminoMsg(object: _294.ResponseEndBlockAminoMsg): _294.ResponseEndBlock;
            fromProtoMsg(message: _294.ResponseEndBlockProtoMsg): _294.ResponseEndBlock;
            toProto(message: _294.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _294.ResponseEndBlock): _294.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            encode(message: _294.ResponseCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseCommit;
            fromJSON(object: any): _294.ResponseCommit;
            toJSON(message: _294.ResponseCommit): unknown;
            fromPartial(object: Partial<_294.ResponseCommit>): _294.ResponseCommit;
            fromAmino(object: _294.ResponseCommitAmino): _294.ResponseCommit;
            toAmino(message: _294.ResponseCommit): _294.ResponseCommitAmino;
            fromAminoMsg(object: _294.ResponseCommitAminoMsg): _294.ResponseCommit;
            fromProtoMsg(message: _294.ResponseCommitProtoMsg): _294.ResponseCommit;
            toProto(message: _294.ResponseCommit): Uint8Array;
            toProtoMsg(message: _294.ResponseCommit): _294.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            encode(message: _294.ResponseListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseListSnapshots;
            fromJSON(object: any): _294.ResponseListSnapshots;
            toJSON(message: _294.ResponseListSnapshots): unknown;
            fromPartial(object: Partial<_294.ResponseListSnapshots>): _294.ResponseListSnapshots;
            fromAmino(object: _294.ResponseListSnapshotsAmino): _294.ResponseListSnapshots;
            toAmino(message: _294.ResponseListSnapshots): _294.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _294.ResponseListSnapshotsAminoMsg): _294.ResponseListSnapshots;
            fromProtoMsg(message: _294.ResponseListSnapshotsProtoMsg): _294.ResponseListSnapshots;
            toProto(message: _294.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _294.ResponseListSnapshots): _294.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            encode(message: _294.ResponseOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseOfferSnapshot;
            fromJSON(object: any): _294.ResponseOfferSnapshot;
            toJSON(message: _294.ResponseOfferSnapshot): unknown;
            fromPartial(object: Partial<_294.ResponseOfferSnapshot>): _294.ResponseOfferSnapshot;
            fromAmino(object: _294.ResponseOfferSnapshotAmino): _294.ResponseOfferSnapshot;
            toAmino(message: _294.ResponseOfferSnapshot): _294.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _294.ResponseOfferSnapshotAminoMsg): _294.ResponseOfferSnapshot;
            fromProtoMsg(message: _294.ResponseOfferSnapshotProtoMsg): _294.ResponseOfferSnapshot;
            toProto(message: _294.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _294.ResponseOfferSnapshot): _294.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            encode(message: _294.ResponseLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseLoadSnapshotChunk;
            fromJSON(object: any): _294.ResponseLoadSnapshotChunk;
            toJSON(message: _294.ResponseLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_294.ResponseLoadSnapshotChunk>): _294.ResponseLoadSnapshotChunk;
            fromAmino(object: _294.ResponseLoadSnapshotChunkAmino): _294.ResponseLoadSnapshotChunk;
            toAmino(message: _294.ResponseLoadSnapshotChunk): _294.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _294.ResponseLoadSnapshotChunkAminoMsg): _294.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _294.ResponseLoadSnapshotChunkProtoMsg): _294.ResponseLoadSnapshotChunk;
            toProto(message: _294.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _294.ResponseLoadSnapshotChunk): _294.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            encode(message: _294.ResponseApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ResponseApplySnapshotChunk;
            fromJSON(object: any): _294.ResponseApplySnapshotChunk;
            toJSON(message: _294.ResponseApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_294.ResponseApplySnapshotChunk>): _294.ResponseApplySnapshotChunk;
            fromAmino(object: _294.ResponseApplySnapshotChunkAmino): _294.ResponseApplySnapshotChunk;
            toAmino(message: _294.ResponseApplySnapshotChunk): _294.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _294.ResponseApplySnapshotChunkAminoMsg): _294.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _294.ResponseApplySnapshotChunkProtoMsg): _294.ResponseApplySnapshotChunk;
            toProto(message: _294.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _294.ResponseApplySnapshotChunk): _294.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            encode(message: _294.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ConsensusParams;
            fromJSON(object: any): _294.ConsensusParams;
            toJSON(message: _294.ConsensusParams): unknown;
            fromPartial(object: Partial<_294.ConsensusParams>): _294.ConsensusParams;
            fromAmino(object: _294.ConsensusParamsAmino): _294.ConsensusParams;
            toAmino(message: _294.ConsensusParams): _294.ConsensusParamsAmino;
            fromAminoMsg(object: _294.ConsensusParamsAminoMsg): _294.ConsensusParams;
            fromProtoMsg(message: _294.ConsensusParamsProtoMsg): _294.ConsensusParams;
            toProto(message: _294.ConsensusParams): Uint8Array;
            toProtoMsg(message: _294.ConsensusParams): _294.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _294.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.BlockParams;
            fromJSON(object: any): _294.BlockParams;
            toJSON(message: _294.BlockParams): unknown;
            fromPartial(object: Partial<_294.BlockParams>): _294.BlockParams;
            fromAmino(object: _294.BlockParamsAmino): _294.BlockParams;
            toAmino(message: _294.BlockParams): _294.BlockParamsAmino;
            fromAminoMsg(object: _294.BlockParamsAminoMsg): _294.BlockParams;
            fromProtoMsg(message: _294.BlockParamsProtoMsg): _294.BlockParams;
            toProto(message: _294.BlockParams): Uint8Array;
            toProtoMsg(message: _294.BlockParams): _294.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            encode(message: _294.LastCommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.LastCommitInfo;
            fromJSON(object: any): _294.LastCommitInfo;
            toJSON(message: _294.LastCommitInfo): unknown;
            fromPartial(object: Partial<_294.LastCommitInfo>): _294.LastCommitInfo;
            fromAmino(object: _294.LastCommitInfoAmino): _294.LastCommitInfo;
            toAmino(message: _294.LastCommitInfo): _294.LastCommitInfoAmino;
            fromAminoMsg(object: _294.LastCommitInfoAminoMsg): _294.LastCommitInfo;
            fromProtoMsg(message: _294.LastCommitInfoProtoMsg): _294.LastCommitInfo;
            toProto(message: _294.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _294.LastCommitInfo): _294.LastCommitInfoProtoMsg;
        };
        Event: {
            encode(message: _294.Event, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.Event;
            fromJSON(object: any): _294.Event;
            toJSON(message: _294.Event): unknown;
            fromPartial(object: Partial<_294.Event>): _294.Event;
            fromAmino(object: _294.EventAmino): _294.Event;
            toAmino(message: _294.Event): _294.EventAmino;
            fromAminoMsg(object: _294.EventAminoMsg): _294.Event;
            fromProtoMsg(message: _294.EventProtoMsg): _294.Event;
            toProto(message: _294.Event): Uint8Array;
            toProtoMsg(message: _294.Event): _294.EventProtoMsg;
        };
        EventAttribute: {
            encode(message: _294.EventAttribute, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.EventAttribute;
            fromJSON(object: any): _294.EventAttribute;
            toJSON(message: _294.EventAttribute): unknown;
            fromPartial(object: Partial<_294.EventAttribute>): _294.EventAttribute;
            fromAmino(object: _294.EventAttributeAmino): _294.EventAttribute;
            toAmino(message: _294.EventAttribute): _294.EventAttributeAmino;
            fromAminoMsg(object: _294.EventAttributeAminoMsg): _294.EventAttribute;
            fromProtoMsg(message: _294.EventAttributeProtoMsg): _294.EventAttribute;
            toProto(message: _294.EventAttribute): Uint8Array;
            toProtoMsg(message: _294.EventAttribute): _294.EventAttributeProtoMsg;
        };
        TxResult: {
            encode(message: _294.TxResult, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.TxResult;
            fromJSON(object: any): _294.TxResult;
            toJSON(message: _294.TxResult): unknown;
            fromPartial(object: Partial<_294.TxResult>): _294.TxResult;
            fromAmino(object: _294.TxResultAmino): _294.TxResult;
            toAmino(message: _294.TxResult): _294.TxResultAmino;
            fromAminoMsg(object: _294.TxResultAminoMsg): _294.TxResult;
            fromProtoMsg(message: _294.TxResultProtoMsg): _294.TxResult;
            toProto(message: _294.TxResult): Uint8Array;
            toProtoMsg(message: _294.TxResult): _294.TxResultProtoMsg;
        };
        Validator: {
            encode(message: _294.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.Validator;
            fromJSON(object: any): _294.Validator;
            toJSON(message: _294.Validator): unknown;
            fromPartial(object: Partial<_294.Validator>): _294.Validator;
            fromAmino(object: _294.ValidatorAmino): _294.Validator;
            toAmino(message: _294.Validator): _294.ValidatorAmino;
            fromAminoMsg(object: _294.ValidatorAminoMsg): _294.Validator;
            fromProtoMsg(message: _294.ValidatorProtoMsg): _294.Validator;
            toProto(message: _294.Validator): Uint8Array;
            toProtoMsg(message: _294.Validator): _294.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            encode(message: _294.ValidatorUpdate, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ValidatorUpdate;
            fromJSON(object: any): _294.ValidatorUpdate;
            toJSON(message: _294.ValidatorUpdate): unknown;
            fromPartial(object: Partial<_294.ValidatorUpdate>): _294.ValidatorUpdate;
            fromAmino(object: _294.ValidatorUpdateAmino): _294.ValidatorUpdate;
            toAmino(message: _294.ValidatorUpdate): _294.ValidatorUpdateAmino;
            fromAminoMsg(object: _294.ValidatorUpdateAminoMsg): _294.ValidatorUpdate;
            fromProtoMsg(message: _294.ValidatorUpdateProtoMsg): _294.ValidatorUpdate;
            toProto(message: _294.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _294.ValidatorUpdate): _294.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            encode(message: _294.VoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.VoteInfo;
            fromJSON(object: any): _294.VoteInfo;
            toJSON(message: _294.VoteInfo): unknown;
            fromPartial(object: Partial<_294.VoteInfo>): _294.VoteInfo;
            fromAmino(object: _294.VoteInfoAmino): _294.VoteInfo;
            toAmino(message: _294.VoteInfo): _294.VoteInfoAmino;
            fromAminoMsg(object: _294.VoteInfoAminoMsg): _294.VoteInfo;
            fromProtoMsg(message: _294.VoteInfoProtoMsg): _294.VoteInfo;
            toProto(message: _294.VoteInfo): Uint8Array;
            toProtoMsg(message: _294.VoteInfo): _294.VoteInfoProtoMsg;
        };
        Evidence: {
            encode(message: _294.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.Evidence;
            fromJSON(object: any): _294.Evidence;
            toJSON(message: _294.Evidence): unknown;
            fromPartial(object: Partial<_294.Evidence>): _294.Evidence;
            fromAmino(object: _294.EvidenceAmino): _294.Evidence;
            toAmino(message: _294.Evidence): _294.EvidenceAmino;
            fromAminoMsg(object: _294.EvidenceAminoMsg): _294.Evidence;
            fromProtoMsg(message: _294.EvidenceProtoMsg): _294.Evidence;
            toProto(message: _294.Evidence): Uint8Array;
            toProtoMsg(message: _294.Evidence): _294.EvidenceProtoMsg;
        };
        Snapshot: {
            encode(message: _294.Snapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.Snapshot;
            fromJSON(object: any): _294.Snapshot;
            toJSON(message: _294.Snapshot): unknown;
            fromPartial(object: Partial<_294.Snapshot>): _294.Snapshot;
            fromAmino(object: _294.SnapshotAmino): _294.Snapshot;
            toAmino(message: _294.Snapshot): _294.SnapshotAmino;
            fromAminoMsg(object: _294.SnapshotAminoMsg): _294.Snapshot;
            fromProtoMsg(message: _294.SnapshotProtoMsg): _294.Snapshot;
            toProto(message: _294.Snapshot): Uint8Array;
            toProtoMsg(message: _294.Snapshot): _294.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            encode(message: _296.Proof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _296.Proof;
            fromJSON(object: any): _296.Proof;
            toJSON(message: _296.Proof): unknown;
            fromPartial(object: Partial<_296.Proof>): _296.Proof;
            fromAmino(object: _296.ProofAmino): _296.Proof;
            toAmino(message: _296.Proof): _296.ProofAmino;
            fromAminoMsg(object: _296.ProofAminoMsg): _296.Proof;
            fromProtoMsg(message: _296.ProofProtoMsg): _296.Proof;
            toProto(message: _296.Proof): Uint8Array;
            toProtoMsg(message: _296.Proof): _296.ProofProtoMsg;
        };
        ValueOp: {
            encode(message: _296.ValueOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _296.ValueOp;
            fromJSON(object: any): _296.ValueOp;
            toJSON(message: _296.ValueOp): unknown;
            fromPartial(object: Partial<_296.ValueOp>): _296.ValueOp;
            fromAmino(object: _296.ValueOpAmino): _296.ValueOp;
            toAmino(message: _296.ValueOp): _296.ValueOpAmino;
            fromAminoMsg(object: _296.ValueOpAminoMsg): _296.ValueOp;
            fromProtoMsg(message: _296.ValueOpProtoMsg): _296.ValueOp;
            toProto(message: _296.ValueOp): Uint8Array;
            toProtoMsg(message: _296.ValueOp): _296.ValueOpProtoMsg;
        };
        DominoOp: {
            encode(message: _296.DominoOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _296.DominoOp;
            fromJSON(object: any): _296.DominoOp;
            toJSON(message: _296.DominoOp): unknown;
            fromPartial(object: Partial<_296.DominoOp>): _296.DominoOp;
            fromAmino(object: _296.DominoOpAmino): _296.DominoOp;
            toAmino(message: _296.DominoOp): _296.DominoOpAmino;
            fromAminoMsg(object: _296.DominoOpAminoMsg): _296.DominoOp;
            fromProtoMsg(message: _296.DominoOpProtoMsg): _296.DominoOp;
            toProto(message: _296.DominoOp): Uint8Array;
            toProtoMsg(message: _296.DominoOp): _296.DominoOpProtoMsg;
        };
        ProofOp: {
            encode(message: _296.ProofOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _296.ProofOp;
            fromJSON(object: any): _296.ProofOp;
            toJSON(message: _296.ProofOp): unknown;
            fromPartial(object: Partial<_296.ProofOp>): _296.ProofOp;
            fromAmino(object: _296.ProofOpAmino): _296.ProofOp;
            toAmino(message: _296.ProofOp): _296.ProofOpAmino;
            fromAminoMsg(object: _296.ProofOpAminoMsg): _296.ProofOp;
            fromProtoMsg(message: _296.ProofOpProtoMsg): _296.ProofOp;
            toProto(message: _296.ProofOp): Uint8Array;
            toProtoMsg(message: _296.ProofOp): _296.ProofOpProtoMsg;
        };
        ProofOps: {
            encode(message: _296.ProofOps, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _296.ProofOps;
            fromJSON(object: any): _296.ProofOps;
            toJSON(message: _296.ProofOps): unknown;
            fromPartial(object: Partial<_296.ProofOps>): _296.ProofOps;
            fromAmino(object: _296.ProofOpsAmino): _296.ProofOps;
            toAmino(message: _296.ProofOps): _296.ProofOpsAmino;
            fromAminoMsg(object: _296.ProofOpsAminoMsg): _296.ProofOps;
            fromProtoMsg(message: _296.ProofOpsProtoMsg): _296.ProofOps;
            toProto(message: _296.ProofOps): Uint8Array;
            toProtoMsg(message: _296.ProofOps): _296.ProofOpsProtoMsg;
        };
        PublicKey: {
            encode(message: _295.PublicKey, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _295.PublicKey;
            fromJSON(object: any): _295.PublicKey;
            toJSON(message: _295.PublicKey): unknown;
            fromPartial(object: Partial<_295.PublicKey>): _295.PublicKey;
            fromAmino(object: _295.PublicKeyAmino): _295.PublicKey;
            toAmino(message: _295.PublicKey): _295.PublicKeyAmino;
            fromAminoMsg(object: _295.PublicKeyAminoMsg): _295.PublicKey;
            fromProtoMsg(message: _295.PublicKeyProtoMsg): _295.PublicKey;
            toProto(message: _295.PublicKey): Uint8Array;
            toProtoMsg(message: _295.PublicKey): _295.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                encode(message: _297.BitArray, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
                decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _297.BitArray;
                fromJSON(object: any): _297.BitArray;
                toJSON(message: _297.BitArray): unknown;
                fromPartial(object: Partial<_297.BitArray>): _297.BitArray;
                fromAmino(object: _297.BitArrayAmino): _297.BitArray;
                toAmino(message: _297.BitArray): _297.BitArrayAmino;
                fromAminoMsg(object: _297.BitArrayAminoMsg): _297.BitArray;
                fromProtoMsg(message: _297.BitArrayProtoMsg): _297.BitArray;
                toProto(message: _297.BitArray): Uint8Array;
                toProtoMsg(message: _297.BitArray): _297.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        ProtocolVersion: {
            encode(message: _298.ProtocolVersion, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.ProtocolVersion;
            fromJSON(object: any): _298.ProtocolVersion;
            toJSON(message: _298.ProtocolVersion): unknown;
            fromPartial(object: Partial<_298.ProtocolVersion>): _298.ProtocolVersion;
            fromAmino(object: _298.ProtocolVersionAmino): _298.ProtocolVersion;
            toAmino(message: _298.ProtocolVersion): _298.ProtocolVersionAmino;
            fromAminoMsg(object: _298.ProtocolVersionAminoMsg): _298.ProtocolVersion;
            fromProtoMsg(message: _298.ProtocolVersionProtoMsg): _298.ProtocolVersion;
            toProto(message: _298.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _298.ProtocolVersion): _298.ProtocolVersionProtoMsg;
        };
        NodeInfo: {
            encode(message: _298.NodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.NodeInfo;
            fromJSON(object: any): _298.NodeInfo;
            toJSON(message: _298.NodeInfo): unknown;
            fromPartial(object: Partial<_298.NodeInfo>): _298.NodeInfo;
            fromAmino(object: _298.NodeInfoAmino): _298.NodeInfo;
            toAmino(message: _298.NodeInfo): _298.NodeInfoAmino;
            fromAminoMsg(object: _298.NodeInfoAminoMsg): _298.NodeInfo;
            fromProtoMsg(message: _298.NodeInfoProtoMsg): _298.NodeInfo;
            toProto(message: _298.NodeInfo): Uint8Array;
            toProtoMsg(message: _298.NodeInfo): _298.NodeInfoProtoMsg;
        };
        NodeInfoOther: {
            encode(message: _298.NodeInfoOther, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.NodeInfoOther;
            fromJSON(object: any): _298.NodeInfoOther;
            toJSON(message: _298.NodeInfoOther): unknown;
            fromPartial(object: Partial<_298.NodeInfoOther>): _298.NodeInfoOther;
            fromAmino(object: _298.NodeInfoOtherAmino): _298.NodeInfoOther;
            toAmino(message: _298.NodeInfoOther): _298.NodeInfoOtherAmino;
            fromAminoMsg(object: _298.NodeInfoOtherAminoMsg): _298.NodeInfoOther;
            fromProtoMsg(message: _298.NodeInfoOtherProtoMsg): _298.NodeInfoOther;
            toProto(message: _298.NodeInfoOther): Uint8Array;
            toProtoMsg(message: _298.NodeInfoOther): _298.NodeInfoOtherProtoMsg;
        };
        PeerInfo: {
            encode(message: _298.PeerInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.PeerInfo;
            fromJSON(object: any): _298.PeerInfo;
            toJSON(message: _298.PeerInfo): unknown;
            fromPartial(object: Partial<_298.PeerInfo>): _298.PeerInfo;
            fromAmino(object: _298.PeerInfoAmino): _298.PeerInfo;
            toAmino(message: _298.PeerInfo): _298.PeerInfoAmino;
            fromAminoMsg(object: _298.PeerInfoAminoMsg): _298.PeerInfo;
            fromProtoMsg(message: _298.PeerInfoProtoMsg): _298.PeerInfo;
            toProto(message: _298.PeerInfo): Uint8Array;
            toProtoMsg(message: _298.PeerInfo): _298.PeerInfoProtoMsg;
        };
        PeerAddressInfo: {
            encode(message: _298.PeerAddressInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.PeerAddressInfo;
            fromJSON(object: any): _298.PeerAddressInfo;
            toJSON(message: _298.PeerAddressInfo): unknown;
            fromPartial(object: Partial<_298.PeerAddressInfo>): _298.PeerAddressInfo;
            fromAmino(object: _298.PeerAddressInfoAmino): _298.PeerAddressInfo;
            toAmino(message: _298.PeerAddressInfo): _298.PeerAddressInfoAmino;
            fromAminoMsg(object: _298.PeerAddressInfoAminoMsg): _298.PeerAddressInfo;
            fromProtoMsg(message: _298.PeerAddressInfoProtoMsg): _298.PeerAddressInfo;
            toProto(message: _298.PeerAddressInfo): Uint8Array;
            toProtoMsg(message: _298.PeerAddressInfo): _298.PeerAddressInfoProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            encode(message: _303.ValidatorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _303.ValidatorSet;
            fromJSON(object: any): _303.ValidatorSet;
            toJSON(message: _303.ValidatorSet): unknown;
            fromPartial(object: Partial<_303.ValidatorSet>): _303.ValidatorSet;
            fromAmino(object: _303.ValidatorSetAmino): _303.ValidatorSet;
            toAmino(message: _303.ValidatorSet): _303.ValidatorSetAmino;
            fromAminoMsg(object: _303.ValidatorSetAminoMsg): _303.ValidatorSet;
            fromProtoMsg(message: _303.ValidatorSetProtoMsg): _303.ValidatorSet;
            toProto(message: _303.ValidatorSet): Uint8Array;
            toProtoMsg(message: _303.ValidatorSet): _303.ValidatorSetProtoMsg;
        };
        Validator: {
            encode(message: _303.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _303.Validator;
            fromJSON(object: any): _303.Validator;
            toJSON(message: _303.Validator): unknown;
            fromPartial(object: Partial<_303.Validator>): _303.Validator;
            fromAmino(object: _303.ValidatorAmino): _303.Validator;
            toAmino(message: _303.Validator): _303.ValidatorAmino;
            fromAminoMsg(object: _303.ValidatorAminoMsg): _303.Validator;
            fromProtoMsg(message: _303.ValidatorProtoMsg): _303.Validator;
            toProto(message: _303.Validator): Uint8Array;
            toProtoMsg(message: _303.Validator): _303.ValidatorProtoMsg;
        };
        SimpleValidator: {
            encode(message: _303.SimpleValidator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _303.SimpleValidator;
            fromJSON(object: any): _303.SimpleValidator;
            toJSON(message: _303.SimpleValidator): unknown;
            fromPartial(object: Partial<_303.SimpleValidator>): _303.SimpleValidator;
            fromAmino(object: _303.SimpleValidatorAmino): _303.SimpleValidator;
            toAmino(message: _303.SimpleValidator): _303.SimpleValidatorAmino;
            fromAminoMsg(object: _303.SimpleValidatorAminoMsg): _303.SimpleValidator;
            fromProtoMsg(message: _303.SimpleValidatorProtoMsg): _303.SimpleValidator;
            toProto(message: _303.SimpleValidator): Uint8Array;
            toProtoMsg(message: _303.SimpleValidator): _303.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _302.BlockIDFlag;
        blockIDFlagToJSON(object: _302.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _302.SignedMsgType;
        signedMsgTypeToJSON(object: _302.SignedMsgType): string;
        BlockIDFlag: typeof _302.BlockIDFlag;
        BlockIDFlagSDKType: typeof _302.BlockIDFlag;
        BlockIDFlagAmino: typeof _302.BlockIDFlag;
        SignedMsgType: typeof _302.SignedMsgType;
        SignedMsgTypeSDKType: typeof _302.SignedMsgType;
        SignedMsgTypeAmino: typeof _302.SignedMsgType;
        PartSetHeader: {
            encode(message: _302.PartSetHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.PartSetHeader;
            fromJSON(object: any): _302.PartSetHeader;
            toJSON(message: _302.PartSetHeader): unknown;
            fromPartial(object: Partial<_302.PartSetHeader>): _302.PartSetHeader;
            fromAmino(object: _302.PartSetHeaderAmino): _302.PartSetHeader;
            toAmino(message: _302.PartSetHeader): _302.PartSetHeaderAmino;
            fromAminoMsg(object: _302.PartSetHeaderAminoMsg): _302.PartSetHeader;
            fromProtoMsg(message: _302.PartSetHeaderProtoMsg): _302.PartSetHeader;
            toProto(message: _302.PartSetHeader): Uint8Array;
            toProtoMsg(message: _302.PartSetHeader): _302.PartSetHeaderProtoMsg;
        };
        Part: {
            encode(message: _302.Part, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Part;
            fromJSON(object: any): _302.Part;
            toJSON(message: _302.Part): unknown;
            fromPartial(object: Partial<_302.Part>): _302.Part;
            fromAmino(object: _302.PartAmino): _302.Part;
            toAmino(message: _302.Part): _302.PartAmino;
            fromAminoMsg(object: _302.PartAminoMsg): _302.Part;
            fromProtoMsg(message: _302.PartProtoMsg): _302.Part;
            toProto(message: _302.Part): Uint8Array;
            toProtoMsg(message: _302.Part): _302.PartProtoMsg;
        };
        BlockID: {
            encode(message: _302.BlockID, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.BlockID;
            fromJSON(object: any): _302.BlockID;
            toJSON(message: _302.BlockID): unknown;
            fromPartial(object: Partial<_302.BlockID>): _302.BlockID;
            fromAmino(object: _302.BlockIDAmino): _302.BlockID;
            toAmino(message: _302.BlockID): _302.BlockIDAmino;
            fromAminoMsg(object: _302.BlockIDAminoMsg): _302.BlockID;
            fromProtoMsg(message: _302.BlockIDProtoMsg): _302.BlockID;
            toProto(message: _302.BlockID): Uint8Array;
            toProtoMsg(message: _302.BlockID): _302.BlockIDProtoMsg;
        };
        Header: {
            encode(message: _302.Header, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Header;
            fromJSON(object: any): _302.Header;
            toJSON(message: _302.Header): unknown;
            fromPartial(object: Partial<_302.Header>): _302.Header;
            fromAmino(object: _302.HeaderAmino): _302.Header;
            toAmino(message: _302.Header): _302.HeaderAmino;
            fromAminoMsg(object: _302.HeaderAminoMsg): _302.Header;
            fromProtoMsg(message: _302.HeaderProtoMsg): _302.Header;
            toProto(message: _302.Header): Uint8Array;
            toProtoMsg(message: _302.Header): _302.HeaderProtoMsg;
        };
        Data: {
            encode(message: _302.Data, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Data;
            fromJSON(object: any): _302.Data;
            toJSON(message: _302.Data): unknown;
            fromPartial(object: Partial<_302.Data>): _302.Data;
            fromAmino(object: _302.DataAmino): _302.Data;
            toAmino(message: _302.Data): _302.DataAmino;
            fromAminoMsg(object: _302.DataAminoMsg): _302.Data;
            fromProtoMsg(message: _302.DataProtoMsg): _302.Data;
            toProto(message: _302.Data): Uint8Array;
            toProtoMsg(message: _302.Data): _302.DataProtoMsg;
        };
        Vote: {
            encode(message: _302.Vote, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Vote;
            fromJSON(object: any): _302.Vote;
            toJSON(message: _302.Vote): unknown;
            fromPartial(object: Partial<_302.Vote>): _302.Vote;
            fromAmino(object: _302.VoteAmino): _302.Vote;
            toAmino(message: _302.Vote): _302.VoteAmino;
            fromAminoMsg(object: _302.VoteAminoMsg): _302.Vote;
            fromProtoMsg(message: _302.VoteProtoMsg): _302.Vote;
            toProto(message: _302.Vote): Uint8Array;
            toProtoMsg(message: _302.Vote): _302.VoteProtoMsg;
        };
        Commit: {
            encode(message: _302.Commit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Commit;
            fromJSON(object: any): _302.Commit;
            toJSON(message: _302.Commit): unknown;
            fromPartial(object: Partial<_302.Commit>): _302.Commit;
            fromAmino(object: _302.CommitAmino): _302.Commit;
            toAmino(message: _302.Commit): _302.CommitAmino;
            fromAminoMsg(object: _302.CommitAminoMsg): _302.Commit;
            fromProtoMsg(message: _302.CommitProtoMsg): _302.Commit;
            toProto(message: _302.Commit): Uint8Array;
            toProtoMsg(message: _302.Commit): _302.CommitProtoMsg;
        };
        CommitSig: {
            encode(message: _302.CommitSig, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.CommitSig;
            fromJSON(object: any): _302.CommitSig;
            toJSON(message: _302.CommitSig): unknown;
            fromPartial(object: Partial<_302.CommitSig>): _302.CommitSig;
            fromAmino(object: _302.CommitSigAmino): _302.CommitSig;
            toAmino(message: _302.CommitSig): _302.CommitSigAmino;
            fromAminoMsg(object: _302.CommitSigAminoMsg): _302.CommitSig;
            fromProtoMsg(message: _302.CommitSigProtoMsg): _302.CommitSig;
            toProto(message: _302.CommitSig): Uint8Array;
            toProtoMsg(message: _302.CommitSig): _302.CommitSigProtoMsg;
        };
        Proposal: {
            encode(message: _302.Proposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.Proposal;
            fromJSON(object: any): _302.Proposal;
            toJSON(message: _302.Proposal): unknown;
            fromPartial(object: Partial<_302.Proposal>): _302.Proposal;
            fromAmino(object: _302.ProposalAmino): _302.Proposal;
            toAmino(message: _302.Proposal): _302.ProposalAmino;
            fromAminoMsg(object: _302.ProposalAminoMsg): _302.Proposal;
            fromProtoMsg(message: _302.ProposalProtoMsg): _302.Proposal;
            toProto(message: _302.Proposal): Uint8Array;
            toProtoMsg(message: _302.Proposal): _302.ProposalProtoMsg;
        };
        SignedHeader: {
            encode(message: _302.SignedHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.SignedHeader;
            fromJSON(object: any): _302.SignedHeader;
            toJSON(message: _302.SignedHeader): unknown;
            fromPartial(object: Partial<_302.SignedHeader>): _302.SignedHeader;
            fromAmino(object: _302.SignedHeaderAmino): _302.SignedHeader;
            toAmino(message: _302.SignedHeader): _302.SignedHeaderAmino;
            fromAminoMsg(object: _302.SignedHeaderAminoMsg): _302.SignedHeader;
            fromProtoMsg(message: _302.SignedHeaderProtoMsg): _302.SignedHeader;
            toProto(message: _302.SignedHeader): Uint8Array;
            toProtoMsg(message: _302.SignedHeader): _302.SignedHeaderProtoMsg;
        };
        LightBlock: {
            encode(message: _302.LightBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.LightBlock;
            fromJSON(object: any): _302.LightBlock;
            toJSON(message: _302.LightBlock): unknown;
            fromPartial(object: Partial<_302.LightBlock>): _302.LightBlock;
            fromAmino(object: _302.LightBlockAmino): _302.LightBlock;
            toAmino(message: _302.LightBlock): _302.LightBlockAmino;
            fromAminoMsg(object: _302.LightBlockAminoMsg): _302.LightBlock;
            fromProtoMsg(message: _302.LightBlockProtoMsg): _302.LightBlock;
            toProto(message: _302.LightBlock): Uint8Array;
            toProtoMsg(message: _302.LightBlock): _302.LightBlockProtoMsg;
        };
        BlockMeta: {
            encode(message: _302.BlockMeta, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.BlockMeta;
            fromJSON(object: any): _302.BlockMeta;
            toJSON(message: _302.BlockMeta): unknown;
            fromPartial(object: Partial<_302.BlockMeta>): _302.BlockMeta;
            fromAmino(object: _302.BlockMetaAmino): _302.BlockMeta;
            toAmino(message: _302.BlockMeta): _302.BlockMetaAmino;
            fromAminoMsg(object: _302.BlockMetaAminoMsg): _302.BlockMeta;
            fromProtoMsg(message: _302.BlockMetaProtoMsg): _302.BlockMeta;
            toProto(message: _302.BlockMeta): Uint8Array;
            toProtoMsg(message: _302.BlockMeta): _302.BlockMetaProtoMsg;
        };
        TxProof: {
            encode(message: _302.TxProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _302.TxProof;
            fromJSON(object: any): _302.TxProof;
            toJSON(message: _302.TxProof): unknown;
            fromPartial(object: Partial<_302.TxProof>): _302.TxProof;
            fromAmino(object: _302.TxProofAmino): _302.TxProof;
            toAmino(message: _302.TxProof): _302.TxProofAmino;
            fromAminoMsg(object: _302.TxProofAminoMsg): _302.TxProof;
            fromProtoMsg(message: _302.TxProofProtoMsg): _302.TxProof;
            toProto(message: _302.TxProof): Uint8Array;
            toProtoMsg(message: _302.TxProof): _302.TxProofProtoMsg;
        };
        ConsensusParams: {
            encode(message: _301.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _301.ConsensusParams;
            fromJSON(object: any): _301.ConsensusParams;
            toJSON(message: _301.ConsensusParams): unknown;
            fromPartial(object: Partial<_301.ConsensusParams>): _301.ConsensusParams;
            fromAmino(object: _301.ConsensusParamsAmino): _301.ConsensusParams;
            toAmino(message: _301.ConsensusParams): _301.ConsensusParamsAmino;
            fromAminoMsg(object: _301.ConsensusParamsAminoMsg): _301.ConsensusParams;
            fromProtoMsg(message: _301.ConsensusParamsProtoMsg): _301.ConsensusParams;
            toProto(message: _301.ConsensusParams): Uint8Array;
            toProtoMsg(message: _301.ConsensusParams): _301.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _301.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _301.BlockParams;
            fromJSON(object: any): _301.BlockParams;
            toJSON(message: _301.BlockParams): unknown;
            fromPartial(object: Partial<_301.BlockParams>): _301.BlockParams;
            fromAmino(object: _301.BlockParamsAmino): _301.BlockParams;
            toAmino(message: _301.BlockParams): _301.BlockParamsAmino;
            fromAminoMsg(object: _301.BlockParamsAminoMsg): _301.BlockParams;
            fromProtoMsg(message: _301.BlockParamsProtoMsg): _301.BlockParams;
            toProto(message: _301.BlockParams): Uint8Array;
            toProtoMsg(message: _301.BlockParams): _301.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            encode(message: _301.EvidenceParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _301.EvidenceParams;
            fromJSON(object: any): _301.EvidenceParams;
            toJSON(message: _301.EvidenceParams): unknown;
            fromPartial(object: Partial<_301.EvidenceParams>): _301.EvidenceParams;
            fromAmino(object: _301.EvidenceParamsAmino): _301.EvidenceParams;
            toAmino(message: _301.EvidenceParams): _301.EvidenceParamsAmino;
            fromAminoMsg(object: _301.EvidenceParamsAminoMsg): _301.EvidenceParams;
            fromProtoMsg(message: _301.EvidenceParamsProtoMsg): _301.EvidenceParams;
            toProto(message: _301.EvidenceParams): Uint8Array;
            toProtoMsg(message: _301.EvidenceParams): _301.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            encode(message: _301.ValidatorParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _301.ValidatorParams;
            fromJSON(object: any): _301.ValidatorParams;
            toJSON(message: _301.ValidatorParams): unknown;
            fromPartial(object: Partial<_301.ValidatorParams>): _301.ValidatorParams;
            fromAmino(object: _301.ValidatorParamsAmino): _301.ValidatorParams;
            toAmino(message: _301.ValidatorParams): _301.ValidatorParamsAmino;
            fromAminoMsg(object: _301.ValidatorParamsAminoMsg): _301.ValidatorParams;
            fromProtoMsg(message: _301.ValidatorParamsProtoMsg): _301.ValidatorParams;
            toProto(message: _301.ValidatorParams): Uint8Array;
            toProtoMsg(message: _301.ValidatorParams): _301.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            encode(message: _301.VersionParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _301.VersionParams;
            fromJSON(object: any): _301.VersionParams;
            toJSON(message: _301.VersionParams): unknown;
            fromPartial(object: Partial<_301.VersionParams>): _301.VersionParams;
            fromAmino(object: _301.VersionParamsAmino): _301.VersionParams;
            toAmino(message: _301.VersionParams): _301.VersionParamsAmino;
            fromAminoMsg(object: _301.VersionParamsAminoMsg): _301.VersionParams;
            fromProtoMsg(message: _301.VersionParamsProtoMsg): _301.VersionParams;
            toProto(message: _301.VersionParams): Uint8Array;
            toProtoMsg(message: _301.VersionParams): _301.VersionParamsProtoMsg;
        };
        HashedParams: {
            encode(message: _301.HashedParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _301.HashedParams;
            fromJSON(object: any): _301.HashedParams;
            toJSON(message: _301.HashedParams): unknown;
            fromPartial(object: Partial<_301.HashedParams>): _301.HashedParams;
            fromAmino(object: _301.HashedParamsAmino): _301.HashedParams;
            toAmino(message: _301.HashedParams): _301.HashedParamsAmino;
            fromAminoMsg(object: _301.HashedParamsAminoMsg): _301.HashedParams;
            fromProtoMsg(message: _301.HashedParamsProtoMsg): _301.HashedParams;
            toProto(message: _301.HashedParams): Uint8Array;
            toProtoMsg(message: _301.HashedParams): _301.HashedParamsProtoMsg;
        };
        Evidence: {
            encode(message: _300.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _300.Evidence;
            fromJSON(object: any): _300.Evidence;
            toJSON(message: _300.Evidence): unknown;
            fromPartial(object: Partial<_300.Evidence>): _300.Evidence;
            fromAmino(object: _300.EvidenceAmino): _300.Evidence;
            toAmino(message: _300.Evidence): _300.EvidenceAmino;
            fromAminoMsg(object: _300.EvidenceAminoMsg): _300.Evidence;
            fromProtoMsg(message: _300.EvidenceProtoMsg): _300.Evidence;
            toProto(message: _300.Evidence): Uint8Array;
            toProtoMsg(message: _300.Evidence): _300.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            encode(message: _300.DuplicateVoteEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _300.DuplicateVoteEvidence;
            fromJSON(object: any): _300.DuplicateVoteEvidence;
            toJSON(message: _300.DuplicateVoteEvidence): unknown;
            fromPartial(object: Partial<_300.DuplicateVoteEvidence>): _300.DuplicateVoteEvidence;
            fromAmino(object: _300.DuplicateVoteEvidenceAmino): _300.DuplicateVoteEvidence;
            toAmino(message: _300.DuplicateVoteEvidence): _300.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _300.DuplicateVoteEvidenceAminoMsg): _300.DuplicateVoteEvidence;
            fromProtoMsg(message: _300.DuplicateVoteEvidenceProtoMsg): _300.DuplicateVoteEvidence;
            toProto(message: _300.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _300.DuplicateVoteEvidence): _300.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            encode(message: _300.LightClientAttackEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _300.LightClientAttackEvidence;
            fromJSON(object: any): _300.LightClientAttackEvidence;
            toJSON(message: _300.LightClientAttackEvidence): unknown;
            fromPartial(object: Partial<_300.LightClientAttackEvidence>): _300.LightClientAttackEvidence;
            fromAmino(object: _300.LightClientAttackEvidenceAmino): _300.LightClientAttackEvidence;
            toAmino(message: _300.LightClientAttackEvidence): _300.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _300.LightClientAttackEvidenceAminoMsg): _300.LightClientAttackEvidence;
            fromProtoMsg(message: _300.LightClientAttackEvidenceProtoMsg): _300.LightClientAttackEvidence;
            toProto(message: _300.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _300.LightClientAttackEvidence): _300.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            encode(message: _300.EvidenceList, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _300.EvidenceList;
            fromJSON(object: any): _300.EvidenceList;
            toJSON(message: _300.EvidenceList): unknown;
            fromPartial(object: Partial<_300.EvidenceList>): _300.EvidenceList;
            fromAmino(object: _300.EvidenceListAmino): _300.EvidenceList;
            toAmino(message: _300.EvidenceList): _300.EvidenceListAmino;
            fromAminoMsg(object: _300.EvidenceListAminoMsg): _300.EvidenceList;
            fromProtoMsg(message: _300.EvidenceListProtoMsg): _300.EvidenceList;
            toProto(message: _300.EvidenceList): Uint8Array;
            toProtoMsg(message: _300.EvidenceList): _300.EvidenceListProtoMsg;
        };
        Block: {
            encode(message: _299.Block, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _299.Block;
            fromJSON(object: any): _299.Block;
            toJSON(message: _299.Block): unknown;
            fromPartial(object: Partial<_299.Block>): _299.Block;
            fromAmino(object: _299.BlockAmino): _299.Block;
            toAmino(message: _299.Block): _299.BlockAmino;
            fromAminoMsg(object: _299.BlockAminoMsg): _299.Block;
            fromProtoMsg(message: _299.BlockProtoMsg): _299.Block;
            toProto(message: _299.Block): Uint8Array;
            toProtoMsg(message: _299.Block): _299.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            encode(message: _304.App, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _304.App;
            fromJSON(object: any): _304.App;
            toJSON(message: _304.App): unknown;
            fromPartial(object: Partial<_304.App>): _304.App;
            fromAmino(object: _304.AppAmino): _304.App;
            toAmino(message: _304.App): _304.AppAmino;
            fromAminoMsg(object: _304.AppAminoMsg): _304.App;
            fromProtoMsg(message: _304.AppProtoMsg): _304.App;
            toProto(message: _304.App): Uint8Array;
            toProtoMsg(message: _304.App): _304.AppProtoMsg;
        };
        Consensus: {
            encode(message: _304.Consensus, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _304.Consensus;
            fromJSON(object: any): _304.Consensus;
            toJSON(message: _304.Consensus): unknown;
            fromPartial(object: Partial<_304.Consensus>): _304.Consensus;
            fromAmino(object: _304.ConsensusAmino): _304.Consensus;
            toAmino(message: _304.Consensus): _304.ConsensusAmino;
            fromAminoMsg(object: _304.ConsensusAminoMsg): _304.Consensus;
            fromProtoMsg(message: _304.ConsensusProtoMsg): _304.Consensus;
            toProto(message: _304.Consensus): Uint8Array;
            toProtoMsg(message: _304.Consensus): _304.ConsensusProtoMsg;
        };
    };
}
