import * as _285 from "./abci/types";
import * as _286 from "./crypto/keys";
import * as _287 from "./crypto/proof";
import * as _288 from "./libs/bits/types";
import * as _289 from "./p2p/types";
import * as _290 from "./types/block";
import * as _291 from "./types/evidence";
import * as _292 from "./types/params";
import * as _293 from "./types/types";
import * as _294 from "./types/validator";
import * as _295 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _285.CheckTxType;
        checkTxTypeToJSON(object: _285.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _285.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _285.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _285.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _285.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _285.EvidenceType;
        evidenceTypeToJSON(object: _285.EvidenceType): string;
        CheckTxType: typeof _285.CheckTxType;
        CheckTxTypeSDKType: typeof _285.CheckTxType;
        CheckTxTypeAmino: typeof _285.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _285.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _285.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _285.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _285.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _285.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _285.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _285.EvidenceType;
        EvidenceTypeSDKType: typeof _285.EvidenceType;
        EvidenceTypeAmino: typeof _285.EvidenceType;
        Request: {
            encode(message: _285.Request, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.Request;
            fromJSON(object: any): _285.Request;
            toJSON(message: _285.Request): unknown;
            fromPartial(object: Partial<_285.Request>): _285.Request;
            fromAmino(object: _285.RequestAmino): _285.Request;
            toAmino(message: _285.Request): _285.RequestAmino;
            fromAminoMsg(object: _285.RequestAminoMsg): _285.Request;
            fromProtoMsg(message: _285.RequestProtoMsg): _285.Request;
            toProto(message: _285.Request): Uint8Array;
            toProtoMsg(message: _285.Request): _285.RequestProtoMsg;
        };
        RequestEcho: {
            encode(message: _285.RequestEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestEcho;
            fromJSON(object: any): _285.RequestEcho;
            toJSON(message: _285.RequestEcho): unknown;
            fromPartial(object: Partial<_285.RequestEcho>): _285.RequestEcho;
            fromAmino(object: _285.RequestEchoAmino): _285.RequestEcho;
            toAmino(message: _285.RequestEcho): _285.RequestEchoAmino;
            fromAminoMsg(object: _285.RequestEchoAminoMsg): _285.RequestEcho;
            fromProtoMsg(message: _285.RequestEchoProtoMsg): _285.RequestEcho;
            toProto(message: _285.RequestEcho): Uint8Array;
            toProtoMsg(message: _285.RequestEcho): _285.RequestEchoProtoMsg;
        };
        RequestFlush: {
            encode(_: _285.RequestFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestFlush;
            fromJSON(_: any): _285.RequestFlush;
            toJSON(_: _285.RequestFlush): unknown;
            fromPartial(_: Partial<_285.RequestFlush>): _285.RequestFlush;
            fromAmino(_: _285.RequestFlushAmino): _285.RequestFlush;
            toAmino(_: _285.RequestFlush): _285.RequestFlushAmino;
            fromAminoMsg(object: _285.RequestFlushAminoMsg): _285.RequestFlush;
            fromProtoMsg(message: _285.RequestFlushProtoMsg): _285.RequestFlush;
            toProto(message: _285.RequestFlush): Uint8Array;
            toProtoMsg(message: _285.RequestFlush): _285.RequestFlushProtoMsg;
        };
        RequestInfo: {
            encode(message: _285.RequestInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestInfo;
            fromJSON(object: any): _285.RequestInfo;
            toJSON(message: _285.RequestInfo): unknown;
            fromPartial(object: Partial<_285.RequestInfo>): _285.RequestInfo;
            fromAmino(object: _285.RequestInfoAmino): _285.RequestInfo;
            toAmino(message: _285.RequestInfo): _285.RequestInfoAmino;
            fromAminoMsg(object: _285.RequestInfoAminoMsg): _285.RequestInfo;
            fromProtoMsg(message: _285.RequestInfoProtoMsg): _285.RequestInfo;
            toProto(message: _285.RequestInfo): Uint8Array;
            toProtoMsg(message: _285.RequestInfo): _285.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            encode(message: _285.RequestSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestSetOption;
            fromJSON(object: any): _285.RequestSetOption;
            toJSON(message: _285.RequestSetOption): unknown;
            fromPartial(object: Partial<_285.RequestSetOption>): _285.RequestSetOption;
            fromAmino(object: _285.RequestSetOptionAmino): _285.RequestSetOption;
            toAmino(message: _285.RequestSetOption): _285.RequestSetOptionAmino;
            fromAminoMsg(object: _285.RequestSetOptionAminoMsg): _285.RequestSetOption;
            fromProtoMsg(message: _285.RequestSetOptionProtoMsg): _285.RequestSetOption;
            toProto(message: _285.RequestSetOption): Uint8Array;
            toProtoMsg(message: _285.RequestSetOption): _285.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            encode(message: _285.RequestInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestInitChain;
            fromJSON(object: any): _285.RequestInitChain;
            toJSON(message: _285.RequestInitChain): unknown;
            fromPartial(object: Partial<_285.RequestInitChain>): _285.RequestInitChain;
            fromAmino(object: _285.RequestInitChainAmino): _285.RequestInitChain;
            toAmino(message: _285.RequestInitChain): _285.RequestInitChainAmino;
            fromAminoMsg(object: _285.RequestInitChainAminoMsg): _285.RequestInitChain;
            fromProtoMsg(message: _285.RequestInitChainProtoMsg): _285.RequestInitChain;
            toProto(message: _285.RequestInitChain): Uint8Array;
            toProtoMsg(message: _285.RequestInitChain): _285.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            encode(message: _285.RequestQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestQuery;
            fromJSON(object: any): _285.RequestQuery;
            toJSON(message: _285.RequestQuery): unknown;
            fromPartial(object: Partial<_285.RequestQuery>): _285.RequestQuery;
            fromAmino(object: _285.RequestQueryAmino): _285.RequestQuery;
            toAmino(message: _285.RequestQuery): _285.RequestQueryAmino;
            fromAminoMsg(object: _285.RequestQueryAminoMsg): _285.RequestQuery;
            fromProtoMsg(message: _285.RequestQueryProtoMsg): _285.RequestQuery;
            toProto(message: _285.RequestQuery): Uint8Array;
            toProtoMsg(message: _285.RequestQuery): _285.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            encode(message: _285.RequestBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestBeginBlock;
            fromJSON(object: any): _285.RequestBeginBlock;
            toJSON(message: _285.RequestBeginBlock): unknown;
            fromPartial(object: Partial<_285.RequestBeginBlock>): _285.RequestBeginBlock;
            fromAmino(object: _285.RequestBeginBlockAmino): _285.RequestBeginBlock;
            toAmino(message: _285.RequestBeginBlock): _285.RequestBeginBlockAmino;
            fromAminoMsg(object: _285.RequestBeginBlockAminoMsg): _285.RequestBeginBlock;
            fromProtoMsg(message: _285.RequestBeginBlockProtoMsg): _285.RequestBeginBlock;
            toProto(message: _285.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _285.RequestBeginBlock): _285.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            encode(message: _285.RequestCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestCheckTx;
            fromJSON(object: any): _285.RequestCheckTx;
            toJSON(message: _285.RequestCheckTx): unknown;
            fromPartial(object: Partial<_285.RequestCheckTx>): _285.RequestCheckTx;
            fromAmino(object: _285.RequestCheckTxAmino): _285.RequestCheckTx;
            toAmino(message: _285.RequestCheckTx): _285.RequestCheckTxAmino;
            fromAminoMsg(object: _285.RequestCheckTxAminoMsg): _285.RequestCheckTx;
            fromProtoMsg(message: _285.RequestCheckTxProtoMsg): _285.RequestCheckTx;
            toProto(message: _285.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _285.RequestCheckTx): _285.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            encode(message: _285.RequestDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestDeliverTx;
            fromJSON(object: any): _285.RequestDeliverTx;
            toJSON(message: _285.RequestDeliverTx): unknown;
            fromPartial(object: Partial<_285.RequestDeliverTx>): _285.RequestDeliverTx;
            fromAmino(object: _285.RequestDeliverTxAmino): _285.RequestDeliverTx;
            toAmino(message: _285.RequestDeliverTx): _285.RequestDeliverTxAmino;
            fromAminoMsg(object: _285.RequestDeliverTxAminoMsg): _285.RequestDeliverTx;
            fromProtoMsg(message: _285.RequestDeliverTxProtoMsg): _285.RequestDeliverTx;
            toProto(message: _285.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _285.RequestDeliverTx): _285.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            encode(message: _285.RequestEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestEndBlock;
            fromJSON(object: any): _285.RequestEndBlock;
            toJSON(message: _285.RequestEndBlock): unknown;
            fromPartial(object: Partial<_285.RequestEndBlock>): _285.RequestEndBlock;
            fromAmino(object: _285.RequestEndBlockAmino): _285.RequestEndBlock;
            toAmino(message: _285.RequestEndBlock): _285.RequestEndBlockAmino;
            fromAminoMsg(object: _285.RequestEndBlockAminoMsg): _285.RequestEndBlock;
            fromProtoMsg(message: _285.RequestEndBlockProtoMsg): _285.RequestEndBlock;
            toProto(message: _285.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _285.RequestEndBlock): _285.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            encode(_: _285.RequestCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestCommit;
            fromJSON(_: any): _285.RequestCommit;
            toJSON(_: _285.RequestCommit): unknown;
            fromPartial(_: Partial<_285.RequestCommit>): _285.RequestCommit;
            fromAmino(_: _285.RequestCommitAmino): _285.RequestCommit;
            toAmino(_: _285.RequestCommit): _285.RequestCommitAmino;
            fromAminoMsg(object: _285.RequestCommitAminoMsg): _285.RequestCommit;
            fromProtoMsg(message: _285.RequestCommitProtoMsg): _285.RequestCommit;
            toProto(message: _285.RequestCommit): Uint8Array;
            toProtoMsg(message: _285.RequestCommit): _285.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            encode(_: _285.RequestListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestListSnapshots;
            fromJSON(_: any): _285.RequestListSnapshots;
            toJSON(_: _285.RequestListSnapshots): unknown;
            fromPartial(_: Partial<_285.RequestListSnapshots>): _285.RequestListSnapshots;
            fromAmino(_: _285.RequestListSnapshotsAmino): _285.RequestListSnapshots;
            toAmino(_: _285.RequestListSnapshots): _285.RequestListSnapshotsAmino;
            fromAminoMsg(object: _285.RequestListSnapshotsAminoMsg): _285.RequestListSnapshots;
            fromProtoMsg(message: _285.RequestListSnapshotsProtoMsg): _285.RequestListSnapshots;
            toProto(message: _285.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _285.RequestListSnapshots): _285.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            encode(message: _285.RequestOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestOfferSnapshot;
            fromJSON(object: any): _285.RequestOfferSnapshot;
            toJSON(message: _285.RequestOfferSnapshot): unknown;
            fromPartial(object: Partial<_285.RequestOfferSnapshot>): _285.RequestOfferSnapshot;
            fromAmino(object: _285.RequestOfferSnapshotAmino): _285.RequestOfferSnapshot;
            toAmino(message: _285.RequestOfferSnapshot): _285.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _285.RequestOfferSnapshotAminoMsg): _285.RequestOfferSnapshot;
            fromProtoMsg(message: _285.RequestOfferSnapshotProtoMsg): _285.RequestOfferSnapshot;
            toProto(message: _285.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _285.RequestOfferSnapshot): _285.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            encode(message: _285.RequestLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestLoadSnapshotChunk;
            fromJSON(object: any): _285.RequestLoadSnapshotChunk;
            toJSON(message: _285.RequestLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_285.RequestLoadSnapshotChunk>): _285.RequestLoadSnapshotChunk;
            fromAmino(object: _285.RequestLoadSnapshotChunkAmino): _285.RequestLoadSnapshotChunk;
            toAmino(message: _285.RequestLoadSnapshotChunk): _285.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _285.RequestLoadSnapshotChunkAminoMsg): _285.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _285.RequestLoadSnapshotChunkProtoMsg): _285.RequestLoadSnapshotChunk;
            toProto(message: _285.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _285.RequestLoadSnapshotChunk): _285.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            encode(message: _285.RequestApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.RequestApplySnapshotChunk;
            fromJSON(object: any): _285.RequestApplySnapshotChunk;
            toJSON(message: _285.RequestApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_285.RequestApplySnapshotChunk>): _285.RequestApplySnapshotChunk;
            fromAmino(object: _285.RequestApplySnapshotChunkAmino): _285.RequestApplySnapshotChunk;
            toAmino(message: _285.RequestApplySnapshotChunk): _285.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _285.RequestApplySnapshotChunkAminoMsg): _285.RequestApplySnapshotChunk;
            fromProtoMsg(message: _285.RequestApplySnapshotChunkProtoMsg): _285.RequestApplySnapshotChunk;
            toProto(message: _285.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _285.RequestApplySnapshotChunk): _285.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            encode(message: _285.Response, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.Response;
            fromJSON(object: any): _285.Response;
            toJSON(message: _285.Response): unknown;
            fromPartial(object: Partial<_285.Response>): _285.Response;
            fromAmino(object: _285.ResponseAmino): _285.Response;
            toAmino(message: _285.Response): _285.ResponseAmino;
            fromAminoMsg(object: _285.ResponseAminoMsg): _285.Response;
            fromProtoMsg(message: _285.ResponseProtoMsg): _285.Response;
            toProto(message: _285.Response): Uint8Array;
            toProtoMsg(message: _285.Response): _285.ResponseProtoMsg;
        };
        ResponseException: {
            encode(message: _285.ResponseException, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseException;
            fromJSON(object: any): _285.ResponseException;
            toJSON(message: _285.ResponseException): unknown;
            fromPartial(object: Partial<_285.ResponseException>): _285.ResponseException;
            fromAmino(object: _285.ResponseExceptionAmino): _285.ResponseException;
            toAmino(message: _285.ResponseException): _285.ResponseExceptionAmino;
            fromAminoMsg(object: _285.ResponseExceptionAminoMsg): _285.ResponseException;
            fromProtoMsg(message: _285.ResponseExceptionProtoMsg): _285.ResponseException;
            toProto(message: _285.ResponseException): Uint8Array;
            toProtoMsg(message: _285.ResponseException): _285.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            encode(message: _285.ResponseEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseEcho;
            fromJSON(object: any): _285.ResponseEcho;
            toJSON(message: _285.ResponseEcho): unknown;
            fromPartial(object: Partial<_285.ResponseEcho>): _285.ResponseEcho;
            fromAmino(object: _285.ResponseEchoAmino): _285.ResponseEcho;
            toAmino(message: _285.ResponseEcho): _285.ResponseEchoAmino;
            fromAminoMsg(object: _285.ResponseEchoAminoMsg): _285.ResponseEcho;
            fromProtoMsg(message: _285.ResponseEchoProtoMsg): _285.ResponseEcho;
            toProto(message: _285.ResponseEcho): Uint8Array;
            toProtoMsg(message: _285.ResponseEcho): _285.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            encode(_: _285.ResponseFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseFlush;
            fromJSON(_: any): _285.ResponseFlush;
            toJSON(_: _285.ResponseFlush): unknown;
            fromPartial(_: Partial<_285.ResponseFlush>): _285.ResponseFlush;
            fromAmino(_: _285.ResponseFlushAmino): _285.ResponseFlush;
            toAmino(_: _285.ResponseFlush): _285.ResponseFlushAmino;
            fromAminoMsg(object: _285.ResponseFlushAminoMsg): _285.ResponseFlush;
            fromProtoMsg(message: _285.ResponseFlushProtoMsg): _285.ResponseFlush;
            toProto(message: _285.ResponseFlush): Uint8Array;
            toProtoMsg(message: _285.ResponseFlush): _285.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            encode(message: _285.ResponseInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseInfo;
            fromJSON(object: any): _285.ResponseInfo;
            toJSON(message: _285.ResponseInfo): unknown;
            fromPartial(object: Partial<_285.ResponseInfo>): _285.ResponseInfo;
            fromAmino(object: _285.ResponseInfoAmino): _285.ResponseInfo;
            toAmino(message: _285.ResponseInfo): _285.ResponseInfoAmino;
            fromAminoMsg(object: _285.ResponseInfoAminoMsg): _285.ResponseInfo;
            fromProtoMsg(message: _285.ResponseInfoProtoMsg): _285.ResponseInfo;
            toProto(message: _285.ResponseInfo): Uint8Array;
            toProtoMsg(message: _285.ResponseInfo): _285.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            encode(message: _285.ResponseSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseSetOption;
            fromJSON(object: any): _285.ResponseSetOption;
            toJSON(message: _285.ResponseSetOption): unknown;
            fromPartial(object: Partial<_285.ResponseSetOption>): _285.ResponseSetOption;
            fromAmino(object: _285.ResponseSetOptionAmino): _285.ResponseSetOption;
            toAmino(message: _285.ResponseSetOption): _285.ResponseSetOptionAmino;
            fromAminoMsg(object: _285.ResponseSetOptionAminoMsg): _285.ResponseSetOption;
            fromProtoMsg(message: _285.ResponseSetOptionProtoMsg): _285.ResponseSetOption;
            toProto(message: _285.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _285.ResponseSetOption): _285.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            encode(message: _285.ResponseInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseInitChain;
            fromJSON(object: any): _285.ResponseInitChain;
            toJSON(message: _285.ResponseInitChain): unknown;
            fromPartial(object: Partial<_285.ResponseInitChain>): _285.ResponseInitChain;
            fromAmino(object: _285.ResponseInitChainAmino): _285.ResponseInitChain;
            toAmino(message: _285.ResponseInitChain): _285.ResponseInitChainAmino;
            fromAminoMsg(object: _285.ResponseInitChainAminoMsg): _285.ResponseInitChain;
            fromProtoMsg(message: _285.ResponseInitChainProtoMsg): _285.ResponseInitChain;
            toProto(message: _285.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _285.ResponseInitChain): _285.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            encode(message: _285.ResponseQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseQuery;
            fromJSON(object: any): _285.ResponseQuery;
            toJSON(message: _285.ResponseQuery): unknown;
            fromPartial(object: Partial<_285.ResponseQuery>): _285.ResponseQuery;
            fromAmino(object: _285.ResponseQueryAmino): _285.ResponseQuery;
            toAmino(message: _285.ResponseQuery): _285.ResponseQueryAmino;
            fromAminoMsg(object: _285.ResponseQueryAminoMsg): _285.ResponseQuery;
            fromProtoMsg(message: _285.ResponseQueryProtoMsg): _285.ResponseQuery;
            toProto(message: _285.ResponseQuery): Uint8Array;
            toProtoMsg(message: _285.ResponseQuery): _285.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            encode(message: _285.ResponseBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseBeginBlock;
            fromJSON(object: any): _285.ResponseBeginBlock;
            toJSON(message: _285.ResponseBeginBlock): unknown;
            fromPartial(object: Partial<_285.ResponseBeginBlock>): _285.ResponseBeginBlock;
            fromAmino(object: _285.ResponseBeginBlockAmino): _285.ResponseBeginBlock;
            toAmino(message: _285.ResponseBeginBlock): _285.ResponseBeginBlockAmino;
            fromAminoMsg(object: _285.ResponseBeginBlockAminoMsg): _285.ResponseBeginBlock;
            fromProtoMsg(message: _285.ResponseBeginBlockProtoMsg): _285.ResponseBeginBlock;
            toProto(message: _285.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _285.ResponseBeginBlock): _285.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            encode(message: _285.ResponseCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseCheckTx;
            fromJSON(object: any): _285.ResponseCheckTx;
            toJSON(message: _285.ResponseCheckTx): unknown;
            fromPartial(object: Partial<_285.ResponseCheckTx>): _285.ResponseCheckTx;
            fromAmino(object: _285.ResponseCheckTxAmino): _285.ResponseCheckTx;
            toAmino(message: _285.ResponseCheckTx): _285.ResponseCheckTxAmino;
            fromAminoMsg(object: _285.ResponseCheckTxAminoMsg): _285.ResponseCheckTx;
            fromProtoMsg(message: _285.ResponseCheckTxProtoMsg): _285.ResponseCheckTx;
            toProto(message: _285.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _285.ResponseCheckTx): _285.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            encode(message: _285.ResponseDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseDeliverTx;
            fromJSON(object: any): _285.ResponseDeliverTx;
            toJSON(message: _285.ResponseDeliverTx): unknown;
            fromPartial(object: Partial<_285.ResponseDeliverTx>): _285.ResponseDeliverTx;
            fromAmino(object: _285.ResponseDeliverTxAmino): _285.ResponseDeliverTx;
            toAmino(message: _285.ResponseDeliverTx): _285.ResponseDeliverTxAmino;
            fromAminoMsg(object: _285.ResponseDeliverTxAminoMsg): _285.ResponseDeliverTx;
            fromProtoMsg(message: _285.ResponseDeliverTxProtoMsg): _285.ResponseDeliverTx;
            toProto(message: _285.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _285.ResponseDeliverTx): _285.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            encode(message: _285.ResponseEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseEndBlock;
            fromJSON(object: any): _285.ResponseEndBlock;
            toJSON(message: _285.ResponseEndBlock): unknown;
            fromPartial(object: Partial<_285.ResponseEndBlock>): _285.ResponseEndBlock;
            fromAmino(object: _285.ResponseEndBlockAmino): _285.ResponseEndBlock;
            toAmino(message: _285.ResponseEndBlock): _285.ResponseEndBlockAmino;
            fromAminoMsg(object: _285.ResponseEndBlockAminoMsg): _285.ResponseEndBlock;
            fromProtoMsg(message: _285.ResponseEndBlockProtoMsg): _285.ResponseEndBlock;
            toProto(message: _285.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _285.ResponseEndBlock): _285.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            encode(message: _285.ResponseCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseCommit;
            fromJSON(object: any): _285.ResponseCommit;
            toJSON(message: _285.ResponseCommit): unknown;
            fromPartial(object: Partial<_285.ResponseCommit>): _285.ResponseCommit;
            fromAmino(object: _285.ResponseCommitAmino): _285.ResponseCommit;
            toAmino(message: _285.ResponseCommit): _285.ResponseCommitAmino;
            fromAminoMsg(object: _285.ResponseCommitAminoMsg): _285.ResponseCommit;
            fromProtoMsg(message: _285.ResponseCommitProtoMsg): _285.ResponseCommit;
            toProto(message: _285.ResponseCommit): Uint8Array;
            toProtoMsg(message: _285.ResponseCommit): _285.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            encode(message: _285.ResponseListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseListSnapshots;
            fromJSON(object: any): _285.ResponseListSnapshots;
            toJSON(message: _285.ResponseListSnapshots): unknown;
            fromPartial(object: Partial<_285.ResponseListSnapshots>): _285.ResponseListSnapshots;
            fromAmino(object: _285.ResponseListSnapshotsAmino): _285.ResponseListSnapshots;
            toAmino(message: _285.ResponseListSnapshots): _285.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _285.ResponseListSnapshotsAminoMsg): _285.ResponseListSnapshots;
            fromProtoMsg(message: _285.ResponseListSnapshotsProtoMsg): _285.ResponseListSnapshots;
            toProto(message: _285.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _285.ResponseListSnapshots): _285.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            encode(message: _285.ResponseOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseOfferSnapshot;
            fromJSON(object: any): _285.ResponseOfferSnapshot;
            toJSON(message: _285.ResponseOfferSnapshot): unknown;
            fromPartial(object: Partial<_285.ResponseOfferSnapshot>): _285.ResponseOfferSnapshot;
            fromAmino(object: _285.ResponseOfferSnapshotAmino): _285.ResponseOfferSnapshot;
            toAmino(message: _285.ResponseOfferSnapshot): _285.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _285.ResponseOfferSnapshotAminoMsg): _285.ResponseOfferSnapshot;
            fromProtoMsg(message: _285.ResponseOfferSnapshotProtoMsg): _285.ResponseOfferSnapshot;
            toProto(message: _285.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _285.ResponseOfferSnapshot): _285.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            encode(message: _285.ResponseLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseLoadSnapshotChunk;
            fromJSON(object: any): _285.ResponseLoadSnapshotChunk;
            toJSON(message: _285.ResponseLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_285.ResponseLoadSnapshotChunk>): _285.ResponseLoadSnapshotChunk;
            fromAmino(object: _285.ResponseLoadSnapshotChunkAmino): _285.ResponseLoadSnapshotChunk;
            toAmino(message: _285.ResponseLoadSnapshotChunk): _285.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _285.ResponseLoadSnapshotChunkAminoMsg): _285.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _285.ResponseLoadSnapshotChunkProtoMsg): _285.ResponseLoadSnapshotChunk;
            toProto(message: _285.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _285.ResponseLoadSnapshotChunk): _285.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            encode(message: _285.ResponseApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ResponseApplySnapshotChunk;
            fromJSON(object: any): _285.ResponseApplySnapshotChunk;
            toJSON(message: _285.ResponseApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_285.ResponseApplySnapshotChunk>): _285.ResponseApplySnapshotChunk;
            fromAmino(object: _285.ResponseApplySnapshotChunkAmino): _285.ResponseApplySnapshotChunk;
            toAmino(message: _285.ResponseApplySnapshotChunk): _285.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _285.ResponseApplySnapshotChunkAminoMsg): _285.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _285.ResponseApplySnapshotChunkProtoMsg): _285.ResponseApplySnapshotChunk;
            toProto(message: _285.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _285.ResponseApplySnapshotChunk): _285.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            encode(message: _285.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ConsensusParams;
            fromJSON(object: any): _285.ConsensusParams;
            toJSON(message: _285.ConsensusParams): unknown;
            fromPartial(object: Partial<_285.ConsensusParams>): _285.ConsensusParams;
            fromAmino(object: _285.ConsensusParamsAmino): _285.ConsensusParams;
            toAmino(message: _285.ConsensusParams): _285.ConsensusParamsAmino;
            fromAminoMsg(object: _285.ConsensusParamsAminoMsg): _285.ConsensusParams;
            fromProtoMsg(message: _285.ConsensusParamsProtoMsg): _285.ConsensusParams;
            toProto(message: _285.ConsensusParams): Uint8Array;
            toProtoMsg(message: _285.ConsensusParams): _285.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _285.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.BlockParams;
            fromJSON(object: any): _285.BlockParams;
            toJSON(message: _285.BlockParams): unknown;
            fromPartial(object: Partial<_285.BlockParams>): _285.BlockParams;
            fromAmino(object: _285.BlockParamsAmino): _285.BlockParams;
            toAmino(message: _285.BlockParams): _285.BlockParamsAmino;
            fromAminoMsg(object: _285.BlockParamsAminoMsg): _285.BlockParams;
            fromProtoMsg(message: _285.BlockParamsProtoMsg): _285.BlockParams;
            toProto(message: _285.BlockParams): Uint8Array;
            toProtoMsg(message: _285.BlockParams): _285.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            encode(message: _285.LastCommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.LastCommitInfo;
            fromJSON(object: any): _285.LastCommitInfo;
            toJSON(message: _285.LastCommitInfo): unknown;
            fromPartial(object: Partial<_285.LastCommitInfo>): _285.LastCommitInfo;
            fromAmino(object: _285.LastCommitInfoAmino): _285.LastCommitInfo;
            toAmino(message: _285.LastCommitInfo): _285.LastCommitInfoAmino;
            fromAminoMsg(object: _285.LastCommitInfoAminoMsg): _285.LastCommitInfo;
            fromProtoMsg(message: _285.LastCommitInfoProtoMsg): _285.LastCommitInfo;
            toProto(message: _285.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _285.LastCommitInfo): _285.LastCommitInfoProtoMsg;
        };
        Event: {
            encode(message: _285.Event, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.Event;
            fromJSON(object: any): _285.Event;
            toJSON(message: _285.Event): unknown;
            fromPartial(object: Partial<_285.Event>): _285.Event;
            fromAmino(object: _285.EventAmino): _285.Event;
            toAmino(message: _285.Event): _285.EventAmino;
            fromAminoMsg(object: _285.EventAminoMsg): _285.Event;
            fromProtoMsg(message: _285.EventProtoMsg): _285.Event;
            toProto(message: _285.Event): Uint8Array;
            toProtoMsg(message: _285.Event): _285.EventProtoMsg;
        };
        EventAttribute: {
            encode(message: _285.EventAttribute, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.EventAttribute;
            fromJSON(object: any): _285.EventAttribute;
            toJSON(message: _285.EventAttribute): unknown;
            fromPartial(object: Partial<_285.EventAttribute>): _285.EventAttribute;
            fromAmino(object: _285.EventAttributeAmino): _285.EventAttribute;
            toAmino(message: _285.EventAttribute): _285.EventAttributeAmino;
            fromAminoMsg(object: _285.EventAttributeAminoMsg): _285.EventAttribute;
            fromProtoMsg(message: _285.EventAttributeProtoMsg): _285.EventAttribute;
            toProto(message: _285.EventAttribute): Uint8Array;
            toProtoMsg(message: _285.EventAttribute): _285.EventAttributeProtoMsg;
        };
        TxResult: {
            encode(message: _285.TxResult, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.TxResult;
            fromJSON(object: any): _285.TxResult;
            toJSON(message: _285.TxResult): unknown;
            fromPartial(object: Partial<_285.TxResult>): _285.TxResult;
            fromAmino(object: _285.TxResultAmino): _285.TxResult;
            toAmino(message: _285.TxResult): _285.TxResultAmino;
            fromAminoMsg(object: _285.TxResultAminoMsg): _285.TxResult;
            fromProtoMsg(message: _285.TxResultProtoMsg): _285.TxResult;
            toProto(message: _285.TxResult): Uint8Array;
            toProtoMsg(message: _285.TxResult): _285.TxResultProtoMsg;
        };
        Validator: {
            encode(message: _285.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.Validator;
            fromJSON(object: any): _285.Validator;
            toJSON(message: _285.Validator): unknown;
            fromPartial(object: Partial<_285.Validator>): _285.Validator;
            fromAmino(object: _285.ValidatorAmino): _285.Validator;
            toAmino(message: _285.Validator): _285.ValidatorAmino;
            fromAminoMsg(object: _285.ValidatorAminoMsg): _285.Validator;
            fromProtoMsg(message: _285.ValidatorProtoMsg): _285.Validator;
            toProto(message: _285.Validator): Uint8Array;
            toProtoMsg(message: _285.Validator): _285.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            encode(message: _285.ValidatorUpdate, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.ValidatorUpdate;
            fromJSON(object: any): _285.ValidatorUpdate;
            toJSON(message: _285.ValidatorUpdate): unknown;
            fromPartial(object: Partial<_285.ValidatorUpdate>): _285.ValidatorUpdate;
            fromAmino(object: _285.ValidatorUpdateAmino): _285.ValidatorUpdate;
            toAmino(message: _285.ValidatorUpdate): _285.ValidatorUpdateAmino;
            fromAminoMsg(object: _285.ValidatorUpdateAminoMsg): _285.ValidatorUpdate;
            fromProtoMsg(message: _285.ValidatorUpdateProtoMsg): _285.ValidatorUpdate;
            toProto(message: _285.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _285.ValidatorUpdate): _285.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            encode(message: _285.VoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.VoteInfo;
            fromJSON(object: any): _285.VoteInfo;
            toJSON(message: _285.VoteInfo): unknown;
            fromPartial(object: Partial<_285.VoteInfo>): _285.VoteInfo;
            fromAmino(object: _285.VoteInfoAmino): _285.VoteInfo;
            toAmino(message: _285.VoteInfo): _285.VoteInfoAmino;
            fromAminoMsg(object: _285.VoteInfoAminoMsg): _285.VoteInfo;
            fromProtoMsg(message: _285.VoteInfoProtoMsg): _285.VoteInfo;
            toProto(message: _285.VoteInfo): Uint8Array;
            toProtoMsg(message: _285.VoteInfo): _285.VoteInfoProtoMsg;
        };
        Evidence: {
            encode(message: _285.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.Evidence;
            fromJSON(object: any): _285.Evidence;
            toJSON(message: _285.Evidence): unknown;
            fromPartial(object: Partial<_285.Evidence>): _285.Evidence;
            fromAmino(object: _285.EvidenceAmino): _285.Evidence;
            toAmino(message: _285.Evidence): _285.EvidenceAmino;
            fromAminoMsg(object: _285.EvidenceAminoMsg): _285.Evidence;
            fromProtoMsg(message: _285.EvidenceProtoMsg): _285.Evidence;
            toProto(message: _285.Evidence): Uint8Array;
            toProtoMsg(message: _285.Evidence): _285.EvidenceProtoMsg;
        };
        Snapshot: {
            encode(message: _285.Snapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _285.Snapshot;
            fromJSON(object: any): _285.Snapshot;
            toJSON(message: _285.Snapshot): unknown;
            fromPartial(object: Partial<_285.Snapshot>): _285.Snapshot;
            fromAmino(object: _285.SnapshotAmino): _285.Snapshot;
            toAmino(message: _285.Snapshot): _285.SnapshotAmino;
            fromAminoMsg(object: _285.SnapshotAminoMsg): _285.Snapshot;
            fromProtoMsg(message: _285.SnapshotProtoMsg): _285.Snapshot;
            toProto(message: _285.Snapshot): Uint8Array;
            toProtoMsg(message: _285.Snapshot): _285.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            encode(message: _287.Proof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _287.Proof;
            fromJSON(object: any): _287.Proof;
            toJSON(message: _287.Proof): unknown;
            fromPartial(object: Partial<_287.Proof>): _287.Proof;
            fromAmino(object: _287.ProofAmino): _287.Proof;
            toAmino(message: _287.Proof): _287.ProofAmino;
            fromAminoMsg(object: _287.ProofAminoMsg): _287.Proof;
            fromProtoMsg(message: _287.ProofProtoMsg): _287.Proof;
            toProto(message: _287.Proof): Uint8Array;
            toProtoMsg(message: _287.Proof): _287.ProofProtoMsg;
        };
        ValueOp: {
            encode(message: _287.ValueOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _287.ValueOp;
            fromJSON(object: any): _287.ValueOp;
            toJSON(message: _287.ValueOp): unknown;
            fromPartial(object: Partial<_287.ValueOp>): _287.ValueOp;
            fromAmino(object: _287.ValueOpAmino): _287.ValueOp;
            toAmino(message: _287.ValueOp): _287.ValueOpAmino;
            fromAminoMsg(object: _287.ValueOpAminoMsg): _287.ValueOp;
            fromProtoMsg(message: _287.ValueOpProtoMsg): _287.ValueOp;
            toProto(message: _287.ValueOp): Uint8Array;
            toProtoMsg(message: _287.ValueOp): _287.ValueOpProtoMsg;
        };
        DominoOp: {
            encode(message: _287.DominoOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _287.DominoOp;
            fromJSON(object: any): _287.DominoOp;
            toJSON(message: _287.DominoOp): unknown;
            fromPartial(object: Partial<_287.DominoOp>): _287.DominoOp;
            fromAmino(object: _287.DominoOpAmino): _287.DominoOp;
            toAmino(message: _287.DominoOp): _287.DominoOpAmino;
            fromAminoMsg(object: _287.DominoOpAminoMsg): _287.DominoOp;
            fromProtoMsg(message: _287.DominoOpProtoMsg): _287.DominoOp;
            toProto(message: _287.DominoOp): Uint8Array;
            toProtoMsg(message: _287.DominoOp): _287.DominoOpProtoMsg;
        };
        ProofOp: {
            encode(message: _287.ProofOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _287.ProofOp;
            fromJSON(object: any): _287.ProofOp;
            toJSON(message: _287.ProofOp): unknown;
            fromPartial(object: Partial<_287.ProofOp>): _287.ProofOp;
            fromAmino(object: _287.ProofOpAmino): _287.ProofOp;
            toAmino(message: _287.ProofOp): _287.ProofOpAmino;
            fromAminoMsg(object: _287.ProofOpAminoMsg): _287.ProofOp;
            fromProtoMsg(message: _287.ProofOpProtoMsg): _287.ProofOp;
            toProto(message: _287.ProofOp): Uint8Array;
            toProtoMsg(message: _287.ProofOp): _287.ProofOpProtoMsg;
        };
        ProofOps: {
            encode(message: _287.ProofOps, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _287.ProofOps;
            fromJSON(object: any): _287.ProofOps;
            toJSON(message: _287.ProofOps): unknown;
            fromPartial(object: Partial<_287.ProofOps>): _287.ProofOps;
            fromAmino(object: _287.ProofOpsAmino): _287.ProofOps;
            toAmino(message: _287.ProofOps): _287.ProofOpsAmino;
            fromAminoMsg(object: _287.ProofOpsAminoMsg): _287.ProofOps;
            fromProtoMsg(message: _287.ProofOpsProtoMsg): _287.ProofOps;
            toProto(message: _287.ProofOps): Uint8Array;
            toProtoMsg(message: _287.ProofOps): _287.ProofOpsProtoMsg;
        };
        PublicKey: {
            encode(message: _286.PublicKey, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _286.PublicKey;
            fromJSON(object: any): _286.PublicKey;
            toJSON(message: _286.PublicKey): unknown;
            fromPartial(object: Partial<_286.PublicKey>): _286.PublicKey;
            fromAmino(object: _286.PublicKeyAmino): _286.PublicKey;
            toAmino(message: _286.PublicKey): _286.PublicKeyAmino;
            fromAminoMsg(object: _286.PublicKeyAminoMsg): _286.PublicKey;
            fromProtoMsg(message: _286.PublicKeyProtoMsg): _286.PublicKey;
            toProto(message: _286.PublicKey): Uint8Array;
            toProtoMsg(message: _286.PublicKey): _286.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                encode(message: _288.BitArray, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
                decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _288.BitArray;
                fromJSON(object: any): _288.BitArray;
                toJSON(message: _288.BitArray): unknown;
                fromPartial(object: Partial<_288.BitArray>): _288.BitArray;
                fromAmino(object: _288.BitArrayAmino): _288.BitArray;
                toAmino(message: _288.BitArray): _288.BitArrayAmino;
                fromAminoMsg(object: _288.BitArrayAminoMsg): _288.BitArray;
                fromProtoMsg(message: _288.BitArrayProtoMsg): _288.BitArray;
                toProto(message: _288.BitArray): Uint8Array;
                toProtoMsg(message: _288.BitArray): _288.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        ProtocolVersion: {
            encode(message: _289.ProtocolVersion, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _289.ProtocolVersion;
            fromJSON(object: any): _289.ProtocolVersion;
            toJSON(message: _289.ProtocolVersion): unknown;
            fromPartial(object: Partial<_289.ProtocolVersion>): _289.ProtocolVersion;
            fromAmino(object: _289.ProtocolVersionAmino): _289.ProtocolVersion;
            toAmino(message: _289.ProtocolVersion): _289.ProtocolVersionAmino;
            fromAminoMsg(object: _289.ProtocolVersionAminoMsg): _289.ProtocolVersion;
            fromProtoMsg(message: _289.ProtocolVersionProtoMsg): _289.ProtocolVersion;
            toProto(message: _289.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _289.ProtocolVersion): _289.ProtocolVersionProtoMsg;
        };
        NodeInfo: {
            encode(message: _289.NodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _289.NodeInfo;
            fromJSON(object: any): _289.NodeInfo;
            toJSON(message: _289.NodeInfo): unknown;
            fromPartial(object: Partial<_289.NodeInfo>): _289.NodeInfo;
            fromAmino(object: _289.NodeInfoAmino): _289.NodeInfo;
            toAmino(message: _289.NodeInfo): _289.NodeInfoAmino;
            fromAminoMsg(object: _289.NodeInfoAminoMsg): _289.NodeInfo;
            fromProtoMsg(message: _289.NodeInfoProtoMsg): _289.NodeInfo;
            toProto(message: _289.NodeInfo): Uint8Array;
            toProtoMsg(message: _289.NodeInfo): _289.NodeInfoProtoMsg;
        };
        NodeInfoOther: {
            encode(message: _289.NodeInfoOther, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _289.NodeInfoOther;
            fromJSON(object: any): _289.NodeInfoOther;
            toJSON(message: _289.NodeInfoOther): unknown;
            fromPartial(object: Partial<_289.NodeInfoOther>): _289.NodeInfoOther;
            fromAmino(object: _289.NodeInfoOtherAmino): _289.NodeInfoOther;
            toAmino(message: _289.NodeInfoOther): _289.NodeInfoOtherAmino;
            fromAminoMsg(object: _289.NodeInfoOtherAminoMsg): _289.NodeInfoOther;
            fromProtoMsg(message: _289.NodeInfoOtherProtoMsg): _289.NodeInfoOther;
            toProto(message: _289.NodeInfoOther): Uint8Array;
            toProtoMsg(message: _289.NodeInfoOther): _289.NodeInfoOtherProtoMsg;
        };
        PeerInfo: {
            encode(message: _289.PeerInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _289.PeerInfo;
            fromJSON(object: any): _289.PeerInfo;
            toJSON(message: _289.PeerInfo): unknown;
            fromPartial(object: Partial<_289.PeerInfo>): _289.PeerInfo;
            fromAmino(object: _289.PeerInfoAmino): _289.PeerInfo;
            toAmino(message: _289.PeerInfo): _289.PeerInfoAmino;
            fromAminoMsg(object: _289.PeerInfoAminoMsg): _289.PeerInfo;
            fromProtoMsg(message: _289.PeerInfoProtoMsg): _289.PeerInfo;
            toProto(message: _289.PeerInfo): Uint8Array;
            toProtoMsg(message: _289.PeerInfo): _289.PeerInfoProtoMsg;
        };
        PeerAddressInfo: {
            encode(message: _289.PeerAddressInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _289.PeerAddressInfo;
            fromJSON(object: any): _289.PeerAddressInfo;
            toJSON(message: _289.PeerAddressInfo): unknown;
            fromPartial(object: Partial<_289.PeerAddressInfo>): _289.PeerAddressInfo;
            fromAmino(object: _289.PeerAddressInfoAmino): _289.PeerAddressInfo;
            toAmino(message: _289.PeerAddressInfo): _289.PeerAddressInfoAmino;
            fromAminoMsg(object: _289.PeerAddressInfoAminoMsg): _289.PeerAddressInfo;
            fromProtoMsg(message: _289.PeerAddressInfoProtoMsg): _289.PeerAddressInfo;
            toProto(message: _289.PeerAddressInfo): Uint8Array;
            toProtoMsg(message: _289.PeerAddressInfo): _289.PeerAddressInfoProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            encode(message: _294.ValidatorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.ValidatorSet;
            fromJSON(object: any): _294.ValidatorSet;
            toJSON(message: _294.ValidatorSet): unknown;
            fromPartial(object: Partial<_294.ValidatorSet>): _294.ValidatorSet;
            fromAmino(object: _294.ValidatorSetAmino): _294.ValidatorSet;
            toAmino(message: _294.ValidatorSet): _294.ValidatorSetAmino;
            fromAminoMsg(object: _294.ValidatorSetAminoMsg): _294.ValidatorSet;
            fromProtoMsg(message: _294.ValidatorSetProtoMsg): _294.ValidatorSet;
            toProto(message: _294.ValidatorSet): Uint8Array;
            toProtoMsg(message: _294.ValidatorSet): _294.ValidatorSetProtoMsg;
        };
        Validator: {
            encode(message: _294.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.Validator;
            fromJSON(object: any): _294.Validator;
            toJSON(message: _294.Validator): unknown;
            fromPartial(object: Partial<_294.Validator>): _294.Validator;
            fromAmino(object: _294.ValidatorAmino): _294.Validator;
            toAmino(message: _294.Validator): _294.ValidatorAmino;
            fromAminoMsg(object: _294.ValidatorAminoMsg): _294.Validator;
            fromProtoMsg(message: _294.ValidatorProtoMsg): _294.Validator;
            toProto(message: _294.Validator): Uint8Array;
            toProtoMsg(message: _294.Validator): _294.ValidatorProtoMsg;
        };
        SimpleValidator: {
            encode(message: _294.SimpleValidator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _294.SimpleValidator;
            fromJSON(object: any): _294.SimpleValidator;
            toJSON(message: _294.SimpleValidator): unknown;
            fromPartial(object: Partial<_294.SimpleValidator>): _294.SimpleValidator;
            fromAmino(object: _294.SimpleValidatorAmino): _294.SimpleValidator;
            toAmino(message: _294.SimpleValidator): _294.SimpleValidatorAmino;
            fromAminoMsg(object: _294.SimpleValidatorAminoMsg): _294.SimpleValidator;
            fromProtoMsg(message: _294.SimpleValidatorProtoMsg): _294.SimpleValidator;
            toProto(message: _294.SimpleValidator): Uint8Array;
            toProtoMsg(message: _294.SimpleValidator): _294.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _293.BlockIDFlag;
        blockIDFlagToJSON(object: _293.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _293.SignedMsgType;
        signedMsgTypeToJSON(object: _293.SignedMsgType): string;
        BlockIDFlag: typeof _293.BlockIDFlag;
        BlockIDFlagSDKType: typeof _293.BlockIDFlag;
        BlockIDFlagAmino: typeof _293.BlockIDFlag;
        SignedMsgType: typeof _293.SignedMsgType;
        SignedMsgTypeSDKType: typeof _293.SignedMsgType;
        SignedMsgTypeAmino: typeof _293.SignedMsgType;
        PartSetHeader: {
            encode(message: _293.PartSetHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.PartSetHeader;
            fromJSON(object: any): _293.PartSetHeader;
            toJSON(message: _293.PartSetHeader): unknown;
            fromPartial(object: Partial<_293.PartSetHeader>): _293.PartSetHeader;
            fromAmino(object: _293.PartSetHeaderAmino): _293.PartSetHeader;
            toAmino(message: _293.PartSetHeader): _293.PartSetHeaderAmino;
            fromAminoMsg(object: _293.PartSetHeaderAminoMsg): _293.PartSetHeader;
            fromProtoMsg(message: _293.PartSetHeaderProtoMsg): _293.PartSetHeader;
            toProto(message: _293.PartSetHeader): Uint8Array;
            toProtoMsg(message: _293.PartSetHeader): _293.PartSetHeaderProtoMsg;
        };
        Part: {
            encode(message: _293.Part, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.Part;
            fromJSON(object: any): _293.Part;
            toJSON(message: _293.Part): unknown;
            fromPartial(object: Partial<_293.Part>): _293.Part;
            fromAmino(object: _293.PartAmino): _293.Part;
            toAmino(message: _293.Part): _293.PartAmino;
            fromAminoMsg(object: _293.PartAminoMsg): _293.Part;
            fromProtoMsg(message: _293.PartProtoMsg): _293.Part;
            toProto(message: _293.Part): Uint8Array;
            toProtoMsg(message: _293.Part): _293.PartProtoMsg;
        };
        BlockID: {
            encode(message: _293.BlockID, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.BlockID;
            fromJSON(object: any): _293.BlockID;
            toJSON(message: _293.BlockID): unknown;
            fromPartial(object: Partial<_293.BlockID>): _293.BlockID;
            fromAmino(object: _293.BlockIDAmino): _293.BlockID;
            toAmino(message: _293.BlockID): _293.BlockIDAmino;
            fromAminoMsg(object: _293.BlockIDAminoMsg): _293.BlockID;
            fromProtoMsg(message: _293.BlockIDProtoMsg): _293.BlockID;
            toProto(message: _293.BlockID): Uint8Array;
            toProtoMsg(message: _293.BlockID): _293.BlockIDProtoMsg;
        };
        Header: {
            encode(message: _293.Header, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.Header;
            fromJSON(object: any): _293.Header;
            toJSON(message: _293.Header): unknown;
            fromPartial(object: Partial<_293.Header>): _293.Header;
            fromAmino(object: _293.HeaderAmino): _293.Header;
            toAmino(message: _293.Header): _293.HeaderAmino;
            fromAminoMsg(object: _293.HeaderAminoMsg): _293.Header;
            fromProtoMsg(message: _293.HeaderProtoMsg): _293.Header;
            toProto(message: _293.Header): Uint8Array;
            toProtoMsg(message: _293.Header): _293.HeaderProtoMsg;
        };
        Data: {
            encode(message: _293.Data, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.Data;
            fromJSON(object: any): _293.Data;
            toJSON(message: _293.Data): unknown;
            fromPartial(object: Partial<_293.Data>): _293.Data;
            fromAmino(object: _293.DataAmino): _293.Data;
            toAmino(message: _293.Data): _293.DataAmino;
            fromAminoMsg(object: _293.DataAminoMsg): _293.Data;
            fromProtoMsg(message: _293.DataProtoMsg): _293.Data;
            toProto(message: _293.Data): Uint8Array;
            toProtoMsg(message: _293.Data): _293.DataProtoMsg;
        };
        Vote: {
            encode(message: _293.Vote, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.Vote;
            fromJSON(object: any): _293.Vote;
            toJSON(message: _293.Vote): unknown;
            fromPartial(object: Partial<_293.Vote>): _293.Vote;
            fromAmino(object: _293.VoteAmino): _293.Vote;
            toAmino(message: _293.Vote): _293.VoteAmino;
            fromAminoMsg(object: _293.VoteAminoMsg): _293.Vote;
            fromProtoMsg(message: _293.VoteProtoMsg): _293.Vote;
            toProto(message: _293.Vote): Uint8Array;
            toProtoMsg(message: _293.Vote): _293.VoteProtoMsg;
        };
        Commit: {
            encode(message: _293.Commit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.Commit;
            fromJSON(object: any): _293.Commit;
            toJSON(message: _293.Commit): unknown;
            fromPartial(object: Partial<_293.Commit>): _293.Commit;
            fromAmino(object: _293.CommitAmino): _293.Commit;
            toAmino(message: _293.Commit): _293.CommitAmino;
            fromAminoMsg(object: _293.CommitAminoMsg): _293.Commit;
            fromProtoMsg(message: _293.CommitProtoMsg): _293.Commit;
            toProto(message: _293.Commit): Uint8Array;
            toProtoMsg(message: _293.Commit): _293.CommitProtoMsg;
        };
        CommitSig: {
            encode(message: _293.CommitSig, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.CommitSig;
            fromJSON(object: any): _293.CommitSig;
            toJSON(message: _293.CommitSig): unknown;
            fromPartial(object: Partial<_293.CommitSig>): _293.CommitSig;
            fromAmino(object: _293.CommitSigAmino): _293.CommitSig;
            toAmino(message: _293.CommitSig): _293.CommitSigAmino;
            fromAminoMsg(object: _293.CommitSigAminoMsg): _293.CommitSig;
            fromProtoMsg(message: _293.CommitSigProtoMsg): _293.CommitSig;
            toProto(message: _293.CommitSig): Uint8Array;
            toProtoMsg(message: _293.CommitSig): _293.CommitSigProtoMsg;
        };
        Proposal: {
            encode(message: _293.Proposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.Proposal;
            fromJSON(object: any): _293.Proposal;
            toJSON(message: _293.Proposal): unknown;
            fromPartial(object: Partial<_293.Proposal>): _293.Proposal;
            fromAmino(object: _293.ProposalAmino): _293.Proposal;
            toAmino(message: _293.Proposal): _293.ProposalAmino;
            fromAminoMsg(object: _293.ProposalAminoMsg): _293.Proposal;
            fromProtoMsg(message: _293.ProposalProtoMsg): _293.Proposal;
            toProto(message: _293.Proposal): Uint8Array;
            toProtoMsg(message: _293.Proposal): _293.ProposalProtoMsg;
        };
        SignedHeader: {
            encode(message: _293.SignedHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.SignedHeader;
            fromJSON(object: any): _293.SignedHeader;
            toJSON(message: _293.SignedHeader): unknown;
            fromPartial(object: Partial<_293.SignedHeader>): _293.SignedHeader;
            fromAmino(object: _293.SignedHeaderAmino): _293.SignedHeader;
            toAmino(message: _293.SignedHeader): _293.SignedHeaderAmino;
            fromAminoMsg(object: _293.SignedHeaderAminoMsg): _293.SignedHeader;
            fromProtoMsg(message: _293.SignedHeaderProtoMsg): _293.SignedHeader;
            toProto(message: _293.SignedHeader): Uint8Array;
            toProtoMsg(message: _293.SignedHeader): _293.SignedHeaderProtoMsg;
        };
        LightBlock: {
            encode(message: _293.LightBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.LightBlock;
            fromJSON(object: any): _293.LightBlock;
            toJSON(message: _293.LightBlock): unknown;
            fromPartial(object: Partial<_293.LightBlock>): _293.LightBlock;
            fromAmino(object: _293.LightBlockAmino): _293.LightBlock;
            toAmino(message: _293.LightBlock): _293.LightBlockAmino;
            fromAminoMsg(object: _293.LightBlockAminoMsg): _293.LightBlock;
            fromProtoMsg(message: _293.LightBlockProtoMsg): _293.LightBlock;
            toProto(message: _293.LightBlock): Uint8Array;
            toProtoMsg(message: _293.LightBlock): _293.LightBlockProtoMsg;
        };
        BlockMeta: {
            encode(message: _293.BlockMeta, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.BlockMeta;
            fromJSON(object: any): _293.BlockMeta;
            toJSON(message: _293.BlockMeta): unknown;
            fromPartial(object: Partial<_293.BlockMeta>): _293.BlockMeta;
            fromAmino(object: _293.BlockMetaAmino): _293.BlockMeta;
            toAmino(message: _293.BlockMeta): _293.BlockMetaAmino;
            fromAminoMsg(object: _293.BlockMetaAminoMsg): _293.BlockMeta;
            fromProtoMsg(message: _293.BlockMetaProtoMsg): _293.BlockMeta;
            toProto(message: _293.BlockMeta): Uint8Array;
            toProtoMsg(message: _293.BlockMeta): _293.BlockMetaProtoMsg;
        };
        TxProof: {
            encode(message: _293.TxProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.TxProof;
            fromJSON(object: any): _293.TxProof;
            toJSON(message: _293.TxProof): unknown;
            fromPartial(object: Partial<_293.TxProof>): _293.TxProof;
            fromAmino(object: _293.TxProofAmino): _293.TxProof;
            toAmino(message: _293.TxProof): _293.TxProofAmino;
            fromAminoMsg(object: _293.TxProofAminoMsg): _293.TxProof;
            fromProtoMsg(message: _293.TxProofProtoMsg): _293.TxProof;
            toProto(message: _293.TxProof): Uint8Array;
            toProtoMsg(message: _293.TxProof): _293.TxProofProtoMsg;
        };
        ConsensusParams: {
            encode(message: _292.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _292.ConsensusParams;
            fromJSON(object: any): _292.ConsensusParams;
            toJSON(message: _292.ConsensusParams): unknown;
            fromPartial(object: Partial<_292.ConsensusParams>): _292.ConsensusParams;
            fromAmino(object: _292.ConsensusParamsAmino): _292.ConsensusParams;
            toAmino(message: _292.ConsensusParams): _292.ConsensusParamsAmino;
            fromAminoMsg(object: _292.ConsensusParamsAminoMsg): _292.ConsensusParams;
            fromProtoMsg(message: _292.ConsensusParamsProtoMsg): _292.ConsensusParams;
            toProto(message: _292.ConsensusParams): Uint8Array;
            toProtoMsg(message: _292.ConsensusParams): _292.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _292.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _292.BlockParams;
            fromJSON(object: any): _292.BlockParams;
            toJSON(message: _292.BlockParams): unknown;
            fromPartial(object: Partial<_292.BlockParams>): _292.BlockParams;
            fromAmino(object: _292.BlockParamsAmino): _292.BlockParams;
            toAmino(message: _292.BlockParams): _292.BlockParamsAmino;
            fromAminoMsg(object: _292.BlockParamsAminoMsg): _292.BlockParams;
            fromProtoMsg(message: _292.BlockParamsProtoMsg): _292.BlockParams;
            toProto(message: _292.BlockParams): Uint8Array;
            toProtoMsg(message: _292.BlockParams): _292.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            encode(message: _292.EvidenceParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _292.EvidenceParams;
            fromJSON(object: any): _292.EvidenceParams;
            toJSON(message: _292.EvidenceParams): unknown;
            fromPartial(object: Partial<_292.EvidenceParams>): _292.EvidenceParams;
            fromAmino(object: _292.EvidenceParamsAmino): _292.EvidenceParams;
            toAmino(message: _292.EvidenceParams): _292.EvidenceParamsAmino;
            fromAminoMsg(object: _292.EvidenceParamsAminoMsg): _292.EvidenceParams;
            fromProtoMsg(message: _292.EvidenceParamsProtoMsg): _292.EvidenceParams;
            toProto(message: _292.EvidenceParams): Uint8Array;
            toProtoMsg(message: _292.EvidenceParams): _292.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            encode(message: _292.ValidatorParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _292.ValidatorParams;
            fromJSON(object: any): _292.ValidatorParams;
            toJSON(message: _292.ValidatorParams): unknown;
            fromPartial(object: Partial<_292.ValidatorParams>): _292.ValidatorParams;
            fromAmino(object: _292.ValidatorParamsAmino): _292.ValidatorParams;
            toAmino(message: _292.ValidatorParams): _292.ValidatorParamsAmino;
            fromAminoMsg(object: _292.ValidatorParamsAminoMsg): _292.ValidatorParams;
            fromProtoMsg(message: _292.ValidatorParamsProtoMsg): _292.ValidatorParams;
            toProto(message: _292.ValidatorParams): Uint8Array;
            toProtoMsg(message: _292.ValidatorParams): _292.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            encode(message: _292.VersionParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _292.VersionParams;
            fromJSON(object: any): _292.VersionParams;
            toJSON(message: _292.VersionParams): unknown;
            fromPartial(object: Partial<_292.VersionParams>): _292.VersionParams;
            fromAmino(object: _292.VersionParamsAmino): _292.VersionParams;
            toAmino(message: _292.VersionParams): _292.VersionParamsAmino;
            fromAminoMsg(object: _292.VersionParamsAminoMsg): _292.VersionParams;
            fromProtoMsg(message: _292.VersionParamsProtoMsg): _292.VersionParams;
            toProto(message: _292.VersionParams): Uint8Array;
            toProtoMsg(message: _292.VersionParams): _292.VersionParamsProtoMsg;
        };
        HashedParams: {
            encode(message: _292.HashedParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _292.HashedParams;
            fromJSON(object: any): _292.HashedParams;
            toJSON(message: _292.HashedParams): unknown;
            fromPartial(object: Partial<_292.HashedParams>): _292.HashedParams;
            fromAmino(object: _292.HashedParamsAmino): _292.HashedParams;
            toAmino(message: _292.HashedParams): _292.HashedParamsAmino;
            fromAminoMsg(object: _292.HashedParamsAminoMsg): _292.HashedParams;
            fromProtoMsg(message: _292.HashedParamsProtoMsg): _292.HashedParams;
            toProto(message: _292.HashedParams): Uint8Array;
            toProtoMsg(message: _292.HashedParams): _292.HashedParamsProtoMsg;
        };
        Evidence: {
            encode(message: _291.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _291.Evidence;
            fromJSON(object: any): _291.Evidence;
            toJSON(message: _291.Evidence): unknown;
            fromPartial(object: Partial<_291.Evidence>): _291.Evidence;
            fromAmino(object: _291.EvidenceAmino): _291.Evidence;
            toAmino(message: _291.Evidence): _291.EvidenceAmino;
            fromAminoMsg(object: _291.EvidenceAminoMsg): _291.Evidence;
            fromProtoMsg(message: _291.EvidenceProtoMsg): _291.Evidence;
            toProto(message: _291.Evidence): Uint8Array;
            toProtoMsg(message: _291.Evidence): _291.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            encode(message: _291.DuplicateVoteEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _291.DuplicateVoteEvidence;
            fromJSON(object: any): _291.DuplicateVoteEvidence;
            toJSON(message: _291.DuplicateVoteEvidence): unknown;
            fromPartial(object: Partial<_291.DuplicateVoteEvidence>): _291.DuplicateVoteEvidence;
            fromAmino(object: _291.DuplicateVoteEvidenceAmino): _291.DuplicateVoteEvidence;
            toAmino(message: _291.DuplicateVoteEvidence): _291.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _291.DuplicateVoteEvidenceAminoMsg): _291.DuplicateVoteEvidence;
            fromProtoMsg(message: _291.DuplicateVoteEvidenceProtoMsg): _291.DuplicateVoteEvidence;
            toProto(message: _291.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _291.DuplicateVoteEvidence): _291.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            encode(message: _291.LightClientAttackEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _291.LightClientAttackEvidence;
            fromJSON(object: any): _291.LightClientAttackEvidence;
            toJSON(message: _291.LightClientAttackEvidence): unknown;
            fromPartial(object: Partial<_291.LightClientAttackEvidence>): _291.LightClientAttackEvidence;
            fromAmino(object: _291.LightClientAttackEvidenceAmino): _291.LightClientAttackEvidence;
            toAmino(message: _291.LightClientAttackEvidence): _291.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _291.LightClientAttackEvidenceAminoMsg): _291.LightClientAttackEvidence;
            fromProtoMsg(message: _291.LightClientAttackEvidenceProtoMsg): _291.LightClientAttackEvidence;
            toProto(message: _291.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _291.LightClientAttackEvidence): _291.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            encode(message: _291.EvidenceList, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _291.EvidenceList;
            fromJSON(object: any): _291.EvidenceList;
            toJSON(message: _291.EvidenceList): unknown;
            fromPartial(object: Partial<_291.EvidenceList>): _291.EvidenceList;
            fromAmino(object: _291.EvidenceListAmino): _291.EvidenceList;
            toAmino(message: _291.EvidenceList): _291.EvidenceListAmino;
            fromAminoMsg(object: _291.EvidenceListAminoMsg): _291.EvidenceList;
            fromProtoMsg(message: _291.EvidenceListProtoMsg): _291.EvidenceList;
            toProto(message: _291.EvidenceList): Uint8Array;
            toProtoMsg(message: _291.EvidenceList): _291.EvidenceListProtoMsg;
        };
        Block: {
            encode(message: _290.Block, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.Block;
            fromJSON(object: any): _290.Block;
            toJSON(message: _290.Block): unknown;
            fromPartial(object: Partial<_290.Block>): _290.Block;
            fromAmino(object: _290.BlockAmino): _290.Block;
            toAmino(message: _290.Block): _290.BlockAmino;
            fromAminoMsg(object: _290.BlockAminoMsg): _290.Block;
            fromProtoMsg(message: _290.BlockProtoMsg): _290.Block;
            toProto(message: _290.Block): Uint8Array;
            toProtoMsg(message: _290.Block): _290.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            encode(message: _295.App, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _295.App;
            fromJSON(object: any): _295.App;
            toJSON(message: _295.App): unknown;
            fromPartial(object: Partial<_295.App>): _295.App;
            fromAmino(object: _295.AppAmino): _295.App;
            toAmino(message: _295.App): _295.AppAmino;
            fromAminoMsg(object: _295.AppAminoMsg): _295.App;
            fromProtoMsg(message: _295.AppProtoMsg): _295.App;
            toProto(message: _295.App): Uint8Array;
            toProtoMsg(message: _295.App): _295.AppProtoMsg;
        };
        Consensus: {
            encode(message: _295.Consensus, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _295.Consensus;
            fromJSON(object: any): _295.Consensus;
            toJSON(message: _295.Consensus): unknown;
            fromPartial(object: Partial<_295.Consensus>): _295.Consensus;
            fromAmino(object: _295.ConsensusAmino): _295.Consensus;
            toAmino(message: _295.Consensus): _295.ConsensusAmino;
            fromAminoMsg(object: _295.ConsensusAminoMsg): _295.Consensus;
            fromProtoMsg(message: _295.ConsensusProtoMsg): _295.Consensus;
            toProto(message: _295.Consensus): Uint8Array;
            toProtoMsg(message: _295.Consensus): _295.ConsensusProtoMsg;
        };
    };
}
