import * as _279 from "./api/http";
import * as _280 from "./protobuf/any";
import * as _281 from "./protobuf/descriptor";
import * as _282 from "./protobuf/duration";
import * as _283 from "./protobuf/empty";
import * as _284 from "./protobuf/timestamp";
export declare namespace google {
    const api: {
        Http: {
            encode(message: _279.Http, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _279.Http;
            fromJSON(object: any): _279.Http;
            toJSON(message: _279.Http): unknown;
            fromPartial(object: Partial<_279.Http>): _279.Http;
            fromAmino(object: _279.HttpAmino): _279.Http;
            toAmino(message: _279.Http): _279.HttpAmino;
            fromAminoMsg(object: _279.HttpAminoMsg): _279.Http;
            fromProtoMsg(message: _279.HttpProtoMsg): _279.Http;
            toProto(message: _279.Http): Uint8Array;
            toProtoMsg(message: _279.Http): _279.HttpProtoMsg;
        };
        HttpRule: {
            encode(message: _279.HttpRule, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _279.HttpRule;
            fromJSON(object: any): _279.HttpRule;
            toJSON(message: _279.HttpRule): unknown;
            fromPartial(object: Partial<_279.HttpRule>): _279.HttpRule;
            fromAmino(object: _279.HttpRuleAmino): _279.HttpRule;
            toAmino(message: _279.HttpRule): _279.HttpRuleAmino;
            fromAminoMsg(object: _279.HttpRuleAminoMsg): _279.HttpRule;
            fromProtoMsg(message: _279.HttpRuleProtoMsg): _279.HttpRule;
            toProto(message: _279.HttpRule): Uint8Array;
            toProtoMsg(message: _279.HttpRule): _279.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            encode(message: _279.CustomHttpPattern, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _279.CustomHttpPattern;
            fromJSON(object: any): _279.CustomHttpPattern;
            toJSON(message: _279.CustomHttpPattern): unknown;
            fromPartial(object: Partial<_279.CustomHttpPattern>): _279.CustomHttpPattern;
            fromAmino(object: _279.CustomHttpPatternAmino): _279.CustomHttpPattern;
            toAmino(message: _279.CustomHttpPattern): _279.CustomHttpPatternAmino;
            fromAminoMsg(object: _279.CustomHttpPatternAminoMsg): _279.CustomHttpPattern;
            fromProtoMsg(message: _279.CustomHttpPatternProtoMsg): _279.CustomHttpPattern;
            toProto(message: _279.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _279.CustomHttpPattern): _279.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Timestamp: {
            encode(message: _284.Timestamp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _284.Timestamp;
            fromJSON(object: any): _284.Timestamp;
            toJSON(message: _284.Timestamp): unknown;
            fromPartial(object: Partial<_284.Timestamp>): _284.Timestamp;
            fromAmino(object: string): _284.Timestamp;
            toAmino(message: _284.Timestamp): string;
            fromAminoMsg(object: _284.TimestampAminoMsg): _284.Timestamp;
            fromProtoMsg(message: _284.TimestampProtoMsg): _284.Timestamp;
            toProto(message: _284.Timestamp): Uint8Array;
            toProtoMsg(message: _284.Timestamp): _284.TimestampProtoMsg;
        };
        Empty: {
            encode(_: _283.Empty, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _283.Empty;
            fromJSON(_: any): _283.Empty;
            toJSON(_: _283.Empty): unknown;
            fromPartial(_: Partial<_283.Empty>): _283.Empty;
            fromAmino(_: _283.EmptyAmino): _283.Empty;
            toAmino(_: _283.Empty): _283.EmptyAmino;
            fromAminoMsg(object: _283.EmptyAminoMsg): _283.Empty;
            fromProtoMsg(message: _283.EmptyProtoMsg): _283.Empty;
            toProto(message: _283.Empty): Uint8Array;
            toProtoMsg(message: _283.Empty): _283.EmptyProtoMsg;
        };
        Duration: {
            encode(message: _282.Duration, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _282.Duration;
            fromJSON(object: any): _282.Duration;
            toJSON(message: _282.Duration): unknown;
            fromPartial(object: Partial<_282.Duration>): _282.Duration;
            fromAmino(object: string): _282.Duration;
            toAmino(message: _282.Duration): string;
            fromAminoMsg(object: _282.DurationAminoMsg): _282.Duration;
            fromProtoMsg(message: _282.DurationProtoMsg): _282.Duration;
            toProto(message: _282.Duration): Uint8Array;
            toProtoMsg(message: _282.Duration): _282.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _281.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _281.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _281.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _281.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _281.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _281.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _281.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _281.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _281.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _281.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _281.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _281.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _281.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _281.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _281.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _281.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _281.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _281.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _281.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _281.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _281.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _281.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _281.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _281.FieldOptions_CType;
        FieldOptions_JSType: typeof _281.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _281.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _281.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _281.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _281.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _281.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            encode(message: _281.FileDescriptorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.FileDescriptorSet;
            fromJSON(object: any): _281.FileDescriptorSet;
            toJSON(message: _281.FileDescriptorSet): unknown;
            fromPartial(object: Partial<_281.FileDescriptorSet>): _281.FileDescriptorSet;
            fromAmino(object: _281.FileDescriptorSetAmino): _281.FileDescriptorSet;
            toAmino(message: _281.FileDescriptorSet): _281.FileDescriptorSetAmino;
            fromAminoMsg(object: _281.FileDescriptorSetAminoMsg): _281.FileDescriptorSet;
            fromProtoMsg(message: _281.FileDescriptorSetProtoMsg): _281.FileDescriptorSet;
            toProto(message: _281.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _281.FileDescriptorSet): _281.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            encode(message: _281.FileDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.FileDescriptorProto;
            fromJSON(object: any): _281.FileDescriptorProto;
            toJSON(message: _281.FileDescriptorProto): unknown;
            fromPartial(object: Partial<_281.FileDescriptorProto>): _281.FileDescriptorProto;
            fromAmino(object: _281.FileDescriptorProtoAmino): _281.FileDescriptorProto;
            toAmino(message: _281.FileDescriptorProto): _281.FileDescriptorProtoAmino;
            fromAminoMsg(object: _281.FileDescriptorProtoAminoMsg): _281.FileDescriptorProto;
            fromProtoMsg(message: _281.FileDescriptorProtoProtoMsg): _281.FileDescriptorProto;
            toProto(message: _281.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _281.FileDescriptorProto): _281.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            encode(message: _281.DescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.DescriptorProto;
            fromJSON(object: any): _281.DescriptorProto;
            toJSON(message: _281.DescriptorProto): unknown;
            fromPartial(object: Partial<_281.DescriptorProto>): _281.DescriptorProto;
            fromAmino(object: _281.DescriptorProtoAmino): _281.DescriptorProto;
            toAmino(message: _281.DescriptorProto): _281.DescriptorProtoAmino;
            fromAminoMsg(object: _281.DescriptorProtoAminoMsg): _281.DescriptorProto;
            fromProtoMsg(message: _281.DescriptorProtoProtoMsg): _281.DescriptorProto;
            toProto(message: _281.DescriptorProto): Uint8Array;
            toProtoMsg(message: _281.DescriptorProto): _281.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            encode(message: _281.DescriptorProto_ExtensionRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.DescriptorProto_ExtensionRange;
            fromJSON(object: any): _281.DescriptorProto_ExtensionRange;
            toJSON(message: _281.DescriptorProto_ExtensionRange): unknown;
            fromPartial(object: Partial<_281.DescriptorProto_ExtensionRange>): _281.DescriptorProto_ExtensionRange;
            fromAmino(object: _281.DescriptorProto_ExtensionRangeAmino): _281.DescriptorProto_ExtensionRange;
            toAmino(message: _281.DescriptorProto_ExtensionRange): _281.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _281.DescriptorProto_ExtensionRangeAminoMsg): _281.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _281.DescriptorProto_ExtensionRangeProtoMsg): _281.DescriptorProto_ExtensionRange;
            toProto(message: _281.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _281.DescriptorProto_ExtensionRange): _281.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            encode(message: _281.DescriptorProto_ReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.DescriptorProto_ReservedRange;
            fromJSON(object: any): _281.DescriptorProto_ReservedRange;
            toJSON(message: _281.DescriptorProto_ReservedRange): unknown;
            fromPartial(object: Partial<_281.DescriptorProto_ReservedRange>): _281.DescriptorProto_ReservedRange;
            fromAmino(object: _281.DescriptorProto_ReservedRangeAmino): _281.DescriptorProto_ReservedRange;
            toAmino(message: _281.DescriptorProto_ReservedRange): _281.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _281.DescriptorProto_ReservedRangeAminoMsg): _281.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _281.DescriptorProto_ReservedRangeProtoMsg): _281.DescriptorProto_ReservedRange;
            toProto(message: _281.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _281.DescriptorProto_ReservedRange): _281.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            encode(message: _281.ExtensionRangeOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.ExtensionRangeOptions;
            fromJSON(object: any): _281.ExtensionRangeOptions;
            toJSON(message: _281.ExtensionRangeOptions): unknown;
            fromPartial(object: Partial<_281.ExtensionRangeOptions>): _281.ExtensionRangeOptions;
            fromAmino(object: _281.ExtensionRangeOptionsAmino): _281.ExtensionRangeOptions;
            toAmino(message: _281.ExtensionRangeOptions): _281.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _281.ExtensionRangeOptionsAminoMsg): _281.ExtensionRangeOptions;
            fromProtoMsg(message: _281.ExtensionRangeOptionsProtoMsg): _281.ExtensionRangeOptions;
            toProto(message: _281.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _281.ExtensionRangeOptions): _281.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            encode(message: _281.FieldDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.FieldDescriptorProto;
            fromJSON(object: any): _281.FieldDescriptorProto;
            toJSON(message: _281.FieldDescriptorProto): unknown;
            fromPartial(object: Partial<_281.FieldDescriptorProto>): _281.FieldDescriptorProto;
            fromAmino(object: _281.FieldDescriptorProtoAmino): _281.FieldDescriptorProto;
            toAmino(message: _281.FieldDescriptorProto): _281.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _281.FieldDescriptorProtoAminoMsg): _281.FieldDescriptorProto;
            fromProtoMsg(message: _281.FieldDescriptorProtoProtoMsg): _281.FieldDescriptorProto;
            toProto(message: _281.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _281.FieldDescriptorProto): _281.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            encode(message: _281.OneofDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.OneofDescriptorProto;
            fromJSON(object: any): _281.OneofDescriptorProto;
            toJSON(message: _281.OneofDescriptorProto): unknown;
            fromPartial(object: Partial<_281.OneofDescriptorProto>): _281.OneofDescriptorProto;
            fromAmino(object: _281.OneofDescriptorProtoAmino): _281.OneofDescriptorProto;
            toAmino(message: _281.OneofDescriptorProto): _281.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _281.OneofDescriptorProtoAminoMsg): _281.OneofDescriptorProto;
            fromProtoMsg(message: _281.OneofDescriptorProtoProtoMsg): _281.OneofDescriptorProto;
            toProto(message: _281.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _281.OneofDescriptorProto): _281.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            encode(message: _281.EnumDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.EnumDescriptorProto;
            fromJSON(object: any): _281.EnumDescriptorProto;
            toJSON(message: _281.EnumDescriptorProto): unknown;
            fromPartial(object: Partial<_281.EnumDescriptorProto>): _281.EnumDescriptorProto;
            fromAmino(object: _281.EnumDescriptorProtoAmino): _281.EnumDescriptorProto;
            toAmino(message: _281.EnumDescriptorProto): _281.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _281.EnumDescriptorProtoAminoMsg): _281.EnumDescriptorProto;
            fromProtoMsg(message: _281.EnumDescriptorProtoProtoMsg): _281.EnumDescriptorProto;
            toProto(message: _281.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _281.EnumDescriptorProto): _281.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            encode(message: _281.EnumDescriptorProto_EnumReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.EnumDescriptorProto_EnumReservedRange;
            fromJSON(object: any): _281.EnumDescriptorProto_EnumReservedRange;
            toJSON(message: _281.EnumDescriptorProto_EnumReservedRange): unknown;
            fromPartial(object: Partial<_281.EnumDescriptorProto_EnumReservedRange>): _281.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _281.EnumDescriptorProto_EnumReservedRangeAmino): _281.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _281.EnumDescriptorProto_EnumReservedRange): _281.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _281.EnumDescriptorProto_EnumReservedRangeAminoMsg): _281.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _281.EnumDescriptorProto_EnumReservedRangeProtoMsg): _281.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _281.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _281.EnumDescriptorProto_EnumReservedRange): _281.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            encode(message: _281.EnumValueDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.EnumValueDescriptorProto;
            fromJSON(object: any): _281.EnumValueDescriptorProto;
            toJSON(message: _281.EnumValueDescriptorProto): unknown;
            fromPartial(object: Partial<_281.EnumValueDescriptorProto>): _281.EnumValueDescriptorProto;
            fromAmino(object: _281.EnumValueDescriptorProtoAmino): _281.EnumValueDescriptorProto;
            toAmino(message: _281.EnumValueDescriptorProto): _281.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _281.EnumValueDescriptorProtoAminoMsg): _281.EnumValueDescriptorProto;
            fromProtoMsg(message: _281.EnumValueDescriptorProtoProtoMsg): _281.EnumValueDescriptorProto;
            toProto(message: _281.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _281.EnumValueDescriptorProto): _281.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            encode(message: _281.ServiceDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.ServiceDescriptorProto;
            fromJSON(object: any): _281.ServiceDescriptorProto;
            toJSON(message: _281.ServiceDescriptorProto): unknown;
            fromPartial(object: Partial<_281.ServiceDescriptorProto>): _281.ServiceDescriptorProto;
            fromAmino(object: _281.ServiceDescriptorProtoAmino): _281.ServiceDescriptorProto;
            toAmino(message: _281.ServiceDescriptorProto): _281.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _281.ServiceDescriptorProtoAminoMsg): _281.ServiceDescriptorProto;
            fromProtoMsg(message: _281.ServiceDescriptorProtoProtoMsg): _281.ServiceDescriptorProto;
            toProto(message: _281.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _281.ServiceDescriptorProto): _281.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            encode(message: _281.MethodDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.MethodDescriptorProto;
            fromJSON(object: any): _281.MethodDescriptorProto;
            toJSON(message: _281.MethodDescriptorProto): unknown;
            fromPartial(object: Partial<_281.MethodDescriptorProto>): _281.MethodDescriptorProto;
            fromAmino(object: _281.MethodDescriptorProtoAmino): _281.MethodDescriptorProto;
            toAmino(message: _281.MethodDescriptorProto): _281.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _281.MethodDescriptorProtoAminoMsg): _281.MethodDescriptorProto;
            fromProtoMsg(message: _281.MethodDescriptorProtoProtoMsg): _281.MethodDescriptorProto;
            toProto(message: _281.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _281.MethodDescriptorProto): _281.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            encode(message: _281.FileOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.FileOptions;
            fromJSON(object: any): _281.FileOptions;
            toJSON(message: _281.FileOptions): unknown;
            fromPartial(object: Partial<_281.FileOptions>): _281.FileOptions;
            fromAmino(object: _281.FileOptionsAmino): _281.FileOptions;
            toAmino(message: _281.FileOptions): _281.FileOptionsAmino;
            fromAminoMsg(object: _281.FileOptionsAminoMsg): _281.FileOptions;
            fromProtoMsg(message: _281.FileOptionsProtoMsg): _281.FileOptions;
            toProto(message: _281.FileOptions): Uint8Array;
            toProtoMsg(message: _281.FileOptions): _281.FileOptionsProtoMsg;
        };
        MessageOptions: {
            encode(message: _281.MessageOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.MessageOptions;
            fromJSON(object: any): _281.MessageOptions;
            toJSON(message: _281.MessageOptions): unknown;
            fromPartial(object: Partial<_281.MessageOptions>): _281.MessageOptions;
            fromAmino(object: _281.MessageOptionsAmino): _281.MessageOptions;
            toAmino(message: _281.MessageOptions): _281.MessageOptionsAmino;
            fromAminoMsg(object: _281.MessageOptionsAminoMsg): _281.MessageOptions;
            fromProtoMsg(message: _281.MessageOptionsProtoMsg): _281.MessageOptions;
            toProto(message: _281.MessageOptions): Uint8Array;
            toProtoMsg(message: _281.MessageOptions): _281.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            encode(message: _281.FieldOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.FieldOptions;
            fromJSON(object: any): _281.FieldOptions;
            toJSON(message: _281.FieldOptions): unknown;
            fromPartial(object: Partial<_281.FieldOptions>): _281.FieldOptions;
            fromAmino(object: _281.FieldOptionsAmino): _281.FieldOptions;
            toAmino(message: _281.FieldOptions): _281.FieldOptionsAmino;
            fromAminoMsg(object: _281.FieldOptionsAminoMsg): _281.FieldOptions;
            fromProtoMsg(message: _281.FieldOptionsProtoMsg): _281.FieldOptions;
            toProto(message: _281.FieldOptions): Uint8Array;
            toProtoMsg(message: _281.FieldOptions): _281.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            encode(message: _281.OneofOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.OneofOptions;
            fromJSON(object: any): _281.OneofOptions;
            toJSON(message: _281.OneofOptions): unknown;
            fromPartial(object: Partial<_281.OneofOptions>): _281.OneofOptions;
            fromAmino(object: _281.OneofOptionsAmino): _281.OneofOptions;
            toAmino(message: _281.OneofOptions): _281.OneofOptionsAmino;
            fromAminoMsg(object: _281.OneofOptionsAminoMsg): _281.OneofOptions;
            fromProtoMsg(message: _281.OneofOptionsProtoMsg): _281.OneofOptions;
            toProto(message: _281.OneofOptions): Uint8Array;
            toProtoMsg(message: _281.OneofOptions): _281.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            encode(message: _281.EnumOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.EnumOptions;
            fromJSON(object: any): _281.EnumOptions;
            toJSON(message: _281.EnumOptions): unknown;
            fromPartial(object: Partial<_281.EnumOptions>): _281.EnumOptions;
            fromAmino(object: _281.EnumOptionsAmino): _281.EnumOptions;
            toAmino(message: _281.EnumOptions): _281.EnumOptionsAmino;
            fromAminoMsg(object: _281.EnumOptionsAminoMsg): _281.EnumOptions;
            fromProtoMsg(message: _281.EnumOptionsProtoMsg): _281.EnumOptions;
            toProto(message: _281.EnumOptions): Uint8Array;
            toProtoMsg(message: _281.EnumOptions): _281.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            encode(message: _281.EnumValueOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.EnumValueOptions;
            fromJSON(object: any): _281.EnumValueOptions;
            toJSON(message: _281.EnumValueOptions): unknown;
            fromPartial(object: Partial<_281.EnumValueOptions>): _281.EnumValueOptions;
            fromAmino(object: _281.EnumValueOptionsAmino): _281.EnumValueOptions;
            toAmino(message: _281.EnumValueOptions): _281.EnumValueOptionsAmino;
            fromAminoMsg(object: _281.EnumValueOptionsAminoMsg): _281.EnumValueOptions;
            fromProtoMsg(message: _281.EnumValueOptionsProtoMsg): _281.EnumValueOptions;
            toProto(message: _281.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _281.EnumValueOptions): _281.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            encode(message: _281.ServiceOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.ServiceOptions;
            fromJSON(object: any): _281.ServiceOptions;
            toJSON(message: _281.ServiceOptions): unknown;
            fromPartial(object: Partial<_281.ServiceOptions>): _281.ServiceOptions;
            fromAmino(object: _281.ServiceOptionsAmino): _281.ServiceOptions;
            toAmino(message: _281.ServiceOptions): _281.ServiceOptionsAmino;
            fromAminoMsg(object: _281.ServiceOptionsAminoMsg): _281.ServiceOptions;
            fromProtoMsg(message: _281.ServiceOptionsProtoMsg): _281.ServiceOptions;
            toProto(message: _281.ServiceOptions): Uint8Array;
            toProtoMsg(message: _281.ServiceOptions): _281.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            encode(message: _281.MethodOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.MethodOptions;
            fromJSON(object: any): _281.MethodOptions;
            toJSON(message: _281.MethodOptions): unknown;
            fromPartial(object: Partial<_281.MethodOptions>): _281.MethodOptions;
            fromAmino(object: _281.MethodOptionsAmino): _281.MethodOptions;
            toAmino(message: _281.MethodOptions): _281.MethodOptionsAmino;
            fromAminoMsg(object: _281.MethodOptionsAminoMsg): _281.MethodOptions;
            fromProtoMsg(message: _281.MethodOptionsProtoMsg): _281.MethodOptions;
            toProto(message: _281.MethodOptions): Uint8Array;
            toProtoMsg(message: _281.MethodOptions): _281.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            encode(message: _281.UninterpretedOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.UninterpretedOption;
            fromJSON(object: any): _281.UninterpretedOption;
            toJSON(message: _281.UninterpretedOption): unknown;
            fromPartial(object: Partial<_281.UninterpretedOption>): _281.UninterpretedOption;
            fromAmino(object: _281.UninterpretedOptionAmino): _281.UninterpretedOption;
            toAmino(message: _281.UninterpretedOption): _281.UninterpretedOptionAmino;
            fromAminoMsg(object: _281.UninterpretedOptionAminoMsg): _281.UninterpretedOption;
            fromProtoMsg(message: _281.UninterpretedOptionProtoMsg): _281.UninterpretedOption;
            toProto(message: _281.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _281.UninterpretedOption): _281.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            encode(message: _281.UninterpretedOption_NamePart, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.UninterpretedOption_NamePart;
            fromJSON(object: any): _281.UninterpretedOption_NamePart;
            toJSON(message: _281.UninterpretedOption_NamePart): unknown;
            fromPartial(object: Partial<_281.UninterpretedOption_NamePart>): _281.UninterpretedOption_NamePart;
            fromAmino(object: _281.UninterpretedOption_NamePartAmino): _281.UninterpretedOption_NamePart;
            toAmino(message: _281.UninterpretedOption_NamePart): _281.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _281.UninterpretedOption_NamePartAminoMsg): _281.UninterpretedOption_NamePart;
            fromProtoMsg(message: _281.UninterpretedOption_NamePartProtoMsg): _281.UninterpretedOption_NamePart;
            toProto(message: _281.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _281.UninterpretedOption_NamePart): _281.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            encode(message: _281.SourceCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.SourceCodeInfo;
            fromJSON(object: any): _281.SourceCodeInfo;
            toJSON(message: _281.SourceCodeInfo): unknown;
            fromPartial(object: Partial<_281.SourceCodeInfo>): _281.SourceCodeInfo;
            fromAmino(object: _281.SourceCodeInfoAmino): _281.SourceCodeInfo;
            toAmino(message: _281.SourceCodeInfo): _281.SourceCodeInfoAmino;
            fromAminoMsg(object: _281.SourceCodeInfoAminoMsg): _281.SourceCodeInfo;
            fromProtoMsg(message: _281.SourceCodeInfoProtoMsg): _281.SourceCodeInfo;
            toProto(message: _281.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _281.SourceCodeInfo): _281.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            encode(message: _281.SourceCodeInfo_Location, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.SourceCodeInfo_Location;
            fromJSON(object: any): _281.SourceCodeInfo_Location;
            toJSON(message: _281.SourceCodeInfo_Location): unknown;
            fromPartial(object: Partial<_281.SourceCodeInfo_Location>): _281.SourceCodeInfo_Location;
            fromAmino(object: _281.SourceCodeInfo_LocationAmino): _281.SourceCodeInfo_Location;
            toAmino(message: _281.SourceCodeInfo_Location): _281.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _281.SourceCodeInfo_LocationAminoMsg): _281.SourceCodeInfo_Location;
            fromProtoMsg(message: _281.SourceCodeInfo_LocationProtoMsg): _281.SourceCodeInfo_Location;
            toProto(message: _281.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _281.SourceCodeInfo_Location): _281.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            encode(message: _281.GeneratedCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.GeneratedCodeInfo;
            fromJSON(object: any): _281.GeneratedCodeInfo;
            toJSON(message: _281.GeneratedCodeInfo): unknown;
            fromPartial(object: Partial<_281.GeneratedCodeInfo>): _281.GeneratedCodeInfo;
            fromAmino(object: _281.GeneratedCodeInfoAmino): _281.GeneratedCodeInfo;
            toAmino(message: _281.GeneratedCodeInfo): _281.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _281.GeneratedCodeInfoAminoMsg): _281.GeneratedCodeInfo;
            fromProtoMsg(message: _281.GeneratedCodeInfoProtoMsg): _281.GeneratedCodeInfo;
            toProto(message: _281.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _281.GeneratedCodeInfo): _281.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            encode(message: _281.GeneratedCodeInfo_Annotation, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _281.GeneratedCodeInfo_Annotation;
            fromJSON(object: any): _281.GeneratedCodeInfo_Annotation;
            toJSON(message: _281.GeneratedCodeInfo_Annotation): unknown;
            fromPartial(object: Partial<_281.GeneratedCodeInfo_Annotation>): _281.GeneratedCodeInfo_Annotation;
            fromAmino(object: _281.GeneratedCodeInfo_AnnotationAmino): _281.GeneratedCodeInfo_Annotation;
            toAmino(message: _281.GeneratedCodeInfo_Annotation): _281.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _281.GeneratedCodeInfo_AnnotationAminoMsg): _281.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _281.GeneratedCodeInfo_AnnotationProtoMsg): _281.GeneratedCodeInfo_Annotation;
            toProto(message: _281.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _281.GeneratedCodeInfo_Annotation): _281.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            encode(message: _280.Any, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _280.Any;
            fromJSON(object: any): _280.Any;
            toJSON(message: _280.Any): unknown;
            fromPartial(object: Partial<_280.Any>): _280.Any;
            fromAmino(object: _280.AnyAmino): _280.Any;
            toAmino(message: _280.Any): _280.AnyAmino;
            fromAminoMsg(object: _280.AnyAminoMsg): _280.Any;
            fromProtoMsg(message: _280.AnyProtoMsg): _280.Any;
            toProto(message: _280.Any): Uint8Array;
            toProtoMsg(message: _280.Any): _280.AnyProtoMsg;
        };
    };
}
