import * as _288 from "./api/http";
import * as _289 from "./protobuf/any";
import * as _290 from "./protobuf/descriptor";
import * as _291 from "./protobuf/duration";
import * as _292 from "./protobuf/empty";
import * as _293 from "./protobuf/timestamp";
export declare namespace google {
    const api: {
        Http: {
            encode(message: _288.Http, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _288.Http;
            fromJSON(object: any): _288.Http;
            toJSON(message: _288.Http): unknown;
            fromPartial(object: Partial<_288.Http>): _288.Http;
            fromAmino(object: _288.HttpAmino): _288.Http;
            toAmino(message: _288.Http): _288.HttpAmino;
            fromAminoMsg(object: _288.HttpAminoMsg): _288.Http;
            fromProtoMsg(message: _288.HttpProtoMsg): _288.Http;
            toProto(message: _288.Http): Uint8Array;
            toProtoMsg(message: _288.Http): _288.HttpProtoMsg;
        };
        HttpRule: {
            encode(message: _288.HttpRule, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _288.HttpRule;
            fromJSON(object: any): _288.HttpRule;
            toJSON(message: _288.HttpRule): unknown;
            fromPartial(object: Partial<_288.HttpRule>): _288.HttpRule;
            fromAmino(object: _288.HttpRuleAmino): _288.HttpRule;
            toAmino(message: _288.HttpRule): _288.HttpRuleAmino;
            fromAminoMsg(object: _288.HttpRuleAminoMsg): _288.HttpRule;
            fromProtoMsg(message: _288.HttpRuleProtoMsg): _288.HttpRule;
            toProto(message: _288.HttpRule): Uint8Array;
            toProtoMsg(message: _288.HttpRule): _288.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            encode(message: _288.CustomHttpPattern, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _288.CustomHttpPattern;
            fromJSON(object: any): _288.CustomHttpPattern;
            toJSON(message: _288.CustomHttpPattern): unknown;
            fromPartial(object: Partial<_288.CustomHttpPattern>): _288.CustomHttpPattern;
            fromAmino(object: _288.CustomHttpPatternAmino): _288.CustomHttpPattern;
            toAmino(message: _288.CustomHttpPattern): _288.CustomHttpPatternAmino;
            fromAminoMsg(object: _288.CustomHttpPatternAminoMsg): _288.CustomHttpPattern;
            fromProtoMsg(message: _288.CustomHttpPatternProtoMsg): _288.CustomHttpPattern;
            toProto(message: _288.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _288.CustomHttpPattern): _288.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Timestamp: {
            encode(message: _293.Timestamp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _293.Timestamp;
            fromJSON(object: any): _293.Timestamp;
            toJSON(message: _293.Timestamp): unknown;
            fromPartial(object: Partial<_293.Timestamp>): _293.Timestamp;
            fromAmino(object: string): _293.Timestamp;
            toAmino(message: _293.Timestamp): string;
            fromAminoMsg(object: _293.TimestampAminoMsg): _293.Timestamp;
            fromProtoMsg(message: _293.TimestampProtoMsg): _293.Timestamp;
            toProto(message: _293.Timestamp): Uint8Array;
            toProtoMsg(message: _293.Timestamp): _293.TimestampProtoMsg;
        };
        Empty: {
            encode(_: _292.Empty, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _292.Empty;
            fromJSON(_: any): _292.Empty;
            toJSON(_: _292.Empty): unknown;
            fromPartial(_: Partial<_292.Empty>): _292.Empty;
            fromAmino(_: _292.EmptyAmino): _292.Empty;
            toAmino(_: _292.Empty): _292.EmptyAmino;
            fromAminoMsg(object: _292.EmptyAminoMsg): _292.Empty;
            fromProtoMsg(message: _292.EmptyProtoMsg): _292.Empty;
            toProto(message: _292.Empty): Uint8Array;
            toProtoMsg(message: _292.Empty): _292.EmptyProtoMsg;
        };
        Duration: {
            encode(message: _291.Duration, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _291.Duration;
            fromJSON(object: any): _291.Duration;
            toJSON(message: _291.Duration): unknown;
            fromPartial(object: Partial<_291.Duration>): _291.Duration;
            fromAmino(object: string): _291.Duration;
            toAmino(message: _291.Duration): string;
            fromAminoMsg(object: _291.DurationAminoMsg): _291.Duration;
            fromProtoMsg(message: _291.DurationProtoMsg): _291.Duration;
            toProto(message: _291.Duration): Uint8Array;
            toProtoMsg(message: _291.Duration): _291.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _290.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _290.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _290.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _290.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _290.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _290.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _290.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _290.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _290.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _290.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _290.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _290.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _290.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _290.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _290.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _290.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _290.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _290.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _290.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _290.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _290.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _290.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _290.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _290.FieldOptions_CType;
        FieldOptions_JSType: typeof _290.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _290.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _290.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _290.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _290.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _290.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            encode(message: _290.FileDescriptorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.FileDescriptorSet;
            fromJSON(object: any): _290.FileDescriptorSet;
            toJSON(message: _290.FileDescriptorSet): unknown;
            fromPartial(object: Partial<_290.FileDescriptorSet>): _290.FileDescriptorSet;
            fromAmino(object: _290.FileDescriptorSetAmino): _290.FileDescriptorSet;
            toAmino(message: _290.FileDescriptorSet): _290.FileDescriptorSetAmino;
            fromAminoMsg(object: _290.FileDescriptorSetAminoMsg): _290.FileDescriptorSet;
            fromProtoMsg(message: _290.FileDescriptorSetProtoMsg): _290.FileDescriptorSet;
            toProto(message: _290.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _290.FileDescriptorSet): _290.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            encode(message: _290.FileDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.FileDescriptorProto;
            fromJSON(object: any): _290.FileDescriptorProto;
            toJSON(message: _290.FileDescriptorProto): unknown;
            fromPartial(object: Partial<_290.FileDescriptorProto>): _290.FileDescriptorProto;
            fromAmino(object: _290.FileDescriptorProtoAmino): _290.FileDescriptorProto;
            toAmino(message: _290.FileDescriptorProto): _290.FileDescriptorProtoAmino;
            fromAminoMsg(object: _290.FileDescriptorProtoAminoMsg): _290.FileDescriptorProto;
            fromProtoMsg(message: _290.FileDescriptorProtoProtoMsg): _290.FileDescriptorProto;
            toProto(message: _290.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _290.FileDescriptorProto): _290.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            encode(message: _290.DescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.DescriptorProto;
            fromJSON(object: any): _290.DescriptorProto;
            toJSON(message: _290.DescriptorProto): unknown;
            fromPartial(object: Partial<_290.DescriptorProto>): _290.DescriptorProto;
            fromAmino(object: _290.DescriptorProtoAmino): _290.DescriptorProto;
            toAmino(message: _290.DescriptorProto): _290.DescriptorProtoAmino;
            fromAminoMsg(object: _290.DescriptorProtoAminoMsg): _290.DescriptorProto;
            fromProtoMsg(message: _290.DescriptorProtoProtoMsg): _290.DescriptorProto;
            toProto(message: _290.DescriptorProto): Uint8Array;
            toProtoMsg(message: _290.DescriptorProto): _290.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            encode(message: _290.DescriptorProto_ExtensionRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.DescriptorProto_ExtensionRange;
            fromJSON(object: any): _290.DescriptorProto_ExtensionRange;
            toJSON(message: _290.DescriptorProto_ExtensionRange): unknown;
            fromPartial(object: Partial<_290.DescriptorProto_ExtensionRange>): _290.DescriptorProto_ExtensionRange;
            fromAmino(object: _290.DescriptorProto_ExtensionRangeAmino): _290.DescriptorProto_ExtensionRange;
            toAmino(message: _290.DescriptorProto_ExtensionRange): _290.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _290.DescriptorProto_ExtensionRangeAminoMsg): _290.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _290.DescriptorProto_ExtensionRangeProtoMsg): _290.DescriptorProto_ExtensionRange;
            toProto(message: _290.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _290.DescriptorProto_ExtensionRange): _290.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            encode(message: _290.DescriptorProto_ReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.DescriptorProto_ReservedRange;
            fromJSON(object: any): _290.DescriptorProto_ReservedRange;
            toJSON(message: _290.DescriptorProto_ReservedRange): unknown;
            fromPartial(object: Partial<_290.DescriptorProto_ReservedRange>): _290.DescriptorProto_ReservedRange;
            fromAmino(object: _290.DescriptorProto_ReservedRangeAmino): _290.DescriptorProto_ReservedRange;
            toAmino(message: _290.DescriptorProto_ReservedRange): _290.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _290.DescriptorProto_ReservedRangeAminoMsg): _290.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _290.DescriptorProto_ReservedRangeProtoMsg): _290.DescriptorProto_ReservedRange;
            toProto(message: _290.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _290.DescriptorProto_ReservedRange): _290.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            encode(message: _290.ExtensionRangeOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.ExtensionRangeOptions;
            fromJSON(object: any): _290.ExtensionRangeOptions;
            toJSON(message: _290.ExtensionRangeOptions): unknown;
            fromPartial(object: Partial<_290.ExtensionRangeOptions>): _290.ExtensionRangeOptions;
            fromAmino(object: _290.ExtensionRangeOptionsAmino): _290.ExtensionRangeOptions;
            toAmino(message: _290.ExtensionRangeOptions): _290.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _290.ExtensionRangeOptionsAminoMsg): _290.ExtensionRangeOptions;
            fromProtoMsg(message: _290.ExtensionRangeOptionsProtoMsg): _290.ExtensionRangeOptions;
            toProto(message: _290.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _290.ExtensionRangeOptions): _290.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            encode(message: _290.FieldDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.FieldDescriptorProto;
            fromJSON(object: any): _290.FieldDescriptorProto;
            toJSON(message: _290.FieldDescriptorProto): unknown;
            fromPartial(object: Partial<_290.FieldDescriptorProto>): _290.FieldDescriptorProto;
            fromAmino(object: _290.FieldDescriptorProtoAmino): _290.FieldDescriptorProto;
            toAmino(message: _290.FieldDescriptorProto): _290.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _290.FieldDescriptorProtoAminoMsg): _290.FieldDescriptorProto;
            fromProtoMsg(message: _290.FieldDescriptorProtoProtoMsg): _290.FieldDescriptorProto;
            toProto(message: _290.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _290.FieldDescriptorProto): _290.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            encode(message: _290.OneofDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.OneofDescriptorProto;
            fromJSON(object: any): _290.OneofDescriptorProto;
            toJSON(message: _290.OneofDescriptorProto): unknown;
            fromPartial(object: Partial<_290.OneofDescriptorProto>): _290.OneofDescriptorProto;
            fromAmino(object: _290.OneofDescriptorProtoAmino): _290.OneofDescriptorProto;
            toAmino(message: _290.OneofDescriptorProto): _290.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _290.OneofDescriptorProtoAminoMsg): _290.OneofDescriptorProto;
            fromProtoMsg(message: _290.OneofDescriptorProtoProtoMsg): _290.OneofDescriptorProto;
            toProto(message: _290.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _290.OneofDescriptorProto): _290.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            encode(message: _290.EnumDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.EnumDescriptorProto;
            fromJSON(object: any): _290.EnumDescriptorProto;
            toJSON(message: _290.EnumDescriptorProto): unknown;
            fromPartial(object: Partial<_290.EnumDescriptorProto>): _290.EnumDescriptorProto;
            fromAmino(object: _290.EnumDescriptorProtoAmino): _290.EnumDescriptorProto;
            toAmino(message: _290.EnumDescriptorProto): _290.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _290.EnumDescriptorProtoAminoMsg): _290.EnumDescriptorProto;
            fromProtoMsg(message: _290.EnumDescriptorProtoProtoMsg): _290.EnumDescriptorProto;
            toProto(message: _290.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _290.EnumDescriptorProto): _290.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            encode(message: _290.EnumDescriptorProto_EnumReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.EnumDescriptorProto_EnumReservedRange;
            fromJSON(object: any): _290.EnumDescriptorProto_EnumReservedRange;
            toJSON(message: _290.EnumDescriptorProto_EnumReservedRange): unknown;
            fromPartial(object: Partial<_290.EnumDescriptorProto_EnumReservedRange>): _290.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _290.EnumDescriptorProto_EnumReservedRangeAmino): _290.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _290.EnumDescriptorProto_EnumReservedRange): _290.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _290.EnumDescriptorProto_EnumReservedRangeAminoMsg): _290.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _290.EnumDescriptorProto_EnumReservedRangeProtoMsg): _290.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _290.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _290.EnumDescriptorProto_EnumReservedRange): _290.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            encode(message: _290.EnumValueDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.EnumValueDescriptorProto;
            fromJSON(object: any): _290.EnumValueDescriptorProto;
            toJSON(message: _290.EnumValueDescriptorProto): unknown;
            fromPartial(object: Partial<_290.EnumValueDescriptorProto>): _290.EnumValueDescriptorProto;
            fromAmino(object: _290.EnumValueDescriptorProtoAmino): _290.EnumValueDescriptorProto;
            toAmino(message: _290.EnumValueDescriptorProto): _290.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _290.EnumValueDescriptorProtoAminoMsg): _290.EnumValueDescriptorProto;
            fromProtoMsg(message: _290.EnumValueDescriptorProtoProtoMsg): _290.EnumValueDescriptorProto;
            toProto(message: _290.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _290.EnumValueDescriptorProto): _290.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            encode(message: _290.ServiceDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.ServiceDescriptorProto;
            fromJSON(object: any): _290.ServiceDescriptorProto;
            toJSON(message: _290.ServiceDescriptorProto): unknown;
            fromPartial(object: Partial<_290.ServiceDescriptorProto>): _290.ServiceDescriptorProto;
            fromAmino(object: _290.ServiceDescriptorProtoAmino): _290.ServiceDescriptorProto;
            toAmino(message: _290.ServiceDescriptorProto): _290.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _290.ServiceDescriptorProtoAminoMsg): _290.ServiceDescriptorProto;
            fromProtoMsg(message: _290.ServiceDescriptorProtoProtoMsg): _290.ServiceDescriptorProto;
            toProto(message: _290.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _290.ServiceDescriptorProto): _290.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            encode(message: _290.MethodDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.MethodDescriptorProto;
            fromJSON(object: any): _290.MethodDescriptorProto;
            toJSON(message: _290.MethodDescriptorProto): unknown;
            fromPartial(object: Partial<_290.MethodDescriptorProto>): _290.MethodDescriptorProto;
            fromAmino(object: _290.MethodDescriptorProtoAmino): _290.MethodDescriptorProto;
            toAmino(message: _290.MethodDescriptorProto): _290.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _290.MethodDescriptorProtoAminoMsg): _290.MethodDescriptorProto;
            fromProtoMsg(message: _290.MethodDescriptorProtoProtoMsg): _290.MethodDescriptorProto;
            toProto(message: _290.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _290.MethodDescriptorProto): _290.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            encode(message: _290.FileOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.FileOptions;
            fromJSON(object: any): _290.FileOptions;
            toJSON(message: _290.FileOptions): unknown;
            fromPartial(object: Partial<_290.FileOptions>): _290.FileOptions;
            fromAmino(object: _290.FileOptionsAmino): _290.FileOptions;
            toAmino(message: _290.FileOptions): _290.FileOptionsAmino;
            fromAminoMsg(object: _290.FileOptionsAminoMsg): _290.FileOptions;
            fromProtoMsg(message: _290.FileOptionsProtoMsg): _290.FileOptions;
            toProto(message: _290.FileOptions): Uint8Array;
            toProtoMsg(message: _290.FileOptions): _290.FileOptionsProtoMsg;
        };
        MessageOptions: {
            encode(message: _290.MessageOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.MessageOptions;
            fromJSON(object: any): _290.MessageOptions;
            toJSON(message: _290.MessageOptions): unknown;
            fromPartial(object: Partial<_290.MessageOptions>): _290.MessageOptions;
            fromAmino(object: _290.MessageOptionsAmino): _290.MessageOptions;
            toAmino(message: _290.MessageOptions): _290.MessageOptionsAmino;
            fromAminoMsg(object: _290.MessageOptionsAminoMsg): _290.MessageOptions;
            fromProtoMsg(message: _290.MessageOptionsProtoMsg): _290.MessageOptions;
            toProto(message: _290.MessageOptions): Uint8Array;
            toProtoMsg(message: _290.MessageOptions): _290.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            encode(message: _290.FieldOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.FieldOptions;
            fromJSON(object: any): _290.FieldOptions;
            toJSON(message: _290.FieldOptions): unknown;
            fromPartial(object: Partial<_290.FieldOptions>): _290.FieldOptions;
            fromAmino(object: _290.FieldOptionsAmino): _290.FieldOptions;
            toAmino(message: _290.FieldOptions): _290.FieldOptionsAmino;
            fromAminoMsg(object: _290.FieldOptionsAminoMsg): _290.FieldOptions;
            fromProtoMsg(message: _290.FieldOptionsProtoMsg): _290.FieldOptions;
            toProto(message: _290.FieldOptions): Uint8Array;
            toProtoMsg(message: _290.FieldOptions): _290.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            encode(message: _290.OneofOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.OneofOptions;
            fromJSON(object: any): _290.OneofOptions;
            toJSON(message: _290.OneofOptions): unknown;
            fromPartial(object: Partial<_290.OneofOptions>): _290.OneofOptions;
            fromAmino(object: _290.OneofOptionsAmino): _290.OneofOptions;
            toAmino(message: _290.OneofOptions): _290.OneofOptionsAmino;
            fromAminoMsg(object: _290.OneofOptionsAminoMsg): _290.OneofOptions;
            fromProtoMsg(message: _290.OneofOptionsProtoMsg): _290.OneofOptions;
            toProto(message: _290.OneofOptions): Uint8Array;
            toProtoMsg(message: _290.OneofOptions): _290.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            encode(message: _290.EnumOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.EnumOptions;
            fromJSON(object: any): _290.EnumOptions;
            toJSON(message: _290.EnumOptions): unknown;
            fromPartial(object: Partial<_290.EnumOptions>): _290.EnumOptions;
            fromAmino(object: _290.EnumOptionsAmino): _290.EnumOptions;
            toAmino(message: _290.EnumOptions): _290.EnumOptionsAmino;
            fromAminoMsg(object: _290.EnumOptionsAminoMsg): _290.EnumOptions;
            fromProtoMsg(message: _290.EnumOptionsProtoMsg): _290.EnumOptions;
            toProto(message: _290.EnumOptions): Uint8Array;
            toProtoMsg(message: _290.EnumOptions): _290.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            encode(message: _290.EnumValueOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.EnumValueOptions;
            fromJSON(object: any): _290.EnumValueOptions;
            toJSON(message: _290.EnumValueOptions): unknown;
            fromPartial(object: Partial<_290.EnumValueOptions>): _290.EnumValueOptions;
            fromAmino(object: _290.EnumValueOptionsAmino): _290.EnumValueOptions;
            toAmino(message: _290.EnumValueOptions): _290.EnumValueOptionsAmino;
            fromAminoMsg(object: _290.EnumValueOptionsAminoMsg): _290.EnumValueOptions;
            fromProtoMsg(message: _290.EnumValueOptionsProtoMsg): _290.EnumValueOptions;
            toProto(message: _290.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _290.EnumValueOptions): _290.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            encode(message: _290.ServiceOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.ServiceOptions;
            fromJSON(object: any): _290.ServiceOptions;
            toJSON(message: _290.ServiceOptions): unknown;
            fromPartial(object: Partial<_290.ServiceOptions>): _290.ServiceOptions;
            fromAmino(object: _290.ServiceOptionsAmino): _290.ServiceOptions;
            toAmino(message: _290.ServiceOptions): _290.ServiceOptionsAmino;
            fromAminoMsg(object: _290.ServiceOptionsAminoMsg): _290.ServiceOptions;
            fromProtoMsg(message: _290.ServiceOptionsProtoMsg): _290.ServiceOptions;
            toProto(message: _290.ServiceOptions): Uint8Array;
            toProtoMsg(message: _290.ServiceOptions): _290.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            encode(message: _290.MethodOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.MethodOptions;
            fromJSON(object: any): _290.MethodOptions;
            toJSON(message: _290.MethodOptions): unknown;
            fromPartial(object: Partial<_290.MethodOptions>): _290.MethodOptions;
            fromAmino(object: _290.MethodOptionsAmino): _290.MethodOptions;
            toAmino(message: _290.MethodOptions): _290.MethodOptionsAmino;
            fromAminoMsg(object: _290.MethodOptionsAminoMsg): _290.MethodOptions;
            fromProtoMsg(message: _290.MethodOptionsProtoMsg): _290.MethodOptions;
            toProto(message: _290.MethodOptions): Uint8Array;
            toProtoMsg(message: _290.MethodOptions): _290.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            encode(message: _290.UninterpretedOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.UninterpretedOption;
            fromJSON(object: any): _290.UninterpretedOption;
            toJSON(message: _290.UninterpretedOption): unknown;
            fromPartial(object: Partial<_290.UninterpretedOption>): _290.UninterpretedOption;
            fromAmino(object: _290.UninterpretedOptionAmino): _290.UninterpretedOption;
            toAmino(message: _290.UninterpretedOption): _290.UninterpretedOptionAmino;
            fromAminoMsg(object: _290.UninterpretedOptionAminoMsg): _290.UninterpretedOption;
            fromProtoMsg(message: _290.UninterpretedOptionProtoMsg): _290.UninterpretedOption;
            toProto(message: _290.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _290.UninterpretedOption): _290.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            encode(message: _290.UninterpretedOption_NamePart, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.UninterpretedOption_NamePart;
            fromJSON(object: any): _290.UninterpretedOption_NamePart;
            toJSON(message: _290.UninterpretedOption_NamePart): unknown;
            fromPartial(object: Partial<_290.UninterpretedOption_NamePart>): _290.UninterpretedOption_NamePart;
            fromAmino(object: _290.UninterpretedOption_NamePartAmino): _290.UninterpretedOption_NamePart;
            toAmino(message: _290.UninterpretedOption_NamePart): _290.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _290.UninterpretedOption_NamePartAminoMsg): _290.UninterpretedOption_NamePart;
            fromProtoMsg(message: _290.UninterpretedOption_NamePartProtoMsg): _290.UninterpretedOption_NamePart;
            toProto(message: _290.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _290.UninterpretedOption_NamePart): _290.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            encode(message: _290.SourceCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.SourceCodeInfo;
            fromJSON(object: any): _290.SourceCodeInfo;
            toJSON(message: _290.SourceCodeInfo): unknown;
            fromPartial(object: Partial<_290.SourceCodeInfo>): _290.SourceCodeInfo;
            fromAmino(object: _290.SourceCodeInfoAmino): _290.SourceCodeInfo;
            toAmino(message: _290.SourceCodeInfo): _290.SourceCodeInfoAmino;
            fromAminoMsg(object: _290.SourceCodeInfoAminoMsg): _290.SourceCodeInfo;
            fromProtoMsg(message: _290.SourceCodeInfoProtoMsg): _290.SourceCodeInfo;
            toProto(message: _290.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _290.SourceCodeInfo): _290.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            encode(message: _290.SourceCodeInfo_Location, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.SourceCodeInfo_Location;
            fromJSON(object: any): _290.SourceCodeInfo_Location;
            toJSON(message: _290.SourceCodeInfo_Location): unknown;
            fromPartial(object: Partial<_290.SourceCodeInfo_Location>): _290.SourceCodeInfo_Location;
            fromAmino(object: _290.SourceCodeInfo_LocationAmino): _290.SourceCodeInfo_Location;
            toAmino(message: _290.SourceCodeInfo_Location): _290.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _290.SourceCodeInfo_LocationAminoMsg): _290.SourceCodeInfo_Location;
            fromProtoMsg(message: _290.SourceCodeInfo_LocationProtoMsg): _290.SourceCodeInfo_Location;
            toProto(message: _290.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _290.SourceCodeInfo_Location): _290.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            encode(message: _290.GeneratedCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.GeneratedCodeInfo;
            fromJSON(object: any): _290.GeneratedCodeInfo;
            toJSON(message: _290.GeneratedCodeInfo): unknown;
            fromPartial(object: Partial<_290.GeneratedCodeInfo>): _290.GeneratedCodeInfo;
            fromAmino(object: _290.GeneratedCodeInfoAmino): _290.GeneratedCodeInfo;
            toAmino(message: _290.GeneratedCodeInfo): _290.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _290.GeneratedCodeInfoAminoMsg): _290.GeneratedCodeInfo;
            fromProtoMsg(message: _290.GeneratedCodeInfoProtoMsg): _290.GeneratedCodeInfo;
            toProto(message: _290.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _290.GeneratedCodeInfo): _290.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            encode(message: _290.GeneratedCodeInfo_Annotation, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _290.GeneratedCodeInfo_Annotation;
            fromJSON(object: any): _290.GeneratedCodeInfo_Annotation;
            toJSON(message: _290.GeneratedCodeInfo_Annotation): unknown;
            fromPartial(object: Partial<_290.GeneratedCodeInfo_Annotation>): _290.GeneratedCodeInfo_Annotation;
            fromAmino(object: _290.GeneratedCodeInfo_AnnotationAmino): _290.GeneratedCodeInfo_Annotation;
            toAmino(message: _290.GeneratedCodeInfo_Annotation): _290.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _290.GeneratedCodeInfo_AnnotationAminoMsg): _290.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _290.GeneratedCodeInfo_AnnotationProtoMsg): _290.GeneratedCodeInfo_Annotation;
            toProto(message: _290.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _290.GeneratedCodeInfo_Annotation): _290.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            encode(message: _289.Any, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _289.Any;
            fromJSON(object: any): _289.Any;
            toJSON(message: _289.Any): unknown;
            fromPartial(object: Partial<_289.Any>): _289.Any;
            fromAmino(object: _289.AnyAmino): _289.Any;
            toAmino(message: _289.Any): _289.AnyAmino;
            fromAminoMsg(object: _289.AnyAminoMsg): _289.Any;
            fromProtoMsg(message: _289.AnyProtoMsg): _289.Any;
            toProto(message: _289.Any): Uint8Array;
            toProtoMsg(message: _289.Any): _289.AnyProtoMsg;
        };
    };
}
