import * as _296 from "./api/http";
import * as _297 from "./protobuf/any";
import * as _298 from "./protobuf/descriptor";
import * as _299 from "./protobuf/duration";
import * as _300 from "./protobuf/empty";
import * as _301 from "./protobuf/timestamp";
export declare namespace google {
    const api: {
        Http: {
            encode(message: _296.Http, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _296.Http;
            fromJSON(object: any): _296.Http;
            toJSON(message: _296.Http): unknown;
            fromPartial(object: Partial<_296.Http>): _296.Http;
            fromAmino(object: _296.HttpAmino): _296.Http;
            toAmino(message: _296.Http): _296.HttpAmino;
            fromAminoMsg(object: _296.HttpAminoMsg): _296.Http;
            fromProtoMsg(message: _296.HttpProtoMsg): _296.Http;
            toProto(message: _296.Http): Uint8Array;
            toProtoMsg(message: _296.Http): _296.HttpProtoMsg;
        };
        HttpRule: {
            encode(message: _296.HttpRule, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _296.HttpRule;
            fromJSON(object: any): _296.HttpRule;
            toJSON(message: _296.HttpRule): unknown;
            fromPartial(object: Partial<_296.HttpRule>): _296.HttpRule;
            fromAmino(object: _296.HttpRuleAmino): _296.HttpRule;
            toAmino(message: _296.HttpRule): _296.HttpRuleAmino;
            fromAminoMsg(object: _296.HttpRuleAminoMsg): _296.HttpRule;
            fromProtoMsg(message: _296.HttpRuleProtoMsg): _296.HttpRule;
            toProto(message: _296.HttpRule): Uint8Array;
            toProtoMsg(message: _296.HttpRule): _296.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            encode(message: _296.CustomHttpPattern, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _296.CustomHttpPattern;
            fromJSON(object: any): _296.CustomHttpPattern;
            toJSON(message: _296.CustomHttpPattern): unknown;
            fromPartial(object: Partial<_296.CustomHttpPattern>): _296.CustomHttpPattern;
            fromAmino(object: _296.CustomHttpPatternAmino): _296.CustomHttpPattern;
            toAmino(message: _296.CustomHttpPattern): _296.CustomHttpPatternAmino;
            fromAminoMsg(object: _296.CustomHttpPatternAminoMsg): _296.CustomHttpPattern;
            fromProtoMsg(message: _296.CustomHttpPatternProtoMsg): _296.CustomHttpPattern;
            toProto(message: _296.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _296.CustomHttpPattern): _296.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Timestamp: {
            encode(message: _301.Timestamp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _301.Timestamp;
            fromJSON(object: any): _301.Timestamp;
            toJSON(message: _301.Timestamp): unknown;
            fromPartial(object: Partial<_301.Timestamp>): _301.Timestamp;
            fromAmino(object: string): _301.Timestamp;
            toAmino(message: _301.Timestamp): string;
            fromAminoMsg(object: _301.TimestampAminoMsg): _301.Timestamp;
            fromProtoMsg(message: _301.TimestampProtoMsg): _301.Timestamp;
            toProto(message: _301.Timestamp): Uint8Array;
            toProtoMsg(message: _301.Timestamp): _301.TimestampProtoMsg;
        };
        Empty: {
            encode(_: _300.Empty, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _300.Empty;
            fromJSON(_: any): _300.Empty;
            toJSON(_: _300.Empty): unknown;
            fromPartial(_: Partial<_300.Empty>): _300.Empty;
            fromAmino(_: _300.EmptyAmino): _300.Empty;
            toAmino(_: _300.Empty): _300.EmptyAmino;
            fromAminoMsg(object: _300.EmptyAminoMsg): _300.Empty;
            fromProtoMsg(message: _300.EmptyProtoMsg): _300.Empty;
            toProto(message: _300.Empty): Uint8Array;
            toProtoMsg(message: _300.Empty): _300.EmptyProtoMsg;
        };
        Duration: {
            encode(message: _299.Duration, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _299.Duration;
            fromJSON(object: any): _299.Duration;
            toJSON(message: _299.Duration): unknown;
            fromPartial(object: Partial<_299.Duration>): _299.Duration;
            fromAmino(object: string): _299.Duration;
            toAmino(message: _299.Duration): string;
            fromAminoMsg(object: _299.DurationAminoMsg): _299.Duration;
            fromProtoMsg(message: _299.DurationProtoMsg): _299.Duration;
            toProto(message: _299.Duration): Uint8Array;
            toProtoMsg(message: _299.Duration): _299.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _298.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _298.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _298.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _298.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _298.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _298.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _298.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _298.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _298.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _298.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _298.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _298.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _298.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _298.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _298.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _298.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _298.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _298.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _298.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _298.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _298.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _298.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _298.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _298.FieldOptions_CType;
        FieldOptions_JSType: typeof _298.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _298.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _298.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _298.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _298.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _298.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            encode(message: _298.FileDescriptorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.FileDescriptorSet;
            fromJSON(object: any): _298.FileDescriptorSet;
            toJSON(message: _298.FileDescriptorSet): unknown;
            fromPartial(object: Partial<_298.FileDescriptorSet>): _298.FileDescriptorSet;
            fromAmino(object: _298.FileDescriptorSetAmino): _298.FileDescriptorSet;
            toAmino(message: _298.FileDescriptorSet): _298.FileDescriptorSetAmino;
            fromAminoMsg(object: _298.FileDescriptorSetAminoMsg): _298.FileDescriptorSet;
            fromProtoMsg(message: _298.FileDescriptorSetProtoMsg): _298.FileDescriptorSet;
            toProto(message: _298.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _298.FileDescriptorSet): _298.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            encode(message: _298.FileDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.FileDescriptorProto;
            fromJSON(object: any): _298.FileDescriptorProto;
            toJSON(message: _298.FileDescriptorProto): unknown;
            fromPartial(object: Partial<_298.FileDescriptorProto>): _298.FileDescriptorProto;
            fromAmino(object: _298.FileDescriptorProtoAmino): _298.FileDescriptorProto;
            toAmino(message: _298.FileDescriptorProto): _298.FileDescriptorProtoAmino;
            fromAminoMsg(object: _298.FileDescriptorProtoAminoMsg): _298.FileDescriptorProto;
            fromProtoMsg(message: _298.FileDescriptorProtoProtoMsg): _298.FileDescriptorProto;
            toProto(message: _298.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _298.FileDescriptorProto): _298.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            encode(message: _298.DescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.DescriptorProto;
            fromJSON(object: any): _298.DescriptorProto;
            toJSON(message: _298.DescriptorProto): unknown;
            fromPartial(object: Partial<_298.DescriptorProto>): _298.DescriptorProto;
            fromAmino(object: _298.DescriptorProtoAmino): _298.DescriptorProto;
            toAmino(message: _298.DescriptorProto): _298.DescriptorProtoAmino;
            fromAminoMsg(object: _298.DescriptorProtoAminoMsg): _298.DescriptorProto;
            fromProtoMsg(message: _298.DescriptorProtoProtoMsg): _298.DescriptorProto;
            toProto(message: _298.DescriptorProto): Uint8Array;
            toProtoMsg(message: _298.DescriptorProto): _298.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            encode(message: _298.DescriptorProto_ExtensionRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.DescriptorProto_ExtensionRange;
            fromJSON(object: any): _298.DescriptorProto_ExtensionRange;
            toJSON(message: _298.DescriptorProto_ExtensionRange): unknown;
            fromPartial(object: Partial<_298.DescriptorProto_ExtensionRange>): _298.DescriptorProto_ExtensionRange;
            fromAmino(object: _298.DescriptorProto_ExtensionRangeAmino): _298.DescriptorProto_ExtensionRange;
            toAmino(message: _298.DescriptorProto_ExtensionRange): _298.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _298.DescriptorProto_ExtensionRangeAminoMsg): _298.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _298.DescriptorProto_ExtensionRangeProtoMsg): _298.DescriptorProto_ExtensionRange;
            toProto(message: _298.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _298.DescriptorProto_ExtensionRange): _298.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            encode(message: _298.DescriptorProto_ReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.DescriptorProto_ReservedRange;
            fromJSON(object: any): _298.DescriptorProto_ReservedRange;
            toJSON(message: _298.DescriptorProto_ReservedRange): unknown;
            fromPartial(object: Partial<_298.DescriptorProto_ReservedRange>): _298.DescriptorProto_ReservedRange;
            fromAmino(object: _298.DescriptorProto_ReservedRangeAmino): _298.DescriptorProto_ReservedRange;
            toAmino(message: _298.DescriptorProto_ReservedRange): _298.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _298.DescriptorProto_ReservedRangeAminoMsg): _298.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _298.DescriptorProto_ReservedRangeProtoMsg): _298.DescriptorProto_ReservedRange;
            toProto(message: _298.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _298.DescriptorProto_ReservedRange): _298.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            encode(message: _298.ExtensionRangeOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.ExtensionRangeOptions;
            fromJSON(object: any): _298.ExtensionRangeOptions;
            toJSON(message: _298.ExtensionRangeOptions): unknown;
            fromPartial(object: Partial<_298.ExtensionRangeOptions>): _298.ExtensionRangeOptions;
            fromAmino(object: _298.ExtensionRangeOptionsAmino): _298.ExtensionRangeOptions;
            toAmino(message: _298.ExtensionRangeOptions): _298.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _298.ExtensionRangeOptionsAminoMsg): _298.ExtensionRangeOptions;
            fromProtoMsg(message: _298.ExtensionRangeOptionsProtoMsg): _298.ExtensionRangeOptions;
            toProto(message: _298.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _298.ExtensionRangeOptions): _298.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            encode(message: _298.FieldDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.FieldDescriptorProto;
            fromJSON(object: any): _298.FieldDescriptorProto;
            toJSON(message: _298.FieldDescriptorProto): unknown;
            fromPartial(object: Partial<_298.FieldDescriptorProto>): _298.FieldDescriptorProto;
            fromAmino(object: _298.FieldDescriptorProtoAmino): _298.FieldDescriptorProto;
            toAmino(message: _298.FieldDescriptorProto): _298.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _298.FieldDescriptorProtoAminoMsg): _298.FieldDescriptorProto;
            fromProtoMsg(message: _298.FieldDescriptorProtoProtoMsg): _298.FieldDescriptorProto;
            toProto(message: _298.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _298.FieldDescriptorProto): _298.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            encode(message: _298.OneofDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.OneofDescriptorProto;
            fromJSON(object: any): _298.OneofDescriptorProto;
            toJSON(message: _298.OneofDescriptorProto): unknown;
            fromPartial(object: Partial<_298.OneofDescriptorProto>): _298.OneofDescriptorProto;
            fromAmino(object: _298.OneofDescriptorProtoAmino): _298.OneofDescriptorProto;
            toAmino(message: _298.OneofDescriptorProto): _298.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _298.OneofDescriptorProtoAminoMsg): _298.OneofDescriptorProto;
            fromProtoMsg(message: _298.OneofDescriptorProtoProtoMsg): _298.OneofDescriptorProto;
            toProto(message: _298.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _298.OneofDescriptorProto): _298.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            encode(message: _298.EnumDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.EnumDescriptorProto;
            fromJSON(object: any): _298.EnumDescriptorProto;
            toJSON(message: _298.EnumDescriptorProto): unknown;
            fromPartial(object: Partial<_298.EnumDescriptorProto>): _298.EnumDescriptorProto;
            fromAmino(object: _298.EnumDescriptorProtoAmino): _298.EnumDescriptorProto;
            toAmino(message: _298.EnumDescriptorProto): _298.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _298.EnumDescriptorProtoAminoMsg): _298.EnumDescriptorProto;
            fromProtoMsg(message: _298.EnumDescriptorProtoProtoMsg): _298.EnumDescriptorProto;
            toProto(message: _298.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _298.EnumDescriptorProto): _298.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            encode(message: _298.EnumDescriptorProto_EnumReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.EnumDescriptorProto_EnumReservedRange;
            fromJSON(object: any): _298.EnumDescriptorProto_EnumReservedRange;
            toJSON(message: _298.EnumDescriptorProto_EnumReservedRange): unknown;
            fromPartial(object: Partial<_298.EnumDescriptorProto_EnumReservedRange>): _298.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _298.EnumDescriptorProto_EnumReservedRangeAmino): _298.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _298.EnumDescriptorProto_EnumReservedRange): _298.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _298.EnumDescriptorProto_EnumReservedRangeAminoMsg): _298.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _298.EnumDescriptorProto_EnumReservedRangeProtoMsg): _298.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _298.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _298.EnumDescriptorProto_EnumReservedRange): _298.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            encode(message: _298.EnumValueDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.EnumValueDescriptorProto;
            fromJSON(object: any): _298.EnumValueDescriptorProto;
            toJSON(message: _298.EnumValueDescriptorProto): unknown;
            fromPartial(object: Partial<_298.EnumValueDescriptorProto>): _298.EnumValueDescriptorProto;
            fromAmino(object: _298.EnumValueDescriptorProtoAmino): _298.EnumValueDescriptorProto;
            toAmino(message: _298.EnumValueDescriptorProto): _298.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _298.EnumValueDescriptorProtoAminoMsg): _298.EnumValueDescriptorProto;
            fromProtoMsg(message: _298.EnumValueDescriptorProtoProtoMsg): _298.EnumValueDescriptorProto;
            toProto(message: _298.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _298.EnumValueDescriptorProto): _298.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            encode(message: _298.ServiceDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.ServiceDescriptorProto;
            fromJSON(object: any): _298.ServiceDescriptorProto;
            toJSON(message: _298.ServiceDescriptorProto): unknown;
            fromPartial(object: Partial<_298.ServiceDescriptorProto>): _298.ServiceDescriptorProto;
            fromAmino(object: _298.ServiceDescriptorProtoAmino): _298.ServiceDescriptorProto;
            toAmino(message: _298.ServiceDescriptorProto): _298.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _298.ServiceDescriptorProtoAminoMsg): _298.ServiceDescriptorProto;
            fromProtoMsg(message: _298.ServiceDescriptorProtoProtoMsg): _298.ServiceDescriptorProto;
            toProto(message: _298.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _298.ServiceDescriptorProto): _298.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            encode(message: _298.MethodDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.MethodDescriptorProto;
            fromJSON(object: any): _298.MethodDescriptorProto;
            toJSON(message: _298.MethodDescriptorProto): unknown;
            fromPartial(object: Partial<_298.MethodDescriptorProto>): _298.MethodDescriptorProto;
            fromAmino(object: _298.MethodDescriptorProtoAmino): _298.MethodDescriptorProto;
            toAmino(message: _298.MethodDescriptorProto): _298.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _298.MethodDescriptorProtoAminoMsg): _298.MethodDescriptorProto;
            fromProtoMsg(message: _298.MethodDescriptorProtoProtoMsg): _298.MethodDescriptorProto;
            toProto(message: _298.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _298.MethodDescriptorProto): _298.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            encode(message: _298.FileOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.FileOptions;
            fromJSON(object: any): _298.FileOptions;
            toJSON(message: _298.FileOptions): unknown;
            fromPartial(object: Partial<_298.FileOptions>): _298.FileOptions;
            fromAmino(object: _298.FileOptionsAmino): _298.FileOptions;
            toAmino(message: _298.FileOptions): _298.FileOptionsAmino;
            fromAminoMsg(object: _298.FileOptionsAminoMsg): _298.FileOptions;
            fromProtoMsg(message: _298.FileOptionsProtoMsg): _298.FileOptions;
            toProto(message: _298.FileOptions): Uint8Array;
            toProtoMsg(message: _298.FileOptions): _298.FileOptionsProtoMsg;
        };
        MessageOptions: {
            encode(message: _298.MessageOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.MessageOptions;
            fromJSON(object: any): _298.MessageOptions;
            toJSON(message: _298.MessageOptions): unknown;
            fromPartial(object: Partial<_298.MessageOptions>): _298.MessageOptions;
            fromAmino(object: _298.MessageOptionsAmino): _298.MessageOptions;
            toAmino(message: _298.MessageOptions): _298.MessageOptionsAmino;
            fromAminoMsg(object: _298.MessageOptionsAminoMsg): _298.MessageOptions;
            fromProtoMsg(message: _298.MessageOptionsProtoMsg): _298.MessageOptions;
            toProto(message: _298.MessageOptions): Uint8Array;
            toProtoMsg(message: _298.MessageOptions): _298.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            encode(message: _298.FieldOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.FieldOptions;
            fromJSON(object: any): _298.FieldOptions;
            toJSON(message: _298.FieldOptions): unknown;
            fromPartial(object: Partial<_298.FieldOptions>): _298.FieldOptions;
            fromAmino(object: _298.FieldOptionsAmino): _298.FieldOptions;
            toAmino(message: _298.FieldOptions): _298.FieldOptionsAmino;
            fromAminoMsg(object: _298.FieldOptionsAminoMsg): _298.FieldOptions;
            fromProtoMsg(message: _298.FieldOptionsProtoMsg): _298.FieldOptions;
            toProto(message: _298.FieldOptions): Uint8Array;
            toProtoMsg(message: _298.FieldOptions): _298.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            encode(message: _298.OneofOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.OneofOptions;
            fromJSON(object: any): _298.OneofOptions;
            toJSON(message: _298.OneofOptions): unknown;
            fromPartial(object: Partial<_298.OneofOptions>): _298.OneofOptions;
            fromAmino(object: _298.OneofOptionsAmino): _298.OneofOptions;
            toAmino(message: _298.OneofOptions): _298.OneofOptionsAmino;
            fromAminoMsg(object: _298.OneofOptionsAminoMsg): _298.OneofOptions;
            fromProtoMsg(message: _298.OneofOptionsProtoMsg): _298.OneofOptions;
            toProto(message: _298.OneofOptions): Uint8Array;
            toProtoMsg(message: _298.OneofOptions): _298.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            encode(message: _298.EnumOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.EnumOptions;
            fromJSON(object: any): _298.EnumOptions;
            toJSON(message: _298.EnumOptions): unknown;
            fromPartial(object: Partial<_298.EnumOptions>): _298.EnumOptions;
            fromAmino(object: _298.EnumOptionsAmino): _298.EnumOptions;
            toAmino(message: _298.EnumOptions): _298.EnumOptionsAmino;
            fromAminoMsg(object: _298.EnumOptionsAminoMsg): _298.EnumOptions;
            fromProtoMsg(message: _298.EnumOptionsProtoMsg): _298.EnumOptions;
            toProto(message: _298.EnumOptions): Uint8Array;
            toProtoMsg(message: _298.EnumOptions): _298.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            encode(message: _298.EnumValueOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.EnumValueOptions;
            fromJSON(object: any): _298.EnumValueOptions;
            toJSON(message: _298.EnumValueOptions): unknown;
            fromPartial(object: Partial<_298.EnumValueOptions>): _298.EnumValueOptions;
            fromAmino(object: _298.EnumValueOptionsAmino): _298.EnumValueOptions;
            toAmino(message: _298.EnumValueOptions): _298.EnumValueOptionsAmino;
            fromAminoMsg(object: _298.EnumValueOptionsAminoMsg): _298.EnumValueOptions;
            fromProtoMsg(message: _298.EnumValueOptionsProtoMsg): _298.EnumValueOptions;
            toProto(message: _298.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _298.EnumValueOptions): _298.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            encode(message: _298.ServiceOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.ServiceOptions;
            fromJSON(object: any): _298.ServiceOptions;
            toJSON(message: _298.ServiceOptions): unknown;
            fromPartial(object: Partial<_298.ServiceOptions>): _298.ServiceOptions;
            fromAmino(object: _298.ServiceOptionsAmino): _298.ServiceOptions;
            toAmino(message: _298.ServiceOptions): _298.ServiceOptionsAmino;
            fromAminoMsg(object: _298.ServiceOptionsAminoMsg): _298.ServiceOptions;
            fromProtoMsg(message: _298.ServiceOptionsProtoMsg): _298.ServiceOptions;
            toProto(message: _298.ServiceOptions): Uint8Array;
            toProtoMsg(message: _298.ServiceOptions): _298.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            encode(message: _298.MethodOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.MethodOptions;
            fromJSON(object: any): _298.MethodOptions;
            toJSON(message: _298.MethodOptions): unknown;
            fromPartial(object: Partial<_298.MethodOptions>): _298.MethodOptions;
            fromAmino(object: _298.MethodOptionsAmino): _298.MethodOptions;
            toAmino(message: _298.MethodOptions): _298.MethodOptionsAmino;
            fromAminoMsg(object: _298.MethodOptionsAminoMsg): _298.MethodOptions;
            fromProtoMsg(message: _298.MethodOptionsProtoMsg): _298.MethodOptions;
            toProto(message: _298.MethodOptions): Uint8Array;
            toProtoMsg(message: _298.MethodOptions): _298.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            encode(message: _298.UninterpretedOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.UninterpretedOption;
            fromJSON(object: any): _298.UninterpretedOption;
            toJSON(message: _298.UninterpretedOption): unknown;
            fromPartial(object: Partial<_298.UninterpretedOption>): _298.UninterpretedOption;
            fromAmino(object: _298.UninterpretedOptionAmino): _298.UninterpretedOption;
            toAmino(message: _298.UninterpretedOption): _298.UninterpretedOptionAmino;
            fromAminoMsg(object: _298.UninterpretedOptionAminoMsg): _298.UninterpretedOption;
            fromProtoMsg(message: _298.UninterpretedOptionProtoMsg): _298.UninterpretedOption;
            toProto(message: _298.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _298.UninterpretedOption): _298.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            encode(message: _298.UninterpretedOption_NamePart, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.UninterpretedOption_NamePart;
            fromJSON(object: any): _298.UninterpretedOption_NamePart;
            toJSON(message: _298.UninterpretedOption_NamePart): unknown;
            fromPartial(object: Partial<_298.UninterpretedOption_NamePart>): _298.UninterpretedOption_NamePart;
            fromAmino(object: _298.UninterpretedOption_NamePartAmino): _298.UninterpretedOption_NamePart;
            toAmino(message: _298.UninterpretedOption_NamePart): _298.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _298.UninterpretedOption_NamePartAminoMsg): _298.UninterpretedOption_NamePart;
            fromProtoMsg(message: _298.UninterpretedOption_NamePartProtoMsg): _298.UninterpretedOption_NamePart;
            toProto(message: _298.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _298.UninterpretedOption_NamePart): _298.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            encode(message: _298.SourceCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.SourceCodeInfo;
            fromJSON(object: any): _298.SourceCodeInfo;
            toJSON(message: _298.SourceCodeInfo): unknown;
            fromPartial(object: Partial<_298.SourceCodeInfo>): _298.SourceCodeInfo;
            fromAmino(object: _298.SourceCodeInfoAmino): _298.SourceCodeInfo;
            toAmino(message: _298.SourceCodeInfo): _298.SourceCodeInfoAmino;
            fromAminoMsg(object: _298.SourceCodeInfoAminoMsg): _298.SourceCodeInfo;
            fromProtoMsg(message: _298.SourceCodeInfoProtoMsg): _298.SourceCodeInfo;
            toProto(message: _298.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _298.SourceCodeInfo): _298.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            encode(message: _298.SourceCodeInfo_Location, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.SourceCodeInfo_Location;
            fromJSON(object: any): _298.SourceCodeInfo_Location;
            toJSON(message: _298.SourceCodeInfo_Location): unknown;
            fromPartial(object: Partial<_298.SourceCodeInfo_Location>): _298.SourceCodeInfo_Location;
            fromAmino(object: _298.SourceCodeInfo_LocationAmino): _298.SourceCodeInfo_Location;
            toAmino(message: _298.SourceCodeInfo_Location): _298.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _298.SourceCodeInfo_LocationAminoMsg): _298.SourceCodeInfo_Location;
            fromProtoMsg(message: _298.SourceCodeInfo_LocationProtoMsg): _298.SourceCodeInfo_Location;
            toProto(message: _298.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _298.SourceCodeInfo_Location): _298.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            encode(message: _298.GeneratedCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.GeneratedCodeInfo;
            fromJSON(object: any): _298.GeneratedCodeInfo;
            toJSON(message: _298.GeneratedCodeInfo): unknown;
            fromPartial(object: Partial<_298.GeneratedCodeInfo>): _298.GeneratedCodeInfo;
            fromAmino(object: _298.GeneratedCodeInfoAmino): _298.GeneratedCodeInfo;
            toAmino(message: _298.GeneratedCodeInfo): _298.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _298.GeneratedCodeInfoAminoMsg): _298.GeneratedCodeInfo;
            fromProtoMsg(message: _298.GeneratedCodeInfoProtoMsg): _298.GeneratedCodeInfo;
            toProto(message: _298.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _298.GeneratedCodeInfo): _298.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            encode(message: _298.GeneratedCodeInfo_Annotation, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _298.GeneratedCodeInfo_Annotation;
            fromJSON(object: any): _298.GeneratedCodeInfo_Annotation;
            toJSON(message: _298.GeneratedCodeInfo_Annotation): unknown;
            fromPartial(object: Partial<_298.GeneratedCodeInfo_Annotation>): _298.GeneratedCodeInfo_Annotation;
            fromAmino(object: _298.GeneratedCodeInfo_AnnotationAmino): _298.GeneratedCodeInfo_Annotation;
            toAmino(message: _298.GeneratedCodeInfo_Annotation): _298.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _298.GeneratedCodeInfo_AnnotationAminoMsg): _298.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _298.GeneratedCodeInfo_AnnotationProtoMsg): _298.GeneratedCodeInfo_Annotation;
            toProto(message: _298.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _298.GeneratedCodeInfo_Annotation): _298.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            encode(message: _297.Any, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _297.Any;
            fromJSON(object: any): _297.Any;
            toJSON(message: _297.Any): unknown;
            fromPartial(object: Partial<_297.Any>): _297.Any;
            fromAmino(object: _297.AnyAmino): _297.Any;
            toAmino(message: _297.Any): _297.AnyAmino;
            fromAminoMsg(object: _297.AnyAminoMsg): _297.Any;
            fromProtoMsg(message: _297.AnyProtoMsg): _297.Any;
            toProto(message: _297.Any): Uint8Array;
            toProtoMsg(message: _297.Any): _297.AnyProtoMsg;
        };
    };
}
